### ISSUE TITLE
Support accepting arguments and passing them to commands

### ISSUE THREAD

**Issue by ssokolow** [sagiegurari/cargo-make#101]
#### Problem Description

I typically write command-line utilities in Rust using `clap` which have required positional arguments. (eg. `command_name [options] <path> ...`)

Currently, I use just's `+args=""` to implement commands like `run-memstats +args=""` (`MALLOC_CONF=stats_print:true cargo run -- {{args}}`) or `kcachegrind +args=""` (run the command inside valgrind, then open up the resulting log in kcachegrind).

While it's not perfect (just doesn't provide an equivalent to `"$@"` so the choices are to only support one argument or not support paths with spaces), cargo-make doesn't seem to provide any mechanism at all for this... which greatly limits its utility to me.

If I use it, I'll probably wind up writing a shell wrapper which handles certain commands itself and then passes the rest through to cargo-make.

**Comment by sagiegurari** [comment]
could you please give an example usage that you were looking for?
that would help me better understand.

**Comment by ssokolow** [comment]
```bash
ssokolow@monolith rdbackup-excludes-indexer [master] %% cargo make run-memstats /srv/fservroot /mnt/buffalo_ext/games 
error: Found argument '/srv/fservroot' which wasn't expected, or isn't valid in this context

USAGE:
    cargo make [FLAGS] [OPTIONS] [--] [TASK]

For more information try --help

```

There should be a way to expose the `[args]...` from the end of the `cargo run [OPTIONS] [--] [args]...` that I call inside that task.

**Comment by sagiegurari** [comment]
ok, i would recommend as env vars for now as part of the cli using the -e cli arg.
lets say cargo-make gets those extra args and keeps them, how would you see them being using in tasks? $CARGO_MAKE_ARG1 $CARGO_MAKE_ARG2 and so on...?

```toml
[tasks.something]
command = "something"
args = ["${CARGO_MAKE_ARG1}", "${CARGO_MAKE_ARG2}"]
```

I don't mind adding that support, but question is if its readable.

**Comment by ssokolow** [comment]
I was thinking something equivalent to `"$@"` in Bourne shell script. (A special token which expands to multiple arguments, preserving their quoting, and is omitted if empty.)

If you have `"a b" "c d"` as input, Bourne shell interprets things like this:

* `$@` --> `"a" "b" "c" "d"`
* `"$@"` --> `"a b" "c d"`
* `"$*"` --> `"a b c d"`

I'd need to see a more thorough reference of your grammar to be sure it's the best fit, but here's one idea:

* Have `${*}` and `${+}` as special variables that expand to more than one argument.
* `${*}` would be omitted if no positional arguments are specified (by analogy to `.*` in a regex), allowing commands where `foo` is valid and `foo /path/to/bar` is valid, but `foo ""` is an error.
* `${+}` would refuse to run the task unless there's at least one positional argument (by analogy to `.+` in a regex).
* You could either require that they be the only things in the argument or, to make them really versatile, you could allow people to write `--input=${+}` and have it expand to `--input="foo" --input="bar" --input="baz"` if the user wrote `cargo make something foo bar baz`.

Suppose I had a `frobnicate` that looked like this:

```toml
[env]
OUTDIR = "target/frobs/"

[tasks.frobnicate]
command = "frobnicate"
args = ["--verbose", "--include=${+}", "${OUTDIR}"]
```

If I typed `cargo make frobnicate foo.md "bar baz.md" quux.md`, then the command that gets run would be `["frobnicate", "--verbose", "--include=foo.inc", "--include=bar baz.inc", "--include=quux.inc", "target/frobs/"]`

...and, if I used `["${*}"]` for the args, then commands would resolve like this:

* `cargo make frobnicate` --> `["frobnicate"]`
* `cargo make frobnicate foo.md "bar baz.md" quux.md` --> `["frobnicate", "foo.md", "bar baz.md", "quux.md"]`

**Comment by sagiegurari** [comment]
thanks, let me think about it a bit.

**Comment by sagiegurari** [comment]
which of these use cases you actually need? I prefer not implement too complex rules that are not readable.

* ${*} expanding to multiple args sounds great. I'll definitely implement that.
* ${+} not crazy about this one. input validations should be done by the actual command and not the task runner. just like bash doesn't do it for you.
* --input=${+} expanding to multiple --input=arg1 --input=arg2 is cool but I'm not sure if its a common use case and might hurt readability.
* I can also concat all args and serve them as an env var to be used in commands/scripts so you can do more complex stuff if needed

**Comment by sagiegurari** [comment]
${*} is now support, you can see the [docs](https://github.com/sagiegurari/cargo-make/tree/0.12.0#usage-task-command-script-task-examplecommand)
you can test it by using branch 0.12.0
please tell me if it works good for you and if you really need those other features.
they are not hard to implement, just need to really think if I should over complicate the usage.

You also have an env var CARGO_MAKE_TASK_ARGS which will hold all those args with ; between them.

**Comment by ssokolow** [comment]
> ${+} not crazy about this one. input validations should be done by the actual command and not the task runner. just like bash doesn't do it for you.

Fair enough... though, before I built on it, my originally idea was actually to have only `${+}` with the `+` implying "additional".

Having only `$(*)` could be counter-intuitive in two ways:

* `*` already means "wildcard" in many contexts.
* In Bourne-compatible shells, `$*` expands to a single arg when quoted, while `"$@"` is the one that expands to the kind of handling you implemented.

> --input=${+} expanding to multiple --input=arg1 --input=arg2 is cool but I'm not sure if its a common use case and might hurt readability.

How so?

Also, sorry I haven't tested the 0.12.0 branch yet. Today was very distracting. I'll try to make time for it tomorrow.

**Comment by sagiegurari** [comment]
* the *->@ is a good point. I'll update that.

* you can still have it all args as a single arg if you do 
```sh
cargo make mytask "arg1 arg2 arg3"
```
in this case, "arg1 arg2 arg3" is considered as a single arg and ${@} would not split it.

* if you really feel the ```--input=${+} expanding to multiple --input=arg1 --input=arg2 ``` is important, I can add it. its not really hard, just worried if people will understand it.

**Comment by ssokolow** [comment]
> please tell me if it works good for you

I did a little testing and I like it.

> you can still have it all args as a single arg if you do [...]

Yeah. The `$*` variable is sort of a niche thing in Bourne shell script and I've never needed to use it.

> if you really feel the --input=${+} expanding to multiple --input=arg1 --input=arg2 is important, I can add it. its not really hard, just worried if people will understand it.

I don't think it'll be a problem. In Bourne shell scripting, it's all space-delimited, so the meaning of `--input="$@"` is unclear (only the `"$@"` gets repeated) but, in `Makefile.toml`, the user specifies exactly where the argument boundaries lie and no additional splitting is used, which means that the most intuitive behaviour for `--input=${@}` is as a template that gets repeated for each argument.

As for its utility, there are various commands where something like `-i<path>` or `-f<path>` allows input or supplementary data to be loaded from file and it can be specified more than once. I've actually seen some where that's the *only* way to not read from stdin.

**Comment by ssokolow** [comment]
On that note, there's one other thing I'd like to suggest.

For `script` tasks, it'd be nice if there was a way to just pass `${@}` to the script via `argv`, rather than having to parse `CARGO_MAKE_TASK_ARGS` and hope that none of the arguments need to contain `;`.

Then it'd be possible to use `"$@"` in Bourne shell script tasks, `std::env::args_os` in `@rust` scripts, etc.

**Comment by sagiegurari** [comment]
--input=${@} and $@ for scripts are now also supported. you can checkout the same dev branch 0.12.
builds are failing due to travis or rust issue with beta but it should work fine for you.

**Comment by ssokolow** [comment]
`--input=${@}` and using `"$@"` in shell scripts both work well under the basic testing I put them through.

Was there a specific reason you chose to limit the `argv` pass-through to only shell scripts? (I also tested under `@rust` and `python` script runners.)

**Comment by sagiegurari** [comment]
didn't want to enable for runners that I cannot be 100% sure of their cli definition.
meaning, you can put there python/node/perl/whatever, and if any of them decide to accept cli args differently they would fail to work or if the cli args would conflict with what they use, they would also fail.
so decided to leave it out (for example I can't support php cli for now, but it wasn't important enough to handle specifically).
I think its good enough for now.

**Comment by ssokolow** [comment]
Fair enough in the case of arbitrary values, but `@rust` hardly seems arbitrary, given that:

1. It's a built-in special-case handler for cargo-script.
2. It seems like an excellent way to get portable task scripts when someone outgrows what your Bourne Shell to `cmd.exe` translator is capable of.

**Comment by sagiegurari** [comment]
yet to see that specific one in use in projects but I'll test it to see it will work well, if so will add official support.

**Comment by ssokolow** [comment]
I worry that might be a chicken-and-egg situation, but OK.

`@rust` seems like a good way to support both UNIX and windows for complex stuff like commands which need an explicit input and output filename for each thing processed, so you'd want to make two arguments from each argument provided, one of which strips the extension and then adds on a new one.

I know your script translator can't understand bash's `${X%.*}` construct for getting the contents of environment variable `X` up to just before the final period. (eg. if `$X` were `foo.bar.baz`, then `${X%.*}.zip` would be `foo.bar.zip`.)

**Comment by sagiegurari** [comment]
@rust now supported as well.

**Comment by ssokolow** [comment]
I'll have to test it tomorrow, but that's good to hear.

One situation I can imagine it being useful for is certain kinds of resource-building. 

For example, in one older project, I wrote a shell script which generates web-ready PNGs from SVG source files by the following process:

1. Use `${X%.*}.png` to generate a PNG filename for each input SVG (Using Inkscape's `--export-png` in this case, but every SVG renderer I've used has required manually-specified output filenames)
2. Optionally call [svgo](https://github.com/svg/svgo) if serving an SVG variant is desired.
3. Call [OptiPNG](http://optipng.sourceforge.net/) to optimize the PNG pre-compression (it's the best open-source one)
4. Call [AdvanceCOMP](http://www.advancemame.it/comp-readme) to optimize the DEFLATE compression (best open-source one before [zopflipng](https://github.com/google/zopfli) came around)
5. Use [pngcrush](https://pmt.sourceforge.io/pngcrush/) to strip unwanted ancillary chunks (pngcrush annoyingly lacks a "modify in place" option so I have to do some renaming and/or deleting to get the desired output filename.)

As you might guess, even with Inkscape, `optipng.exe`, `advpng.exe`, and `pngcrush.exe` on the `PATH`, that isn't usable on Windows because it's written in shell script.

I've also done something similar in a Python project where I combined AdvanceCOMP and [UPX](https://upx.github.io/) to crunch down [py2exe](http://py2exe.org/) output and, to simplify making it work on Windows, I just included `upx.exe` and `advzip.exe` in the repository. (In that case, I used Python like the rest of the project. If I were doing some kind of similar post-build processing for a Rust project, I'd want to do it in Rust.)

**Comment by ssokolow** [comment]
I just tested it and it looks good. :)

**Comment by sagiegurari** [comment]
closing as it is now officially released.
