### ISSUE TITLE
Option to clear / remove any default behavior

### ISSUE THREAD

**Issue by topaxi** [sagiegurari/cargo-make#1010]
## Motivation

I tried to setup a simple workflow of building some packages within my workspace, but cargo-make gets in the way every step I take.

Even though I read through the whole documentation, have overwritten the default workflow, disabled some default tasks like `[task.test]` etc. as I define them very differently in some crates.

I start to wonder whether I should move into a simpler system like "old-school" `make` or a simple script, potentially losing some nice benefits like caching and properly resolving dependencies automatically.

I, and probably some other developers too, prefer the mindset of "explicit is better than implicit", so maybe this is also the wrong tool for me then :thinking:  

Although I really like the configuration setup and everything, as from a first glance it looks very clear and concise.

### Describe The Solution You'd Like

Provide an option that disables / clears all predefined tasks and let's us define our own default task from scratch.

### Code Sample

```toml
[tasks]
no_defaults = true
```

**Comment by sagiegurari** [comment]
1. removing ALL default tasks

https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#disabling-predefined-tasksflows

```toml
[config]
skip_core_tasks = true
```

2. removing task level parent definition (not really needed if you did item 1)

https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#extending-tasks

```toml
[tasks.whatever]
clear = true
```

this is actually like your no_defaults i guess
also if you are in a workspace, make sure you have Makefile.toml in each crate with following:

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

see more at: 
https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#usage-workspace-extend

**Comment by topaxi** [comment]
Somehow missed this, thanks :partying_face: :bow: :heart:

**Comment by sagiegurari** [comment]
not sure you need the config if you have the env part in the crates and younhave workspace level Toml that has the config.... but ok

**Comment by topaxi** [comment]
Workspace level config alone didn't do the trick, but maybe I did something wrong :thinking: 

For now I'm happy, I might circle back to check whether there's a more optimal/concise solution :)
