### ISSUE TITLE
`#!@rust` `load_script` fails to execute

### ISSUE THREAD

**Issue by wmmc88** [sagiegurari/cargo-make#1035]
### Describe The Bug

I am unsure if this is a new problem or recent issue, but I'm finding that using `#!@rust` in a `load_script` causes an error. I think this used to work and something might have broken it, but im not 100% sure.

### To Reproduce

```.toml
[config]
load_script = '''
#!@rust

'''
```

### Error Stack

With RUST_BACKTRACE="full":
```console
cargo make
[cargo-make] INFO - cargo make 0.37.8
thread 'main' panicked at D:\.tools\.cargo\registry\src\index.crates.io-6f17d22bba15001f\envmnt-0.10.4\src\environment.rs:53:19:
called `Result::unwrap()` on an `Err` value: NotPresent
stack backtrace:
   0:     0x7ff663dd6453 - <unknown>
   1:     0x7ff663dff2fb - <unknown>
   2:     0x7ff663dd0993 - <unknown>
   3:     0x7ff663dd625e - <unknown>
   4:     0x7ff663dd8b17 - <unknown>
   5:     0x7ff663dd87b9 - <unknown>
   6:     0x7ff663dd903b - <unknown>
   7:     0x7ff663dd8f05 - <unknown>
   8:     0x7ff663dd6d49 - <unknown>
   9:     0x7ff663dd8c13 - <unknown>
  10:     0x7ff663e3c0a6 - <unknown>
  11:     0x7ff663e3c655 - <unknown>
  12:     0x7ff66368cd79 - <unknown>
  13:     0x7ff6637b253f - <unknown>
  14:     0x7ff66364a5d6 - <unknown>
  15:     0x7ff663650c10 - <unknown>
  16:     0x7ff66365164c - <unknown>
  17:     0x7ff6636c7e74 - <unknown>
  18:     0x7ff6636110e8 - <unknown>
  19:     0x7ff663611006 - <unknown>
  20:     0x7ff66361107c - <unknown>
  21:     0x7ff663dc9af0 - <unknown>
  22:     0x7ff663611048 - <unknown>
  23:     0x7ff663e1c070 - <unknown>
  24:     0x7ffb74b9257d - BaseThreadInitThunk
  25:     0x7ffb7592aa58 - RtlUserThreadStart
  ```

**Comment by wmmc88** [comment]
It looks like its due to `CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY` missing from the environment when the `load_script` is executing. Setting `CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY` to some random value causes the script to run successfully. Is this possibly a regression introduced by the commit fixing #968: https://github.com/sagiegurari/cargo-make/commit/b8e312dfeb4e956ec200299f9df86987716ffb7f

**Comment by wmmc88** [comment]
confirmed this example worked in `0.37.2`, but fails with `0.37.3`

**Comment by sagiegurari** [comment]
@wmmc88 will have a fix for that today probably
