### ISSUE TITLE
Support searching ancestor directories for Makefile.toml

### ISSUE THREAD

**Issue by ssokolow** [sagiegurari/cargo-make#104]
# Description

[just](https://github.com/casey/just) has a useful little feature where, like `cargo`'s built-in subcommands and `git` with the `.git` directory, it will walk up the filesystem looking for a `justfile` if it doesn't find `justfile` in the current directory.

This makes `just foo` from inside `src/mymodule/` equivalent to `pushd ../..; just foo; popd`, which is convenient for the same reasons `git` supports it.

I'd like to suggest that cargo-make do the same.

(Just also supports `just src/proj/taskname` as a shorthand for `pushd src/proj; just taskname; popd`, but that's a more advanced feature.)

# Example

From inside `src/mymodule`:
* `git st` --> Success
* `cargo build` --> Success
* `just taskname` --> Success
* `cargo make taskname` --> `Task not found: taskname`

**Comment by sagiegurari** [comment]
try looking at search_project_root in the global configuration section.
by default its disabled but it might be what you are looking for

**Comment by ssokolow** [comment]
Yeah, that did it. I'm honestly not sure how I missed that one.

**Comment by ssokolow** [comment]
I should have noticed that there was a global configuration section though.

Maybe my eyes just glazed over because of all the time I spent scanning the rest for want of a more concise summary of certain parts. (I'd offer to contribute one, but I'm too busy to be able to keep any such promise I'd make.)
