### ISSUE TITLE
docker command not found under windows

### ISSUE THREAD

**Issue by Matrix-Zhang** [sagiegurari/cargo-make#1097]
in duckscript runner, i execute docker command,  the duckscript can not find the docker command, the PATH is empty, but get_env PATH is have full things

```
 Error while running duckscript: Source: Unknown Line: 6 - Command: docker not found.
```

**Comment by sagiegurari** [comment]
can you explain path empty but getenv for path is not?
can you print it?

**Comment by Matrix-Zhang** [comment]
> can you explain path empty but getenv for path is not? can you print it?
```
echo ${PATH} //this is print nothing
path = get_env PATH
echo ${path} //will print system $PATH
docker ps -a // docker command not found
```

**Comment by Matrix-Zhang** [comment]
ok, should use exec docker
