### ISSUE TITLE
`watch` fails on Windows

### ISSUE THREAD

**Issue by pepperoni505** [sagiegurari/cargo-make#1099]
### Describe The Bug
Adding `watch` to a task causes the task to fail. There is an [issue](https://github.com/watchexec/cargo-watch/issues/304) on the `cargo-watch` repo that mentions a solution to this, which is to install with the `--locked` flag. Per the documentation, I have tried adding `CARGO_MAKE_CRATE_INSTALLATION_LOCKED = "true"` to my `env` section but that didn't seem to get it to add the locked flag

### To Reproduce
Use the `Makefile.toml` sample provided below

### Error Stack

```console
error[E0308]: mismatched types
   --> C:\Users\jack\.cargo\registry\src\index.crates.io-6f17d22bba15001f\notify-4.0.17\src\windows.rs:276:29
    |
276 |         overlapped.hEvent = request_p;
    |         -----------------   ^^^^^^^^^ expected `winapi::ctypes::c_void`, found `libc::c_void`
    |         |
    |         expected due to the type of this binding
    |
    = note: `libc::c_void` and `winapi::ctypes::c_void` have similar names, but are actually distinct types
```

### Code Sample

```toml
[tasks.sample_task]
script_runner = "@duckscript"
script = '''
from = get_env PACKAGE_DIR
to = get_env OUTPUT_DIR
glob_cp ${from}/**/* ${to}
'''
watch = { watch = ["$PACKAGE_DIR"] }
private = true
```

**Comment by sagiegurari** [comment]
ok so to solve that using the locked workaround, need to change the runner.rs which installs cargo watch in the first place.
dependencies :(
a workaround is that you install cargo watch yourself and than cargo-make will use that installation automatically (should work)

**Comment by pepperoni505** [comment]
That worked. Thank you!
