### ISSUE TITLE
List available tasks

### ISSUE THREAD

**Issue by joao-conde** [sagiegurari/cargo-make#1104]
### Feature Description

A command to list the available tasks. Both default and user defined.

### Describe The Solution You'd Like

`cargo make tasks` -> prints out list of user defined tasks
`cargo make tasks --all` -> prints out list of user defined tasks and default cargo make ones

### Notes

I failed to encounter this in the docs. If this exists, and is not documented, this issue should be about documenting.

**Comment by sagiegurari** [comment]
there is already a function that exists to show all tasks. there is no concept of user defined as makefiles extend each other but ther eis also a command to filter by type/group.
the commands also provide multiple output formats.

checkout
https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#usage-cli

--list-all-steps Lists all known steps --list-category-steps <CATEGORY>

**Comment by joao-conde** [comment]
Thank you and sorry!
