### ISSUE TITLE
tasks.do-copy-apidocs does not work for workspace

### ISSUE THREAD

**Issue by chuckliu1979** [sagiegurari/cargo-make#1113]
### Describe The Bug
If the project layout is workspace, the doc generated under <workspace-root>/target/doc/, not under crate, hence the do-copy-apidocs not copy docs

According to https://doc.rust-lang.org/cargo/reference/workspaces.html:
```
All packages share a common [output directory](https://doc.rust-lang.org/cargo/guide/build-cache.html), which defaults to a directory named target in the workspace root.
```

### To Reproduce
in workspace root, run:

cargo make docs-flow

docs/api/<crate> has nothing

**Comment by sagiegurari** [comment]
i have a workspace project as well  (duckscript) that seems to work well. not sure about the difference here but maybe because it might be middle of flow?

**Comment by sagiegurari** [comment]
ok i think i get the confusion. this task was originally written as part of the docs-flow and was used for crate level.
i than modified it to support workspace level stuff and ya this task in the flow doesn't really do much as you stated.
the docs-flow however, enables you to plug into this flow and create custom steps for example in duckscript i create api docs for all commands and in cargo-make i create a list of all known tasks.

closing it for now as it doesn't bother anything but feel free to reopen if you need something solved.
