### ISSUE TITLE
Cant't seem to get anything to work when using some sort of shared folder

### ISSUE THREAD

**Issue by kedom1337** [sagiegurari/cargo-make#1128]
### Describe The Bug
I have a linux host machine on which I develop. I have a windows virtual machine on which I want to build the project due to it being a windows driver. My plan was to create a shared folder containing the project to be able to build the project from the windows virtual machine. This sadly does not work however much I try it. At first I used a virtiofs filesystem with WinFSP. Even though I configured it properly according to [this](https://github.com/virtio-win/kvm-guest-drivers-windows/issues/517) issue it did not work and gave me the following error:

```txt
[cargo-make] INFO - Execute Command: "rust-script" "target\\_cargo_make_temp\\persisted_scripts\\D4060E7434B3779E78A683E8BA00D06A5D08BE8C95BC432359E22F06CB30EF1C.rs"
Error: IoError(Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." })
[cargo-make] VERBOSE - Output: Ok(
    Output {
        status: ExitStatus(
            ExitStatus(
                1,
            ),
        ),
        stdout: "",
        stderr: "",
    },
)
[cargo-make] VERBOSE - Executed rust code, exit code: 1
[cargo-make] ERROR - Unable to execute rust code.
[cargo-make] WARN - Build Failed.
```

Then I thought "No problem let's just try good ol trusted SAMBA". Yet fate again was not nice to me. I got a new error but that hardly made this less frustrating:

```txt
[cargo-make] INFO - Execute Command: "rust-script" "target\\_cargo_make_temp\\persisted_scripts\\D4060E7434B3779E78A683E8BA00D06A5D08BE8C95BC432359E22F06CB30EF1C.rs"
Error: IoError(Os { code: 4390, kind: Uncategorized, message: "The file or directory is not a reparse point." })
[cargo-make] VERBOSE - Output: Ok(
    Output {
        status: ExitStatus(
            ExitStatus(
                1,
            ),
        ),
        stdout: "",
        stderr: "",
    },
)
[cargo-make] VERBOSE - Executed rust code, exit code: 1
[cargo-make] ERROR - Unable to execute rust code.
[cargo-make] WARN - Build Failed.
```

My project is exactly what is described [here](https://github.com/microsoft/windows-drivers-rs). As soon as I copy the project from the shared folder to any location on disk like the desktop the build works as expected.

### To Reproduce
Setup a windows virtual machine on a linux host. Follow the steps described [here](https://github.com/microsoft/windows-drivers-rs) to set up a driver project. And the simply try to build the project with `cargo make`. 

### Error Stack

As described above

### Code Sample

/

**Comment by sagiegurari** [comment]
@kedom1337 thanks for notifying me.
i have to admit i'll probably not setup a windows vm like you did as i'm running on a weak arm machine so will need your help here.
the flow to run a script is 
1. create a temp file
2. add some pre script content (like cd back to original location) - not relevant for your rust usecase
3. add user content
4. run it

for rust scripts, i run it by using the rust-script crate and you can see the actual command i'm running.
so error i feel is originating from that crate. 

my suggestion is to create a simple test case without cargo make
1. create a rust file with your code
2. run it as i did 
3. see error

and open an issue for that crate with link to this one.
wdyt?

**Comment by sagiegurari** [comment]
thanks for verifying. i'll close it for now and feel free to reopen if needed
