### ISSUE TITLE
Allow setting default install_crate to false

### ISSUE THREAD

**Issue by FlixCoder** [sagiegurari/cargo-make#1147]
### Feature Description
For disabling workspace execution of all tasks there is `default_to_workspace = false` in the `[config]` section. However, there is no way to default to NOT installing crates like `default_install_crate = false` or something, as far as I can see. So I would like to have such a config option to disable it by default and only activate it when it makes sense.

### Describe The Solution You'd Like
```toml
[config]
default_install_crate = false
```
This will set the default value for the install_crate variable for all tasks. Not sure if it makes semantic sense. Maybe it would also be something like `default_disable_install = true`, so that one cannot do `default_install_crate = { rustup_component_name = "whatever" }`.

**Comment by sagiegurari** [comment]
@FlixCoder trying to understand the ask here.
if the following is defined:

```toml
[config]
default_install_crate = false
```

when will installation happen? only if rustup/crate values are defined in the install_crate param or even than to disable it? 
if its disabled in the above, how to reenable it?

**Comment by FlixCoder** [comment]
Yeah I had imagined, that you would re-enable it through setting some value in `install_crate`, not sure if that makes sense though.

My concern is only, that it would be possible to disable automatic installation without specifying `install_crate = false` everywhere, as I want to be notified if I failed to install the requirements before and in CI I don't really want to compile the dependencies myself :D

So if that is somehow possible, I honestly don't really mind how it works.

**Comment by sagiegurari** [comment]
so maybe not disable default but actual disable.
that you just can't re-enable and flow will fail unless you install stuff on your own. makes sense?

**Comment by FlixCoder** [comment]
That would work, yes. But I assume it would also be useful to be able to reenable it for some task later.
Although it is always possible to install yourself via a conditional task.

**Comment by sagiegurari** [comment]
done and released
