### ISSUE TITLE
Find the next `Makefile.toml` up the project tree

### ISSUE THREAD

**Issue by FlixCoder** [sagiegurari/cargo-make#1148]
Hi, first of all thank you for the great tool!

### Feature Description

I would like to replace my `xtask` pattern with `cargo-make`, as it is easier to re-use and type commands with simple and quick definitions. `cargo xtask` was working via a custom cargo alias, which runs a specific `xtask` crate in the workspace. This means, cargo will find it from anywhere in the workspace and execute it wherever I want. It will always be executed on the workspace folder per my configuration.

I have only globally defined tasks, as that makes more sense for the "pipeline". I want to run all crate's tests at once via nextest and do some workspace-global tasks beforehand. I don't really have anything crate-specific, so I disabled workspaces via `default_to_workspace = false`.
I have also set `CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true` in the env section, in case that does anything.

Now what happens is, that I cannot run `cargo make` in a subdirectory, not even member crates of the workspace, as they will not find the defined tasks in my workspace-level Makefile.

### Describe The Solution You'd Like

So I would like to have some kind of way, to make this find the workspace Makefile from any sub-folder and run it in the workspace-root as current working directory. Is this something that is possible and makes sense for you in this project?

I would imagine a flow like this:
1. Check current directory for Makefile. If there is one, do whatever you do normally.
2. Go folders up until you find a Makefile definition. Run as if you were called in that folder, i.e. still doing inheritance like normally, with possibly more Makefiles further up. But run in that folder as current working directory.

**Comment by sagiegurari** [comment]
@FlixCoder sorry for late reply.

there are already 2 ways of doing this

1. machine level configuration
https://github.com/sagiegurari/cargo-make#cargo-make-global-config
```
search_project_root = true
```
2. create a 1 liner makefile in each crate and extend manually the workspace level makefile
https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#extending-external-makefiles
```toml
extend = "../Makefile.toml"
```

would any of those work for you?

**Comment by FlixCoder** [comment]
Ah, I didn't know about the global setting, sorry. That helps, thanks!

Though I do need both of your suggestions to find the tasks. It works perfectly when in a non-crate sub-folder. In a sub-crate though, it will set the working directory to the sub-crate and not the workspace-root though.

But I am sure there might be workaround as well. Anyway this is now minor ergonomics at least, so feel free to close or keep open :) Thank you again!

**Comment by sagiegurari** [comment]
personally i'm not a fan of option 1 (although i did write it) because its machine specific and you move to a new machine, or a build machine or someone contributes and its not working as in your setup.

option 2 on its own should be bulletproof and recommended way.

**Comment by U007D** [comment]
I came here to ask about this.  I'm also considering migrating to `cargo-make` from an `xtask`-based workspace.

Option 1 doesn't work for other people's setups, as you point out, and option 2 puts overhead in every crate and folder in the workspace; replicating `cargo`'s pattern of searching the parent folder hierarchy would address both of the above issues and would be more consistent with Rust tooling.

Any possibility of re-opening this issue?
