### ISSUE TITLE
Environment vars not working on windows?

### ISSUE THREAD

**Issue by rokit** [sagiegurari/cargo-make#129]
#### Problem Description
I'm trying to echo the value of a variable, but it's not working.

#### Code Example

````rust
[env]
DEBUG_DLL_SOURCE = "%cd%\\target\\debug\\lib.dll"
DLL_DESTINATION = "%cd%\\resources\\"

[tasks.checkvar]
script = [
 "echo ${DEBUG_DLL_SOURCE}"
]
````

#### Error Stack/Info (if any)
This is the output of the command: `cargo make checkvar`:

E:\Code>echo ${DEBUG_DLL_SOURCE}
${DEBUG_DLL_SOURCE}
[cargo-make] INFO - Running Task: end
[cargo-make] INFO - Build Done  in 0 seconds.

This doesn't work either:
````rust
[tasks.checkvar]
env = { "SOME_ENV_VAR" = "value" }
script = [
 "echo ${SOME_ENV_VAR}"
]
````

I tried in both Cmd and PowerShell. Am I doing something wrong?

**Comment by rokit** [comment]
Ok, I know why. For windows, this:
`"echo ${SOME_ENV_VAR}"`
should be this:
`"echo %SOME_ENV_VAR%"`

**Comment by sagiegurari** [comment]
scripts by default use the system runners.
you could use ${} with ```@shell``` runner on all platforms

**Comment by sagiegurari** [comment]
if the env var is "resources/" it won't work? as far as i remember, "/" works ok with cp.
also you have a dll path there so not sure why that needs to support more than windows only, but generally speaking, / should be ok for cp command.

**Comment by rokit** [comment]
It doesn't work because `cp` resolves to `xcopy`, and `xcopy` doesn't like "/":
````
xcopy ./target/debug/lib.dll ./resources/
Invalid number of parameters
[cargo-make] ERROR - Error while executing command, exit code: 4
[cargo-make] WARN - Build Failed.
````
Yeah, I'm developing on Windows, but I'm always thinking about cross-platform. Anyway, it's no big deal. Guess it's not that hard to substitute the correct slash in a condition.
