### ISSUE TITLE
is it possible to set the toolchain version?

### ISSUE THREAD

**Issue by thedavidmeister** [sagiegurari/cargo-make#132]
#### Problem Description

I saw that it is possible to only run a task conditionally on the toolchain.

Is it possible to set/pin the toolchain? e.g. with an ENV or something?

**Comment by sagiegurari** [comment]
initial commit pushed to 0.15.2 to support toolchain selection in task level.
you can see the [draft docs](https://github.com/sagiegurari/cargo-make/tree/0.15.2#usage-toochain)

if you can give it a try and provide feedback, it would be really helpful.
right now toolchain support is only for command in crate/rustup component installations but not for scripts or install_scripts as I prefer people to use the more structure way to invoking rust related commands.

**Comment by thedavidmeister** [comment]
hi, i'm using nixos atm rather than cargo-make, but sounds good :D

**Comment by sagiegurari** [comment]
pushed to master and will be officially released today
