### ISSUE TITLE
is it possible to have fallbacks for conditional values?

### ISSUE THREAD

**Issue by thedavidmeister** [sagiegurari/cargo-make#133]
#### Problem Description

the condition "linux" is too loose, e.g. using nixos package manager instead of apt-get, or tweaking apt-get behaviour based on linux distribution

is it possible to chain conditions like if/elseif/elseif style to support more subtle variations in OS?

**Comment by sagiegurari** [comment]
@thedavidmeister take a look at #175 I think that will basically provide you the solution.
you can have a task which will route to other tasks based on conditions which would be env vars or platform and so on...

**Comment by sagiegurari** [comment]
0.16.2 released
