### ISSUE TITLE
Should abort on non existent --makefile

### ISSUE THREAD

**Issue by DianaNites** [sagiegurari/cargo-make#143]
#### Problem Description

I think cargo-make should abort if using CLI `--makefile <FILE>` and `<FILE>` doesn't actually exist. It's unexpected and unlikely correct that, when told explicitly to use a certain file, it executes the default predefined task in it's absence.

**Comment by sagiegurari** [comment]
ya makes sense

**Comment by sagiegurari** [comment]
@DianaNites this is now implemented in branch 0.16.0 so you can verify it as well.
once 0.16.0 development is done, it will be released to crates.io

**Comment by sagiegurari** [comment]
release as part of 0.16.0
