### ISSUE TITLE
fotmat.stable should invoke cargo fmt using default rustfmt

### ISSUE THREAD

**Issue by orenbenkiki** [sagiegurari/cargo-make#160]
Shouldn't `tasks.format-stable` be modified to invoke a simple `cargo fmt`, using the default `rustfmt`, now that it is stable at version 1.0.0 as part of the rust 2018 / 1.31.0 release? The current recipe fails since the `-write-mode` parameter is no longer recognized.

**Comment by sagiegurari** [comment]
true. in the past, they kept changing their cli and were not backward compatible (as you can see).
I'll update the makefile to resolve that.

**Comment by orenbenkiki** [comment]
That was fast! :-)

Yes, invoking rustfmt in CI builds and in general used to be a huge PITA due to the breaking API changes. Happily, these days are finally behind us. I'm going over my old crates and updating them to the new toolchain - e.g., adding `check-format` and `clippy` to `verify-project`. Speaking of which, I had to create the `clippy` task, it would be nice if it existed by default.

**Comment by orenbenkiki** [comment]
Ugh, I missed that. Thanks!

**Comment by sagiegurari** [comment]
release as part of 0.16.0
