### ISSUE TITLE
Rust 2018 - clippy/rustfmt are not preview

### ISSUE THREAD

**Issue by D4nte** [sagiegurari/cargo-make#162]
#### Problem Description

Clippy and rustfmt as now part of rust stable 2018-12-06 as `rusfmt` and `clippy` (and not `-preview`).

Hence, need to somehow update the default Make file to remove the `preview` keywords. Not sure how you want to handle that. Let me know, happy to help.

**Comment by sagiegurari** [comment]
rustfmt already handled as part of #160 in the 0.16.0 branch.
if you want to do a PR for clippy, that would be great.
look at rustfmt as an example. thanks

**Comment by sagiegurari** [comment]
@D4nte sorry it took so long. I removed the preview from the rustup component name for both rustfmt and clippy in the 0.16.0 branch.

**Comment by sagiegurari** [comment]
if you look at the [commit](https://github.com/sagiegurari/cargo-make/commit/cbcb2035e9dceef10593dc4971997de281573bf1) you can see

* rustup component name changed from rustfmt-preview to rustfmt (same for clippy)
* crate name didn't change and is still rustfmt-nightly which is what they have in the Cargo.toml

Will rustfmt-nightly work in rust nightly? probably not... but the default behaviour is first to use the rustup component and there is no crate for rustfmt for stable that I can install.
I know for arm, there is no rustup component available, so if you are on arm and stable, you would probably not have rustfmt at all.

**Comment by D4nte** [comment]
I have not yet played around with your changes so these are just assumptions. I'll play around with a fresh install once `0.16.0` is released and let you know/propose changes if I encounter issues :)

**Comment by sagiegurari** [comment]
release as part of 0.16.0, if there are any issues please reopen.
