### ISSUE TITLE
Building cargo on subdirectory

### ISSUE THREAD

**Issue by Swoorup** [sagiegurari/cargo-make#167]
I have a folder with bunch of projects in different languages (js and rust)

How do you build a cargo project on a subdirectory?

**Comment by sagiegurari** [comment]
if you are in the sub directory and invoke cargo-make, by default it will work on that directory.
you can put a Makefile.toml there for sub folder specific tasks.

if you want to run it in parent directory and than for it to run some build tasks in each sub folder, you will have to define that projects as a workspace.

**Comment by sagiegurari** [comment]
yes, but instead of cd, write cwd.
its in the docs.
another way is to pass --cwd on the command line and have a makefile there which extends the makefile in the root dir.

**Comment by sagiegurari** [comment]
closing this. if there are more questions feel free to open a new issue
