### ISSUE TITLE
Any way to ignore paths with watch mode?

### ISSUE THREAD

**Issue by thedodd** [sagiegurari/cargo-make#188]
#### Problem Description
cargo-watch has the capability to pass ignore paths as such:
`-i, --ignore <pattern>...    Ignore a glob/gitignore-style pattern`

Is this currently supported in any way with tasks in watch mode? I've been looking through the docs, examples, issues & haven't seen anything to indicate this, but it is possible that I've missed something.

Thanks for the excellent work on this project so far!

**Comment by sagiegurari** [comment]
right now, there is no way, but will have it for next minor release.
i'll modify watch attribute to either be true/false as today or an object for more fine tuning capability

**Comment by sagiegurari** [comment]
@thedodd I just pushed it to the 0.16.8 dev branch so you can test it directly from there (docs updated as well on that branch).
I'll probably publish 0.16.8 very soon

**Comment by sagiegurari** [comment]
@thedodd this is implemented and published as part of 0.16.8 so i'm closing this.
if there is any issue with the implementation please reopen.
thanks for the idea
