### ISSUE TITLE
allow environment variable to refer to each other

### ISSUE THREAD

**Issue by sehyoc** [sagiegurari/cargo-make#20]
#### Problem Description

Please allow environment variable to be computed from other variable.  I can sort of do it in the task but then I have to declare unnecessary dependency.

#### Code Example

````rust
[env]
MAKE = "ford"
YEAR = "2014"
MODEL = "${MAKE} ${YEAR}
````

#### Error Stack/Info (if any)

Current MODEL is set to be empty.

**Comment by sagiegurari** [comment]
Makes sense.

**Comment by sagiegurari** [comment]
implemented. will push it once all milestone issues are implemented.

**Comment by sagiegurari** [comment]
new 0.5.3 version released
