### ISSUE TITLE
add kcov version validation

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#203]
**Describe the bug**
base on #201 If kcov 33 is already installed, cargo-make will not reinstall kcov.
however 33 doesn't support few features that are needed.
So need to add version validation as well.

**Comment by ssokolow** [comment]
I haven't let the task go all the way yet, but attempting to run `makers coverage-kcov` with my current kcov 33 does now display a `sudo` prompt rather than failing with an error.

**Comment by sagiegurari** [comment]
which means it works as it should.
cargo make will attempt to install anything that is missing and in kcov case also if it sees that it doesn't support the needed features.
when installing kcov i need sudo permission which is the prompt you got.
once you put in the password, it will install kcov and invoke it.
next run, it will just work.

if it would fail with an error, it means you need to manually repair kcov which is not what i want.

**Comment by ssokolow** [comment]
Yeah. What I meant to communicate was "The version check is working as intended, but I won't know if the whole installation process completes successfully until tomorrow, when I audit the contents of the task before giving it my password."
