### ISSUE TITLE
New trim function

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#208]

**Comment by ssokolow** [comment]
I can guess at what the trim function does, but how is it used?

**Comment by sagiegurari** [comment]
i have an example in the docs already:
https://github.com/sagiegurari/cargo-make/tree/0.17.0#usage-functions-trim

**Comment by ssokolow** [comment]
This is very awkwardly written:

> And returns either an empty array in case the environment variable is not defined or after it is trimmed, it is empty or it returns the actual environment variable value.

I'd suggest this instead:

> And returns either the contents of the variable with leading and trailing whitespace removed, or an empty array if the variable is not defined or contains only whitespace.
