### ISSUE TITLE
option to set directory

### ISSUE THREAD

**Issue by sehyoc** [sagiegurari/cargo-make#21]
#### Problem Description

I would like to set directory before running task.  For example, if I have sub directory in the project, I want to use that as directory for my task.   The directory should be relative directory from project.
Fore example, if I have subdirectory "sub1", then

#### Code Example

````rust
[tasks.do_something]
cd = "sub1"
script = [
  "ls"
]
````

#### Error Stack/Info (if any)
This should cd to sub1 in the my project and run "ls".

**Comment by sagiegurari** [comment]
1. You can change cwd as part of the cli. Or you need it per task?
2. You can do it as part of the script itself
3. This is the real question: do we revert back after task ends? How it impacts sub tasks and dependencies? What if a dependency already ran not part of this task so it wont run again? I guess to be as clear as possible this directory should only impact this specific task action and no other task (not dependencies and not sub tasks called via run_task)

What do you think?

**Comment by sehyoc** [comment]
For my need, I just need for this task.  I can do this as part of script but is bit of clumsy to do multi-line in TOML file.

**Comment by sagiegurari** [comment]
this doesn't look clumsy to me, but anyway i'll implement

````toml
script = [
'''
cd mydir
ls
'''
]
````

**Comment by sagiegurari** [comment]
done. I'll be releasing it soon.

**Comment by sagiegurari** [comment]
new 0.5.3 version released
