### ISSUE TITLE
cargo-script seemingly unmaintained

### ISSUE THREAD

**Issue by leo60228** [sagiegurari/cargo-make#216]
**Features Description**
The maintainer of [cargo-script](https://github.com/DanielKeep/cargo-script) doesn't have any public commits since November 2017, and one commit on his profile in August 2018.

**Describe the solution you'd like**
Either forking it or embedding similar logic in cargo-make itself would be helpful.

**Code Sample**
https://github.com/sagiegurari/cargo-make/blob/0a9a7f4c0ce166d044b50daf44c31b0e42947b55/src/lib/scriptengine/rsscript.rs#L17

**Comment by sagiegurari** [comment]
are there any issues with cargo script that requires fixing?

**Comment by leo60228** [comment]
It has a C dependency that's annoying on Windows.

**Comment by sagiegurari** [comment]
@leo60228 took a look at it and I agree that it's outdated and got problematic dependencies.
cargo-make doesn't link to it and it can be replaced fairly easily.
The only issue however, is finding a good alternative.
if you have a suggestion, please let me know.
If not, i'm going to keep this open until there is a good alternative.

personally, i'm not going to fork and take over cargo-script

**Comment by sagiegurari** [comment]
@leo60228 [cargo-play](https://github.com/fanzeyi/cargo-play) seems to provide similar features.
do you think it would be a good alternative to use? can't really test on windows to say for myself.

**Comment by leo60228** [comment]
I think it looks good.

**Comment by sagiegurari** [comment]
@leo60228 support for cargo-play has been pushed to 0.22.0 development branch.
You can look at the [docs](https://github.com/sagiegurari/cargo-make/tree/0.22.0#usage-task-command-script-task-examplerust) on how to control which crate is being used (cargo-script is still the default unless configured differently).
if you can try it out, it would really help. especially since i don't have windows machine to test.

**Comment by leo60228** [comment]
I don't either, but I know @roblabla was looking at this a while ago.

**Comment by sagiegurari** [comment]
@leo60228  @roblabla cargo make 0.22.0 has now been published with cargo-play support
