### ISSUE TITLE
set environment variable based on script evaluation

### ISSUE THREAD

**Issue by sehyoc** [sagiegurari/cargo-make#22]
#### Problem Description

I need to set environment variable based on result of the script.  This variable will be feed to another task.   This is blocker for me to use this tool.  Something like this will be good way to configure env variable.

#### Code Example

````rust
[env]
name = "count"
description = "count of file"
script = "wc file.txt"

[task.echo]
script = ["echo ${count}]
````

**Comment by sagiegurari** [comment]
Nice feature.

**Comment by sehyoc** [comment]
This is show stopper.   I have to go back to Makefile or alternative solutions without this feature.

**Comment by sagiegurari** [comment]
alrealy assigned it to me. I'll handle it

**Comment by sagiegurari** [comment]
pushed this to the 0.5.3 branch. once I finish the other 2 items i'll publish a new release.

**Comment by sehyoc** [comment]
Nice work.   Thanks!

**Comment by sagiegurari** [comment]
new 0.5.3 version released
