### ISSUE TITLE
Split Makefile.stable.toml

### ISSUE THREAD

**Issue by orenbenkiki** [sagiegurari/cargo-make#225]
**Workflow documentation**

The predefined `*-flow` tasks are meant to be used in the context of a certain development work flow. Sometimes this is clear (e.g., `ci-flow` to be used in a CI server), sometimes less so (when is `coverage-flow` supposed to be used?).

I think it would be very useful for `cargo make` newbies if there was a clear documentation of this development work flow - that is, when each task flow is supposed to be used and for what purpose.

**Custom workflows**

While having a default development work flow is great and ensures `cargo make` is useful out of the box, this work flow is not universal.

For example, in my personal workflow, I would expect to have a `pc` (pre-commit) flow (similar to `build`) and a `ci` workflow which is almost identical. In fact `pc` would just invoke `clean` and `pc-correct` (to invoke `rustfmt` to fix source formatting, or any other tool that may modify the source files), and then invoke `ci` (which would in turn invoke `test` and `verify`). The `test` would build and run the tests (always collecting coverage information), and `verify` would run `clippy` and `rustfmt --check` (and any additional custom static verification tools which only examine the source files).

This is similar to the existing flows, but sufficiently different that expressing it as a delta is about as much work (and much less clear) than just defining the new flows.

I suggest it would be beneficial to split `Makefile.stable.toml` into two files: `Makefile.steps.toml` and `Makefile.flows.toml`. The first would only contain tasks that perform a basic step (running `rustc`, running `rustfmt`, running tests, etc.). The second would contain the default flows.

In addition, it should be possible to specify in the `Makefile.toml` whether one wants to use the default flows. If not, then a `config` statement should be used to import a different set of flows. 

Exact syntax is TBD. The simplest way would be to say something like `CARGO_MAKE_NO_DEFAULT_FLOWS = 1` in the `config` section.

**Comment by sagiegurari** [comment]
You raise good points, I'll try to explain how I see it and give you possible solutions using existing capabilities.
and if afterwards you would feel that some change is still needed, lets discuss how/if to implement.

flows - you are right, some are probably not that obvious on what they are doing. coverage-flow?
but flows are just a group of tasks being invoked 1 after the other and not necessarily mean that they are supposed to be public and used by people directly. maybe those flows are sub flows of bigger thing.
so coverage flow is a sub flow of the ci flow and it checks which coverage provider to invoke and runs it (by the way i used it today directly :smiley:)
I auto generate all tasks (including flows) documentation and push it to the readme so its semi-documented. agree that its not good enough, that is why i have sections with manual explanation which are more deep on some major stuff but not all (to prevent information overload).

as for your custom flows use case, you have some possibilities to write custom flows that use core tasks.

1. use your flow names - easy. just write flow named "pc" which calls any custom or core task. that won't do any conflicts with core flows.
2. reuse core flow names - if your flow is really different (conditions, description, so on...) you can add the [clear attribute](https://github.com/sagiegurari/cargo-make#default-tasks-and-extending) and you can reuse the core flow name but your custom content only without extending any core attribute.
3. rename all core tasks and flows and write custom flows that reuse renamed core tasks - that's fairly new capability, see [docs](https://github.com/sagiegurari/cargo-make#usage-predefined-flows-modify) which enable you to rename all core tasks, then you can have your own "ci-flow" which can call core tasks using the ```<namespace>::<name>``` naming convention.
4. using pre/post hooks - i have many flows that call core empty tasks that are named pre-flow and post-flow (for example "format-flow" flow calls "pre-format", "format", "post-format"). this is there to enable customizing the flow without touching it by implementing those pre/post tasks and running some custom stuff.
for example after the formatting run some code generation tool (bad example... by you get it).

do these provide good solution for you? or do you think there is still an issue here and we need some change?

**Comment by orenbenkiki** [comment]
As for documentation: A flat list of flows isn't that helpful. But arranging them in a tree (well, actually a DAG) would be very helpful. This can be done manually, but how about automatically generating this hierarchy, or even a `dot` diagram based on the relationship between the tasks?

Such a hierarchical list would be helpful in understanding what calls what. Presumably the roots will be meant to be invoked directly while the sub-tasks only be explicitly invoked in special cases. It might be also be helpful to add a hint about the expected context in the descriptions, but just having this tree or DAG visible should probably already provide 80% of the solution.

As for the custom flows: Ah, `cargo make` got some new and improved features since I last thoroughly read the docs.

It seems that if I do:
```toml
[config.modify_core_tasks]
private = true
namespace = "default"
```

Then all the default flows and tasks would be (1) renamed to `core::whatever` and (2) will not be listed by `-list-all-steps`. Nice!

I could then add my own flows reusing whatever I want from the default namespace, either by invoking `default::something` as a sub-flows or by directly extending it. This seems to address the core of my suggestion within the current capabilities.

Thanks!

**Comment by sagiegurari** [comment]
docs - i'll think of something. its not trivial as some task are really useful as top level as well and some flows are also top level and sub flows of other flows. its its kinda never ending. i'll open a new task to think about how to make it more clear.

really liked scmf. looks good.
