### ISSUE TITLE
More relaxed CARGO_MAKE_TEST_COVERAGE_DEFAULT_BINARY_FILTER 

### ISSUE THREAD

**Issue by orenbenkiki** [sagiegurari/cargo-make#230]
Currently:

```
CARGO_MAKE_TEST_COVERAGE_DEFAULT_BINARY_FILTER = "${CARGO_MAKE_CRATE_FS_NAME}-[a-z0-9]*$\\|test_[a-z0-9]*-[a-z0-9]*$\\|[a-z0-9]*_test-[a-z0-9]*$"
```

This does not capture my `test_union_find.rs` tests, because of the regexps `test_[a-z0-9]*`. Given Rust naming convention, it is reasonable to restrict test file names, to avoid capital letters and Unicode insanity. However, there's no good reason to avoid `_`:

```
CARGO_MAKE_TEST_COVERAGE_DEFAULT_BINARY_FILTER = "${CARGO_MAKE_CRATE_FS_NAME}-[a-z0-9]*$\\|test_[_a-z0-9]*-[a-z0-9]*$\\|[a-z0-9]*_test-[_a-z0-9]*$"
```

**Comment by sagiegurari** [comment]
makes sense. will check it.

**Comment by sagiegurari** [comment]
@orenbenkiki update pushed to development branch.

**Comment by orenbenkiki** [comment]
Thanks!
