### ISSUE TITLE
Can't customize task in a namespace.

### ISSUE THREAD

**Issue by orenbenkiki** [sagiegurari/cargo-make#235]
Suppose that `Makefile.stable.toml` has task `tasks.coverage-kcov` containing:
```
[tasks.coverage-kcov]
...
env = { "CARGO_MAKE_KCOV_INCLUDE_PATTERN" = "${CARGO_MAKE_WORKING_DIRECTORY}/src/" }
...
```

And further suppose this is _indirectly_ invoked from my `Makefile.toml` using a namespace:
```
[config.modify-core-tasks]
private = true
namespace = "default"

[tasks.coverage]
private = false
extend = "default::coverage"
...
```
Where the default `tasks.coverage` invokes `tasks.coverage-kcov`.

And further suppose I want to override the environment variable in my `Makefile.toml`:
```
[default::tasks.coverage-kcov]
env = { "CARGO_MAKE_KCOV_INCLUDE_PATTERN" = "${CARGO_MAKE_WORKING_DIRECTORY}/src/,${CARGO_MAKE_WORKING_DIRECTORY}/tests/" }
```

Then this fails, because TOML does not accept colons in section names (`Unable to parse external description, expected a right bracket, found a colon at ...`).

I'm not aware of current possible workarounds (are there any?).

A possible fix would be to allow an alternative syntax for namespaces in the TOML file, e.g. `[default..tasks.coverage-kcov]`.
A very disruptive fix would be to use `..` instead of `::` as the namespace separator everywhere.
A middle ground would be to allow `..` to be used everywhere for consistency, but also allow `::` for backward compatibility.

**Comment by sagiegurari** [comment]
you need to add "

**Comment by orenbenkiki** [comment]
My bad for not further investigating the TOML format...

It is true that writing:
```
["default::tasks.coverage-kcov"]
env = { "CARGO_MAKE_KCOV_INCLUDE_PATTERN" = "${CARGO_MAKE_WORKING_DIRECTORY}/src/,${CARGO_MAKE_WORKING_DIRECTORY}/tests/" }
```
Satisfies the TOML parser.

However, it doesn't actually override the environment variable (that is, the original value is still used). Using verbose output I see that the override is not mentioned anywhere - as if I didn't specify it at all.

Specifically, if I `diff` the results of the `--verbose` runs with and without the above override, I get exactly the same output (up to the order of running parallel threads and the time-to-execute report lines).

**Comment by sagiegurari** [comment]
it should be:
[tasks."default::tasks.coverage-kcov""]

The tasks prefix is still needed.

**Comment by orenbenkiki** [comment]
Actually, it seems it should be `[tasks."default::coverage-kcov"]`, which makes more sense.

This solved the problem - thanks!
