### ISSUE TITLE
Travis-ci `cache: cargo` and installing cargo-make with `--debug`

### ISSUE THREAD

**Issue by elpiel** [sagiegurari/cargo-make#247]
Hello,
Again more of a question. Maybe it's good idea to add example with `cache: cargo`, because using the `--debug` will fail when there is this configuration in the `.travis.yml`

**Comment by sagiegurari** [comment]
if you have a good example, i'll add it in.
if you wish you can also submit a PR with the doc change (just make sure to update the content.md as the readme.md is generated from it).

**Comment by elpiel** [comment]
My solution is this:
```
....
cache: cargo
install:
  - if [[ $(cargo list | grep -c make) == 0 ]]; then cargo install --debug cargo-make ; else echo "Cargo make already installed, continuing..."; fi
  - cargo make ci-flow
```

**Comment by elpiel** [comment]
@sagiegurari what would you say about this:
` if (( $(cargo list | grep -c make) == 0 )); then cargo install --debug cargo-make; fi;`
Sadly there is no command in cargo to conditionally install something, the only simple solution I came up with is counting the results from `grep` with `-c` that include `make` and only if there are no results install it. I can't think of anything else.

**Comment by sagiegurari** [comment]
that would work.
i also saw many other examples in github of other projects using travis cache and cargo make in the builds that have different checks and I wonder how good they are compared to this?

this one for example is really short and simple, what do you think?

```sh
which cargo-make || cargo install cargo-make
```

**Comment by elpiel** [comment]
It does output something to the terminal, I guess it depends if that's an issue or not. I would go with `which cargo-make || cargo install cargo-make` it's simple and working. I would guess we are going to leave the suggestion about `--debug` for faster install on the CI, the rest can go like this?
I actually didn't check other repos :sweat_smile: .

**Comment by sagiegurari** [comment]
The output is not an issue. 

Also ```--debug``` is not that important if you cache it, because it happens only once (well... until you clear that cache if you want an updated cargo-make version).
