### ISSUE TITLE
Avoid recompiling when running build + test flow

### ISSUE THREAD

**Issue by emschwartz** [sagiegurari/cargo-make#251]
**Features Description**
When running a workflow like `workspace-ci-flow`, `build-verbose` and `test-verbose` are run as separate steps, which causes the code to be recompiled when the tests are run. It would run faster if the `build-verbose` step called `cargo build --tests ...` to compile all of the tests the first time.

**Describe the solution you'd like**
Call `cargo build` with `--tests` when the `build` and `test` steps are present in a workflow

**Comment by emschwartz** [comment]
Alternatively, just running `cargo test` without running the build step beforehand would trigger the build including the tests before it runs them

**Comment by sagiegurari** [comment]
I'm not sure that will answer all scenarios.
for example, i have the following code in cargo-make:

```rust
#[cfg(test)]
fn exit(code: i32) {
    panic!(code);
}

#[cfg(not(test))]
use std::process::exit;
```

this means, that a different block is compiled for test and for non test.
if for example, I only compile with a test flag, the real app/library may fail in non test compilation mode and we will not know of it (which is the purpose of CI).

dependencies are not recompiled so its not a big overhead in terms of time but its important i think to compile both.
what do you think?

**Comment by emschwartz** [comment]
Fair point. I don't have any code like that so I'll just call the more specific steps myself instead of using the predefined flow

**Comment by sagiegurari** [comment]
by the way cargo build verbose + cargo test verbose are the default travis build steps which i based the ci-flow on (after adding few more stuff of my own like coverage for example).
