### ISSUE TITLE
`fork = true` doesn't work reliably on windows

### ISSUE THREAD

**Issue by LegNeato** [sagiegurari/cargo-make#255]
**Describe the bug**
`foirk=true` appears to not work on windows.

**To Reproduce**

We are using `cargo make` to call `cargo make`. and it is failing, saying `cargo` can't be found.
See https://dev.azure.com/graphql-rust/GraphQL%20Rust/_build/results?buildId=363.

**Error Stack**
```console
'cargo' is not recognized as an internal or external command,
operable program or batch file.
Generating script.
Script contents:
cargo make workspace-ci-flow --no-workspace
```

Haven't had time to investigate what is going on.

**Comment by sagiegurari** [comment]
I see you are running cargo command with full path, like the following:
```$HOME/.cargo/bin/cargo```

is it possible that cargo bin directory is not in the windows PATH?
you should add it and then it should work and you could call cargo without needed full path anymore in your azure piplines scripts.

from cargo-make docs:
```
Make sure to add ~/.cargo/bin directory to your PATH variable.
```

**Comment by LegNeato** [comment]
Possibly. This setup worked until a couple of weeks ago, not sure what changed. I thought windows may have locked down how cargo make is forking, but that may not be the case. I'll investigate.

**Comment by sagiegurari** [comment]
@LegNeato by the way fork=true isn't something special.
its basically alias to:
```toml
command = "cargo"
args = [....]
```
which is something cargo does all over.
i'm pretty sure this all boils down to the bin directory not being in the env.

didn't fully check the azure config, but if rust is installed via rustup, i believe the env var should be defined unless there is an issue on windows with azure+rustup.
in which case, simply adding it manually should resolve it.

**Comment by LegNeato** [comment]
Cool, I'll poke around and reopen if I find a smoking gun!
