### ISSUE TITLE
Can a task increment the version number in cargo.toml?

### ISSUE THREAD

**Issue by LucianoBestia** [sagiegurari/cargo-make#261]
I made a new task in cargo-make for build --release.
I would like to increment the version number in cargo.toml in that task.
How can I do that?
.

**Comment by sagiegurari** [comment]
i guess you could either
1. call some cargo plugin which does that (maybe cargo-release not sure) via cargo-make flow.
2. write a script/rust code and put it in the makefile to do it.

right now, there is no core task for it.
