### ISSUE TITLE
codecov: no coverage report found with tarpaulin

### ISSUE THREAD

**Issue by vtavernier** [sagiegurari/cargo-make#274]
**Describe the bug**
On Travis CI, using `cargo make --no-workspace workspace-ci-flow` results in Tarpaulin being run (as seen in the build log, lines [752](https://travis-ci.com/vtavernier/hyperion.rs/jobs/225545361#L752) and [1282](https://travis-ci.com/vtavernier/hyperion.rs/jobs/225545361#L1282)), but uploading the reports to codecov fails with `No coverage report found` (line [1362](https://travis-ci.com/vtavernier/hyperion.rs/jobs/225545361#L1362)).

**Error Stack**
[.travis.yml](https://github.com/vtavernier/hyperion.rs/blob/479be323f03b76b55ea7f9b021346f2109853329/.travis.yml)
[Travis build log](https://travis-ci.com/vtavernier/hyperion.rs/jobs/225545361#L1362)

**Comment by sagiegurari** [comment]
I don't use tarpaulin so much because it doesn't support arm so i'm not really testing the full CI flow.
I'll try to see what i can do to fix, but if i'm not wrong, tarpaulin has built in support for coverall which you might want to look at as well.

**Comment by sagiegurari** [comment]
@vtavernier your PR is now available in 0.22.1 version which was just published.
thanks a lot
