### ISSUE TITLE
Get current workspace member in an env variable

### ISSUE THREAD

**Issue by roblabla** [sagiegurari/cargo-make#285]
**Features Description**
It'd be nice to know which workspace member is being processed right now. The use-case I have would be to prevent certain tasks to run for some workspace members.

**Describe the solution you'd like**
Have a `CARGO_MAKE_CURRENT_MEMBER` environment variable that is set to the current workspace member project name.

**Code Sample**
N/A

**Comment by sagiegurari** [comment]
cool idea. pretty easy to implement but would take a bit due to network issues :)

**Comment by sagiegurari** [comment]
pushed an implementation for it in the 0.22.2 dev branch.
you will now have an env var: CARGO_MAKE_CRATE_CURRENT_WORKSPACE_MEMBER which will hold the member name (last path element)

**Comment by sagiegurari** [comment]
published in 0.22.2 release
