### ISSUE TITLE
Unclear how I can have a central `Makefile.toml` for a workspace.

### ISSUE THREAD

**Issue by oblique** [sagiegurari/cargo-make#288]
Consider this directory structure:

```
├── Cargo.toml
├── Makefile.toml
├── bar
│   └── Cargo.toml
└── foo
    └── Cargo.toml
```

I want to be able to be inside `foo` directory and `Makefile.toml` of the workspace to be loaded automatically. The only way I found is to create a new makefile within `foo` and use `extend = "../Makefile.toml"`.

Is there a way without creating new makefile in `foo`?

**Comment by sagiegurari** [comment]
can you check this one out?
https://github.com/sagiegurari/cargo-make#usage-workspace-extend

this however relevant if you are running from the workspace root.
when running directly in the member crate, the extend you did is the solution

**Comment by oblique** [comment]
Ok thanks. I will this solution.
