### ISSUE TITLE
A github-action to install cargo-make

### ISSUE THREAD

**Issue by davidB** [sagiegurari/cargo-make#302]
Just to thank you about your powerfull cargo subcommand, and tell you that I use it for cross CI build. And I publish a github-action to ease its installation https://github.com/marketplace/actions/rust-cargo-make (downloading the releases is faster than running `cargo install cargo-make`, like I do on azure-pipelines, travis,...).

During the dev of the action, I noticed that the content of the .zip is not consistent between windows (no top folder) and macosx/linux (with a top folder named like the archive).

Thanks

**Comment by sagiegurari** [comment]
thanks a lot. The github action is pretty cool.
as for the zip, i wasn't aware of that (it was developed as part of a PR) but i think at this point, its better not to change it as it would break scripts/builds for other projects.
