### ISSUE TITLE
Concurrent/Parallel tasks

### ISSUE THREAD

**Issue by emigr2k1** [sagiegurari/cargo-make#321]
**Features Description**
This feature would allow to run a parent task that executes other children tasks parallelly. The parent task would only finish after all children tasks have finished.

**Describe the solution you'd like**
If I have something like
```
[task.build-sass]
command = ["sass"]
args = ["scss/:css/"]

[task.build-ts]
command = ["ts"]
args = ["./ts", "-o", "./js"]

[tasks.build]
run_task = [
    { name = "build-ts", parallel = true },
    { name = "build-sass", parallel = true },
]
```
then I run `cargo make build`, it should execute build-ts and build-sass parallelly.

There is a problem with the output of both tasks because they would be interlapping. This could be fixed by buffering the output of each task and only write it to stdout when the task finishes. Stderr output could be written directly, maybe. I didn't think much about this.

**Comment by sagiegurari** [comment]
thanks, its a really good idea.
i was thinking about it a while back but figured no one would use it so definitely want this to happen.
i was also thinking about the output but there i think we shouldn't buffer.
the result would be a big mess but reason is that there are scripts/cimmands that you invoke that might pause and wait for user input (fir example if you install something with sudo, it will pause for a password).
will definitely check it out.

**Comment by sagiegurari** [comment]
@emigr2k1 I just pushed a commit with the parallel support.
You can read the [docs](https://github.com/sagiegurari/cargo-make/tree/0.24.1#usage-task-command-script-task-examplesubtask) and checkout the parallel flag on how to use it.
if you can try it out and provide some feedback, that would be great.

Simple example:

```toml
[tasks.echo1]
command = "echo"
args = ["1"]

[tasks.echo2]
command = "echo"
args = ["2"]

[tasks.parallel-multi]
run_task = { name = ["echo1", "echo2"], parallel = true }
```

**Comment by emigr2k1** [comment]
@sagiegurari Wow! That was quick.
I just tried it and it's working fine so far. I'll let you know if I have anything else to say.
Thank you!
Should this issue be closed?

**Comment by sagiegurari** [comment]
no need to close. i usually close when i officially release it

**Comment by sagiegurari** [comment]
This is now officially release so i'm closing this issue.
