### ISSUE TITLE
Logging when a task is skipped (caused by mismatch condition)

### ISSUE THREAD

**Issue by davidB** [sagiegurari/cargo-make#326]
**Features Description**
When analyzing output of a run it would be useful to have feedback about Task not executed because condition of the task is not ok.

**Describe the solution you'd like**

- The minimal solution would be display for "skipped" task "Skipped" instead of "Running"
```
[cargo-make] INFO - Running Task: xxxx
```
become
```
[cargo-make] INFO - Skipping Task: xxxx
OR
[cargo-make] INFO - Running Task: xxxx [Skip]
```
- Other alternative: allow to provide a message to display when condition is ko
```toml
condition = { ... else_msg = "the task is skipped X = ${X}" }
```
```
[cargo-make] INFO - Running Task: xxxx
[cargo-make] INFO - Task: xxxx - the task is skipped X = ...
````

- A better solution could be to have the cause, (like "variable XXXX undefined")

Having an intermediary log level (DEBUG is too verbose) or a flag to enable this display is also possible.

**Comment by sagiegurari** [comment]
Changing the output from 'running' to 'skipping' sounds good to me.
I am not sure about the message inside the condition as there is also condition_script that can filter out tasks.

**Comment by sagiegurari** [comment]
@davidB running/skipped printout is now implemented in 0.24.1 development branch.

**Comment by davidB** [comment]
About the message inside the condition, it could be move out (at same level than `condition` and `condition_script`) by example named `skip_message`.
I never try condition_script, if there is an `echo` into the script called by `condition_script` does it is displayed ? if yes, I guess `else_message`(or `skip_message`) could be only an optional field of `condition`.
having more info (to debug) is something than need more reflexion, because it is something that can be useful in some condition (to know why an task is not skip) and sometimes it's the opposite (to hide some behavior).

Thanks for the quick fix.

**Comment by sagiegurari** [comment]
This is now officially release so i'm closing this issue.
I'll create another issue and link to this one regarding the skip message.
i'm not 100% sure how useful it is if its static, but will get to it...
