### ISSUE TITLE
Enable to provide custom condition failure message

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#332]
see #326 for more context

**Comment by sagiegurari** [comment]
@davidB this has now been pushed to the 0.24.2 development branch.
checkout the [docs](https://github.com/sagiegurari/cargo-make/tree/0.24.2#usage-conditions) for usage.
basically you just define the fail_message in the condition object (even if only condition script is setup).

**Comment by davidB** [comment]
Thanks, lot of code to change for adding this attribute.
