### ISSUE TITLE
Embed duckscript to provide real multi platform inprocess scripting capability

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#348]
**Features Description**
Embed duckscript, a shell like scripting language that will provide:
* multi platform solution - no longer need to use @shell
* Enable to modify cargo-make process env and cwd from within the script

**Code Sample**
```toml
[tasks.duckscript-example]
script_runner = "@duckscript"
script = [
'''
task_name = get_env CARGO_MAKE_CURRENT_TASK_NAME
echo The currently running cargo make task is: ${task_name}
cd .. # this changes cargo-make current working directory
pwd
set_env CARGO_MAKE_CURRENT_TASK_NAME tricking_cargo_make
'''
]
```

**Comment by shell** [comment]
Thanks for no longer using me 😄

**Comment by sagiegurari** [comment]
lol sorry about that ```@shell``` is a custom runner name that is used in the code.
but... i'm sure it happens a lot with such a github user name :D

**Comment by shell** [comment]
No worries. Thats what you get for having programming-related name, I've got all kinds of notifications. But then I like to laugh with people about it.
