### ISSUE TITLE
path for watch options

### ISSUE THREAD

**Issue by dakom** [sagiegurari/cargo-make#350]
The [cargo-watch](https://github.com/passcod/cargo-watch) crate allows specifying directories to watch (via the `--watch` or `-w` cli args)

Would it be possible to add this here? Ideally it should have full support including passing multiple directories.

Use case is I am running `cargo-make` in a web project where the wasm is compiled from subdirectories. So they need to be watched specifically, and not interfere with other parts of the project setup (webpack, typescript, etc.)

Thanks!

**Comment by sagiegurari** [comment]
That's good idea. I'll add it.

**Comment by sagiegurari** [comment]
This is now published in the new cargo-make version.
