### ISSUE TITLE
multiple directories in watch

### ISSUE THREAD

**Issue by dakom** [sagiegurari/cargo-make#354]
now that it's possible to add a path to watch (#350 ) - I'm not sure how to add multiple paths.

The syntax for cargo watch itself is to have [multiple `-w` args](https://github.com/passcod/cargo-watch/issues/119#issuecomment-493718619)

I think on the toml side it'd feel natural to have an optional list of paths. e.g.:

```
watch = { watch = ["./crate1/src", "./crate2/src"] }
```

**Comment by sagiegurari** [comment]
no problem.

**Comment by dakom** [comment]
Cool :)

![image](https://user-images.githubusercontent.com/6406986/71633591-d5bf9e00-2c1d-11ea-967e-77dfe9ea118d.png)

**Comment by sagiegurari** [comment]
since this is a breaking change for something i just pushed, decided to create a new release.
it will be available in about 20 minutes
