### ISSUE TITLE
Run task for specific package in the repository

### ISSUE THREAD

**Issue by elpiel** [sagiegurari/cargo-make#363]
**Features Description**
cargo's `--package` option in `cargo-make`

**Describe the solution you'd like**
I would like to see this option as I find it difficult to build a release and zip, since it only does that on the main crate in the `workspace`.
This will allow for repositories that have multiple crates and want to build them separately and independently from each other. Or just running a task for specific member in the main folder.

**Code Sample**
```bash
cargo make -p my_lib clippy
```

**Comment by sagiegurari** [comment]
what if you added an env block per member and name it like the member.
in it you define only that member to be included and than run the whole thing with -p and member name?

**Comment by elpiel** [comment]
I.e. to create a task to be run on each member from the workspace if it has the env. variable defined/not empty? So if there is env. variable in the member's `Makefile` it will execute the task for it.

**Comment by sagiegurari** [comment]
No, you don't need makefile for each member.
What i meant is, lets take for example you have members A, B and C.
in your workspace makefile you can add the following:

```toml
[env.A]
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = "A"

[env.B]
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = "B"

[env.C]
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = "C"
```

And if you run in your workspace level the following:

```sh
cargo make -p B sometask
```

it will use profile 'B' which in turn load ```CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = "B"``` which will result that only that member is invoked with task ```sometask```
what do you think?

**Comment by sagiegurari** [comment]
@elpiel did it solve your issue or you need something additional?

**Comment by elpiel** [comment]
Let me get back to you later since I am no longer working on this task.
Maybe close it for now and reopen it once I come back to it or someone else has similar problem again.

**Comment by ReTWi** [comment]
@sagiegurari i'm not sure how does it work

root Makefile.toml:
```
[env]
CARGO_MAKE_WORKSPACE_EMULATION = true

[env.server]
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = "server"

[env.client]
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = "client"

```

root/server Makefile.toml:
```
[tasks.dev]
command = "cargo"
args = ["watch", "-x", "run"]

```

running from root "cargo make -p server dev" doesn't cd to a server to run task:
```
PS C:\my\apps\root> cargo make -p server dev
[cargo-make] INFO - cargo make 0.32.0
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: dev
[cargo-make] INFO - Profile: server
[cargo-make] INFO - Running Task: workspace

C:\my\apps\root>cd C:\my\apps\root
[cargo-make] INFO - Build Done in 0 seconds.
```

**Comment by sagiegurari** [comment]
is there a reason to use workspace emulation here? it is used when you don't really have a workspace.
in which case you need to tell cargo make what members you have manually because there is no workspace cargo.toml to state it.

**Comment by ReTWi** [comment]
@sagiegurari i don't have a workspace bacouse of side effects (shared target folder and dependencies). I just want to run server and client from root folder.

**Comment by sagiegurari** [comment]
ok, so you need to define all of the members manually in the env block:

```toml
[env]
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS​ = [
    ​"​member1​"​,
    ​"​member2​"​
]
```
