### ISSUE TITLE
Update rustfmt overwrite parameter in examples

### ISSUE THREAD

**Issue by thinkpadder1** [sagiegurari/cargo-make#370]
**Describe the bug**
`rustfmt` replaced `--write-mode` with `--emit`. See the bottom of https://github.com/rust-lang/rustfmt#tips

**To Reproduce**
Run existing simple example on latest stable: https://github.com/sagiegurari/cargo-make#usage-simple

**Error Stack**
```console
[cargo-make] INFO - Execute Command: "cargo" "fmt" "--" "--write-mode=overwrite"
Unrecognized option: 'write-mode'
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

**Code Sample**
```rust
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]
```

**Solution**
Change the args to:
```rust
args = ["fmt", "--", "--emit=files"]
```

**Comment by sagiegurari** [comment]
thanks a lot. i'll update it.
too bad rustfmt always do that and break backward compatibility :(

**Comment by sagiegurari** [comment]
done. thanks a lot
