### ISSUE TITLE
grcov coverage support

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#375]
**Features Description**
Add coverage provider tasks for [grcov](https://github.com/mozilla/grcov)

**Comment by sagiegurari** [comment]
I think this one should be implemented after mozilla/grcov#326 is handled instead of building an entire flow inside cargo-make makefile.

**Comment by kazuk** [comment]
I write cargo-make makefile for grcov.

 https://github.com/kazuk/cargo-make-coverage-grcov

this works on my box (Ubuntu 20.04)

**Comment by sagiegurari** [comment]
really cool. i'll try it out soon.

**Comment by sagiegurari** [comment]
Thanks, this is really great. I'll update the readme to reference your repo.
