### ISSUE TITLE
Version number not correctly reported

### ISSUE THREAD

**Issue by nre-ableton** [sagiegurari/cargo-make#377]
**Describe the bug**

Running `cargo-make --version` just prints out `cargo` and not the actual version. I have so far only tried this with v0.27.0 on Mac, and am not sure if it has been fixed in `master` or for other platforms.

**To Reproduce**

Run `cargo-make --version`.

**Comment by sagiegurari** [comment]
i think you meant to do ```cargo make --version``` no?

**Comment by sagiegurari** [comment]
you can also checkout:
https://github.com/sagiegurari/cargo-make#cli-options

**Comment by nre-ableton** [comment]
> i think you meant to do `cargo make --version` no?

Ah, ok, I see now. So running `cargo-make make --version` prints out `cargo-make 0.27.0` as I was expecting. I found this confusing because running `cargo-make --help` claims that there is a `--version` switch which would print out the version, and it only prints out `cargo`.

I guess this option should be removed, then?

Please forgive my ignorance with these tools; I'm not terribly familiar with cargo or cargo-make, and am installing this tool on behalf of some other developers who need it in our CI infrastructure.

**Comment by sagiegurari** [comment]
so i'm using clap which generates that help docs. i'm not that fond of it but it does most of the job right.
you do have another binary which is makers that you do not need to call cargo first.
so you can do makers --version
makers and cargo-make do the same job just makers doesn't require that cargo prefix....

**Comment by sagiegurari** [comment]
closing this one, but feel free to open new issue if you have any trouble.

**Comment by nre-ableton** [comment]
No problem, thanks for the clarification @sagiegurari!
