### ISSUE TITLE
Obtaining the workspace root

### ISSUE THREAD

**Issue by KaiserKarel** [sagiegurari/cargo-make#382]
I'm using a bunch of workspaces, sharing target directories. I'd like to refer to the root (the directory containing the Cargo.toml with the `workspace.members` key) from one of the nested workspaces. How can I accomplish this?

**Comment by sagiegurari** [comment]
you mean you have a bunch of **crates** which are in the same workspace, right?
if so, when running from the workspace level, you have access to a ** CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY** env var.
however, if you go to a specific crate and run from there, cargo-make is unaware you are in a workspace.

**Comment by KaiserKarel** [comment]
CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY does the trick when running from the root; however I'd like the scripts to also work when ran from other directories. 

Basically I need to access the root `target` directory to load some wasm files; where I specify their location through my programs command line.

**Comment by sagiegurari** [comment]
so currently i don't have that. but could try to add it if you run it from the root of some member crate.

**Comment by KaiserKarel** [comment]
There should be a way to access it through Cargo I reckon; since it is able to figure out where to place all artifacts, even when I'm running cargo make from different directories.

**Comment by sagiegurari** [comment]
ya, didn't say its not possible :)
just that, its not implemented at the moment and going to try to add it soon.

**Comment by KaiserKarel** [comment]
That'd be great. Let me know if I can help out.

**Comment by sagiegurari** [comment]
@KaiserKarel I just pushed a commit to the dev branch to setup CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY correctly even when starting the build in the member crate directly and not in the workspace level.
can you please install it and check if it resolves your issues?

**Comment by KaiserKarel** [comment]
Sorry, bit hectic last couple of days; but it seems to work perfectly!

**Comment by sagiegurari** [comment]
great. will probably release a new official version today/tomorrow.

**Comment by sagiegurari** [comment]
@KaiserKarel just release an official version with this fix.
thanks for the feedback

**Comment by KaiserKarel** [comment]
Perfect, thanks for the quick feature addition!
