### ISSUE TITLE
Extended Makefiles build excessively

### ISSUE THREAD

**Issue by KaiserKarel** [sagiegurari/cargo-make#391]
Extended Makefiles depending on eachother cause excessive builds. See https://github.com/KaiserKarel/cargo-make-dependency-issue for a replication.

**Comment by sagiegurari** [comment]
I don't see an issue, but i do see a strange setup.

1. in workspace level you have CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE - this means that when a member is invoked, its makefile automatically extends the workspace level makefile. 
2. if the workspace level makefile you also have extension to each member... so basically what happens:
* you run cargo make in workspace level
* workspace level makefile is loaded
* it extends each of the member makefiles (this one is strange to me)
* it invokes each member
* for each member, it automatically extends the workspace makefile CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE and somehow doesn't endlessly loop

so now each member when its invoked contains all tasks from workspace and from all members. that's like a leak in a way and an endless recursions.

lets assume thats what you wanted, next lets see the flow.
when you invoke cargo make two, then task two has a dependency on one
so when two is invoked it invoked one and two.
that happens for each member, so one + two are invoked 3 times.
when you invoke cargo make three, three depends on two which depends on one.
so you have one + two + three invoked for each member so thats 3 times.

there isn't an issue here really.

**Comment by sagiegurari** [comment]
closing this one. if you need help to set it up feel free to open an issue.
for workspace example, you might want to look at https://github.com/sagiegurari/duckscript which is a project of mine which is using rust workspace. its fairly simple.
