### ISSUE TITLE
Workspace target directory not being passed in `coverage` flow when run locally

### ISSUE THREAD

**Issue by azriel91** [sagiegurari/cargo-make#40]
#### Problem Description

Is the coverage task intended to only be run in CI builds and not locally?

When running `cargo make coverage` locally, the `coverage-kcov` task misses binaries built in the `<workspace_dir>/target/debug/deps` directory, seemingly because it misses this script:

```toml
[tasks.workspace-members-ci]
description = "Runs the ci-flow for every workspace member."
script = [
'''
#prevent codecov publish in member builds
export CARGO_MAKE_SKIP_CODECOV="true"

export CARGO_MAKE_WORKSPACE_TARGET_DIRECTORY="${CARGO_MAKE_WORKING_DIRECTORY}/target"

#output coverage data goes into workspace level
export CARGO_MAKE_COVERAGE_REPORT_DIRECTORY="${CARGO_MAKE_WORKSPACE_TARGET_DIRECTORY}/coverage"

cargo make --loglevel=${CARGO_MAKE_LOG_LEVEL} ci-flow

unset CARGO_MAKE_COVERAGE_REPORT_DIRECTORY
unset CARGO_MAKE_WORKSPACE_TARGET_DIRECTORY
unset CARGO_MAKE_SKIP_CODECOV
'''
]
```

#### Execution Example

I edited the `coverage-kcov` script a bit to see if `CARGO_MAKE_WORKSPACE_TARGET_DIRECTORY` was populated, but it wasn't:

````text
[cargo-make] INFO - Execute Command: "sh" "/tmp/cargo-make/RFPj37lX46.sh"
+ cd /home/azriel/work/gitlab/azriel91/free_will/crate/application
+ echo Working Directory: /home/azriel/work/gitlab/azriel91/free_will/crate/application
Working Directory: /home/azriel/work/gitlab/azriel91/free_will/crate/application
+ echo CARGO_MAKE_WORKSPACE_TARGET_DIRECTORY: 
CARGO_MAKE_WORKSPACE_TARGET_DIRECTORY: 
+ TARGET_DIRECTORY=target/coverage
+ [ -n  ]
+ mkdir -p ./target/coverage
+ BINARY_DIRECTORY=target/debug/deps
+ [ -n  ]
+ echo Running unit tests from directory: target/debug/deps
Running unit tests from directory: target/debug/deps
+ target/debug/deps/application*
/tmp/cargo-make/RFPj37lX46.sh: 22: /tmp/cargo-make/RFPj37lX46.sh: target/debug/deps/application*: not found
````

#### Error Stack/Info (if any)

If I export `CARGO_MAKE_WORKSPACE_TARGET_DIRECTORY` and `CARGO_MAKE_COVERAGE_REPORT_DIRECTORY` myself, I do get the coverage generated in the right place.

**Comment by sagiegurari** [comment]
I think you are right. I need to setup those env vars for workspace coverage support regardless of ci flow or not.
I'll handle it.
In the meantime, as a temporary workaround, you could define a Makefile.toml in your workspace directory (not in the members) with different coverage task that should resolve it for you.

````toml
[tasks.coverage]
clear = true
script = [
'''
export CARGO_MAKE_WORKSPACE_TARGET_DIRECTORY="${CARGO_MAKE_WORKING_DIRECTORY}/target"
#output coverage data goes into workspace level
export CARGO_MAKE_COVERAGE_REPORT_DIRECTORY="${CARGO_MAKE_WORKSPACE_TARGET_DIRECTORY}/coverage"

cargo make --loglevel=${CARGO_MAKE_LOG_LEVEL} coverage

unset CARGO_MAKE_COVERAGE_REPORT_DIRECTORY
unset CARGO_MAKE_WORKSPACE_TARGET_DIRECTORY
'''
]
````

For a fix, I'll have to setup something a bit more complex unfortunately.

**Comment by sagiegurari** [comment]
Might have not being 100% clear in my workaround, but you will have to execute it in the workspace level as follows:

````sh
cargo make --no-workspace coverage
````

**Comment by sagiegurari** [comment]
Done and released.
You will have to run it as follows as it is a composite flow of both members and workspace level:

````sh
cargo make --no-workspace workspace-coverage
````

See [coverage docs](https://github.com/sagiegurari/cargo-make#usage-predefined-flows-coverage) for more info

**Comment by sagiegurari** [comment]
Please tell me if this solves the issue for you so i'll close this item.

**Comment by azriel91** [comment]
Yeap it does, literally just tried it :smile:

**Comment by sagiegurari** [comment]
:+1:

**Comment by azriel91** [comment]
Something I should've asked before closing, `cargo make --no-workspace workspace-coverage` attempts to upload to codecov by default, is that by design?

**Comment by sagiegurari** [comment]
yap, but you need to enable it by setting the env var in your makefile to upload and you can also replace that task to upload to something else (my plan to provide a task to upload to coverall issue #9 )
