### ISSUE TITLE
Support workspace makefile extension when running directly from member directory

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#410]
see bullet 2 from #409

**Comment by sagiegurari** [comment]
when running cargo make from member directly, i already know today that its part of a workspace, so i could read that workspace makefile and if it has the automatic extend workspace level makefile env setup, i could trigger that flow.

**Comment by sagiegurari** [comment]
This might be more tricky and backfire on users setting their makefile to use different makefile file name or having multiple makefiles in root or just having a root makefile that extends others.
safest way is just have member manually extend using the extend attribute the needed makefile.

closing this one as its more risky then helpful.

**Comment by mraerino** [comment]
seems like because of this, the README might be wrong?

> When running cargo make for modules which are part of a workspace, you can automatically have the member crates makefile (even if doesn't exist) extend the workspace level makefile.

**Comment by sagiegurari** [comment]
I'll need to rewrite that doc to be more explanatory. the meaning wasn't when running from member crate dir directly, but when invoked as part of a workspace build, the crate has ability to get workspace makefile tasks.

remember, that no one really makes you name the makefile with a specific name so its tricky otherwise.
also if you must run directly from crate dir, you should use extend keyword in crate makefile to point to workspace.
