### ISSUE TITLE
Remove nightly requirement to install rustfmt

### ISSUE THREAD

**Issue by connorkuehl** [sagiegurari/cargo-make#418]
**Features Description**
`rustfmt` [can be installed with the stable toolchain](https://github.com/rust-lang/rustfmt#on-the-stable-toolchain), so I think the [`install_crate` step for the builtin `check-format` task](https://github.com/sagiegurari/cargo-make/blob/master/src/lib/descriptor/makefiles/rust.toml#L221) can be simplified to just install it without the condition on nightly.

**Comment by sagiegurari** [comment]
rustfmt do a lot of backward breaks.
so I'll check what now it does, and maybe based on current toolchain I'll set different installation instructions.
similar, like i do with clippy.

**Comment by sagiegurari** [comment]
@connorkuehl  i checked the configuration:
1. i have rustup component setup - so if that is able to install it via rustup thats a higher priority
2. in case rustup is not available, it will install the crate via rustfmt-nigthly which is the crate they publish.

so i'm not sure if there is an issue here. what problem did you face while working with stable? it should have installed rustfmt via rustup for you.

**Comment by connorkuehl** [comment]
Hi @sagiegurari!

> so i'm not sure if there is an issue here. what problem did you face while working with stable? it should have installed rustfmt via rustup for you.

I didn't face any issues. I was just reading some of the source code and I may have misunderstood that `cargo-make` will only install `rustfmt` for the nightly toolchain, but since `rustfmt` had been released for the stable toolchain I was just curious if the default Makefile target could be simplified to  `install_crate = rustfmt`. No bugs, just curious :slightly_smiling_face:

**Comment by sagiegurari** [comment]
ok so install instructions for rustfmt contain both crate name and rustup component.
cargo-make will first try to use the rustup component as it is much faster, and only if fails will fallback to the crate install which requires compilation.
i think for rustfmt we are fine.

The full docs: https://github.com/sagiegurari/cargo-make#usage-installing-dependencies
specifically on what i'm talking about:
https://github.com/sagiegurari/cargo-make#rustup-components

I think its great you are reviewing the code :)
always happy to have more people involved and finding ways to improve cargo-make.
