### ISSUE TITLE
No Colors in Github Actions

### ISSUE THREAD

**Issue by wagenet** [sagiegurari/cargo-make#421]
I'm not at all certain this is cargo-make's fault, but I was hoping that you might be able to give some guidance. I don't have colors turned off and Github Actions does support coloration, so it's not clear why I'm not seeing colors in the logs.

**Comment by sagiegurari** [comment]
Colors are supported via colored (bad name) crate.
the repo is:
https://github.com/mackwic/colored

per their readme:
```
Respect the CLICOLOR/CLICOLOR_FORCE behavior (see the specs)
Respect the NO_COLOR behavior (see the specs)
```

much hunch is that maybe github actions are setting NO_COLOR, but I didn't check it.
I have to admit, i didn't notice it :) and i now i want colors as well....

**Comment by sagiegurari** [comment]
cool. i'll update my ci.yml as well... :)

**Comment by sagiegurari** [comment]
closing this one as it works ok and nothing actionable to do.
thanks for opening it, i just updated all my rust projects to have colors :)
