### ISSUE TITLE
Discussion: Alter "NEW CARGO-MAKE VERSION FOUND!!" message

### ISSUE THREAD

**Issue by olvyko** [sagiegurari/cargo-make#427]
I suggest changing the message about new version of `cargo-make` to more compact one (1-2 lines), since at the moment this message takes up a lot of space (9 lines).

![cargo-make](https://user-images.githubusercontent.com/44478988/82847634-7d9c7780-9eef-11ea-9616-33567a9d246b.png)

as an example: 
```New cargo-make version found (0.30.1 => 0.30.8). Run 'cargo install --force cargo-make'```

**Comment by sagiegurari** [comment]
I think as a 1 liner it would probably not be seen which is like not having it at all.
The current design i took from other cli apps (i think npm).

by default cargo-make will not check for updates more than once a week (between invocations).
you can change it to a month in the global config update_check_minimum_interval param:
https://github.com/sagiegurari/cargo-make#global-configuration-1
so it won't bother you as much if you don't want to upgrade.
you can also run with --disable-check-for-updates cli flag to prevent the check.

**Comment by sagiegurari** [comment]
closing due to lack of feedback
