### ISSUE TITLE
Intuitive way to skip emulated member crates in testing

### ISSUE THREAD

**Issue by lkatalin** [sagiegurari/cargo-make#429]
This may be more of a feature request than a bug; I am not sure.

We are emulating a workspace (many thanks for #415 ) and have one crate in the emulated workspace that will contain our top-level tests, for reasons of internal organization. We want to skip this one crate during `cargo make test` and then invoke it separately *after* the other crates have been built, as part of a command like `cargo make test` or `cargo make ci-flow`. We need this to be a guaranteed order.

So, something like this (which doesn't work as far as I'm aware):
```
[tasks.test]
env = { "CARGO_MAKE_WORKSPACE_SKIP_MEMBERS" = ["topleveltestcrate"] }
```

Is there any way currently to make this happen, other than wrapping `[tasks.test]` in a parent task that forks as part of a composite flow? The reason we don't want to do it that way is:

1. It's fairly complex for a nearly trivial task.
2. It would mean we can't invoke the correct behavior with `cargo make test` because we would instead need to invoke `test`'s composite wrapper / parent; or else we need to completely overwrite the current `test` functionality with `clear = true`, which also seems extreme and didn't seem to mesh well with extending with crate-level makefiles when I tried it last.

I have a small example [here](https://github.com/lkatalin/cargomake/blob/master/Makefile.toml) of what intuitively seems like it "should" work, but doesn't.

One thing I keep imaging is: what if it was possible to define multiple emulated workspaces, so that some tasks could be run only for one of those? On a UI level this seems like it would skip some of the complexity of forking and nesting tasks correctly in order to get the environment variables like `CARGO_MAKE_WORKSPACE_SKIP_MEMBERS` to be properly recognized.

I've tried this many different ways, but it's highly possible that I missed something. Thanks for any advice.

**Comment by sagiegurari** [comment]
the flow sounds kinda complex.
same task, invoked twice in same flow, but once to all crates except one and second time invoked only to that one?

to disable you could do 2 simple things
* add condition in top level to only work if current member is not that specific one (there is env var for current member)
* create a makefile for that member, override that task and just disable it.

but, if you do want to invoked it twice and behave differently, I suggest you create 2 different tasks and than do the logic I wrote above.

**Comment by npmccallum** [comment]
@sagiegurari The primary goal we are trying to accomplish is rather simple: we need to run a bunch of tests after all the crates are built.

We are testing that the output binaries work as designed. If you have an alternative structure suggestion, we're all ears. But the basic idea is:
1. build all the binary crates
2. run lots of tests which use those binaries

**Comment by sagiegurari** [comment]
ok, this means you will have to do some manual stuff i think.
lets say your flow is format, build, test.
but you first want to format + build all crates and only than test all crates.
so its like 2 different workspace flows, managed by one flow (i hope i'm clear... sorry if not).
so you could do something like this in your workspace level makefile.toml (forgive the names, its just to make things clear):

```toml
[tasks.entire_flow]
workspace = false
run_task = { name = ["workspace-build-flow", "test"], fork = true }

[workspace-build-flow]
dependencies = ["format", "build"]
```

**Comment by lkatalin** [comment]
@sagiegurari Thanks so much for your response! That flow makes sense and I ended up using it. For reference for anyone curious, what I ended up doing in order to be able to call that functionality with `cargo make test` instead of a custom command like `cargo make entire_flow` is this:

```
# This will run first fmt + build for each crate and then test for each crate in the emulated workspace.
[tasks.test]
clear = true
workspace = false
run_task = { name = ["fmtbuild", "test-inner"], fork = true }

# Runs format and build (used before testing).
[tasks.fmtbuild]
dependencies = ["format", "build"]

# Copy of "test" under a different name to avoid circular dependency.
[tasks.test-inner]
description = "Runs all available tests."
category = "Test"
command = "cargo"
args = ["test", "@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)", "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )"]
```

**Comment by sagiegurari** [comment]
great to hear it all worked out.
