### ISSUE TITLE
Windows path and duckscript

### ISSUE THREAD

**Issue by roblabla** [sagiegurari/cargo-make#430]
**Describe the bug**
When I try to use `${CARGO_MAKE_WORKING_DIRECTORY}` in certain positions in duckscript from windows, it causes the following error:

> [cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 19 - Source: Unknown Line: 1 - control character found without a valid value

The error is extremely confusing: it doesn't trigger all the time (for instance, `echo ${CARGO_MAKE_WORKING_DIRECTORY}` works fine, but `if is_path_exists ${CARGO_MAKE_WORKING_DIRECTORY}` will fail.

My understanding is that duckscript will replace CARGO_MAKE_WORKING_DIRECTORY with the string, which contains backslashes. It will then try to interpret those backslashes as control characters/escape sequences, instead of a literal backslash character?

**To Reproduce**
Create a Makefile.toml with the code in the below code sample, and run `cargo make reproduce`

**Code Sample**
```rust
[tasks.reproduce]
script_runner = "@duckscript"
script = [
'''
if is_path_exists ${CARGO_MAKE_WORKING_DIRECTORY}
end
''']
```

**Comment by sagiegurari** [comment]
thanks for reporting. ya, that's a definite bug.

**Comment by sagiegurari** [comment]
@roblabla I fixed the duckscript sdk.
you can reinstall cargo-make and it should pick it up.

**Comment by roblabla** [comment]
Yup, it's fixed! Thanks a lot :D
