### ISSUE TITLE
Duckscript for loop with multi-line env variable

### ISSUE THREAD

**Issue by dalance** [sagiegurari/cargo-make#437]
**Features Description**
I want to do for loop with multi-line env variable like below:

```toml
[env]
ARRAY0 = [
"a",
"b",
]

ARRAY1 = '''
a
b
'''
```

**Describe the solution you'd like**

I tried several variation, and found the combination of `array` and `replace` works fine.
Is this expected? If there is more sophisticated way, I want to know it.

```toml
[env]
ARRAY0 = [
"a",
"b",
]

ARRAY1 = '''
a
b
'''

# don't work
[tasks.array0-0]
script_runner = "@duckscript"
script = [
'''
for i in ${ARRAY0}
  echo ${i}
end
'''
]

# don't work
[tasks.array0-1]
script_runner = "@duckscript"
script = [
'''
array0 = array %{ARRAY0}
for i in ${array0}
  echo ${i}
end
release array0
'''
]

# work fine
[tasks.array0-2]
script_runner = "@duckscript"
script = [
'''
array0 = replace ${ARRAY0} ; " "
array0 = array %{array0}
for i in ${array0}
  echo ${i}
end
release array0
'''
]

# don't work
[tasks.array1-0]
script_runner = "@duckscript"
script = [
'''
for i in ${ARRAY1}
  echo ${i}
end
'''
]

# don't work
[tasks.array1-1]
script_runner = "@duckscript"
script = [
'''
array1 = array %{ARRAY1}
for i in ${array1}
  echo ${i}
end
release array1
'''
]

# work fine
[tasks.array1-2]
script_runner = "@duckscript"
script = [
'''
array1 = replace ${ARRAY1} \n " "
array1 = array %{array1}
for i in ${array1}
  echo ${i}
end
release array1
'''
]
```

**Comment by sagiegurari** [comment]
This is a great question.
so a list env var is a cargo-make thing, as in reality env vars are key/value and cargo make enables you to do key/list.
however as you probably saw, the way i do it, is i concat all values using the ';' char.
so key=[a,b,c] becomes key=a;b;c

duckscript, has no idea of multi value env vars, so it just sees a;b;c
so using the spread won't work as spread works on spaces (see docs: https://github.com/sagiegurari/duckscript#tutorial-commands-using-variables-spread-binding)
so i think the simplest solution is using split (https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__string__Split)

```bash
array = split ${ARRAY0}
for i in ${array} ;
  echo ${i}
end
release ${array}
```

as for arrays defined as multi line string such as:
```toml
ARRAY1 = '''
a
b
'''
```

you can use the split again, but this time using the \n char.
so:
```bash
array = split ${ARRAY} \n
```

**Comment by sagiegurari** [comment]
@dalance i think this answers your question. if you need anything more feel free to open a new issue or reopen this one.

**Comment by dalance** [comment]
@sagiegurari I'll use `split` instead of `replace` and `array`. Thank you!
