### ISSUE TITLE
Unable to run task in workspace crate

### ISSUE THREAD

**Issue by philip-peterson** [sagiegurari/cargo-make#448]
**Describe the bug**
Running a task in a workspace-style crate is not possible.

**To Reproduce**
1. Clone the following repository: https://github.com/philip-peterson/repro-cm-issue
2. In the repo root, run `cargo make example`
3. Observe the actual output compared to the expected (which is `hi`)

**Error Stack**
```console
[cargo-make] INFO - cargo make 0.32.1
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: example
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: workspace
[cargo-make][1] INFO - External file not found or is not a file, skipping.
[cargo-make][1] INFO - Project: s1
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: example
[cargo-make][1] INFO - Profile: development
[cargo-make][1] ERROR - Task example not found
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

**Comment by sagiegurari** [comment]
when running member s1 task example, it will run cargo make inside s1 dir and see no such task.

if you want to pull in all tasks from the root workspace makefile, just add the env var as defined at https://github.com/sagiegurari/cargo-make

**Comment by philip-peterson** [comment]
I’m talking about running `cargo make example` not from the `s1` directory but its parent directory.

**Comment by sagiegurari** [comment]
me too. did you try adding the env var in the makefile as the documentation i linked to?

**Comment by philip-peterson** [comment]
OK, that (`CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE`) does seem to work. It seems very confusing though, why is it considered extending the workspace, when the makefile is _in_ the workspace?

**Comment by sagiegurari** [comment]
when you run cargo make in workspace root, it will instead run cargo make for each member in member folder with the task you asked.
this allows you to run actions on all members automatically, like build, format, clippy,....
when it runs the action for the member, it starts a new cargo make instance in the member folder itself.
so it reads the makefile from there , which in your case doesn't exist but that's fine. most times, you want to use the workspace level makefile inside the member. that's what that env does.
there are other ways to achieve this, but this is the simplest one.
anyway, what it does is automatically makes the member makefile (even if doesn't exist) extend the workspace level makefile

**Comment by sagiegurari** [comment]
ok, now i see i sent a link to the project and not the right section,
i meant to send this:
https://github.com/sagiegurari/cargo-make#usage-workspace-extend

also, to better understand why every member just doesn't use the workspace level makefile as is, is that they might have different needs and implementation.
for example a frontend/backend workspace project.
for backend, build means cargo build, for frontend, it would use wasm maybe... so each would write what it means when someone does build for the entire workspace, it their specific member makefiles.

**Comment by philip-peterson** [comment]
My question is more around the function of running a task in the root being what it is. Intuition would dictate that defining a duckscript task in the workspace crate with 3 sub-crates and then running the task from the workspace crate, would only run that duckscript task once for the workspace crate, since the workspace crate is itself, a crate.

Is there no way to define a top-level task that doesn't need to be inherited in order to run?

**Comment by sagiegurari** [comment]
ok so its actually the reverse how i see it and thats why the confusion.
a workspace in rust is a collection of crates. the root folder is not a crate and doesn't have any functionality. it only groups all those member crates.
so cargo make in workspace mode means, it actually invokes the actions you want (like build) on each member and ignores the root folder. since if you are in a workspace and you want to run build, you don't build the workspace root, there is nothing there. so it goes crate by crate.
thats workspace mode.

if you want to run some action on the workspace folder itself, you need to tell cargo-make to ignore this is a workspace and look at it as a simple folder with a makefile and to run stuff on that folder. so in that case you tell cargo make to ignore workspace. there is a cli flag for that, and you can defined workspace=false on the task and so on... 

i explain it at:
https://github.com/sagiegurari/cargo-make#usage-workspace-support

**Comment by philip-peterson** [comment]
Excellent, thank you!

**Comment by ollyde** [comment]
I have a default project, new. I install cargo make, try to run the command. It fails. Any ideas?

<img width="492" alt="Screenshot 2023-12-28 at 15 32 21" src="https://github.com/sagiegurari/cargo-make/assets/6940726/429811bb-90bd-452e-b7c7-ccb45dd66d66">

**Comment by huaidanatu** [comment]
我没有使用成功，我希望可以在工作空间的根目录直接使用cargo make,来同时启动多个项目，这样对于我来说是非常有意义的。

**Comment by sagiegurari** [comment]
@huaidanatu not sure what is the request here... if you have an issue please open one and translate the request to english so i can help
