### ISSUE TITLE
Run parallel tasks for specific members

### ISSUE THREAD

**Issue by lidin** [sagiegurari/cargo-make#451]
**Features Description**
I have come a across a use case regarding watching file changes in several crates in a project, which I want to watch separately and perform different flows of actions separate of each other. I would also like to start these watchers from a workspace root task, in parallel, so that I can watch these crate changes at the same time in one window. So my project structure looks roughly something like this:

```
$PROJECT_ROOT/Makefile.toml
$PROJECT_ROOT/src/frontend/Makefile.toml
$PROJECT_ROOT/src/backend/Makefile.toml
```

`frontend` and `backend` have separate flows defining the watch behavior needed for their code. I have found a way to create a workspace flow that combines these crate flows into one execution line:

`$PROJECT_ROOT/Makefile.toml`
```rust
[tasks.watch-flow]
description = "Watch all project files, and recompile and rerun the project on change."
workspace = false
clear = true
run_task = { name = [
    "watch-frontend",
    "watch-backend"
], fork = true, parallel = true }
```

`$PROJECT_ROOT/src/frontend/Makefile.toml`
```rust
[tasks.watch-frontend]
description = "Watch frontend files and recompile the project on change."
run_task = { name = ["build", "refresh-browser"] }
watch = true

[tasks.watch-backend]
# No op
```

`$PROJECT_ROOT/src/backend/Makefile.toml`
```rust
[tasks.watch-backend]
description = "Watch backend files and rerun the project on change."
command = "cargo"
args = ["run"]
watch = true

[tasks.watch-frontend]
# No op
```

This works, but it would be nice if I could make this work without defining the `watch-backend` and `watch-frontend` no op tasks in the respective crates.

**Describe the solution you'd like**
I am looking for a way to point to a specific member of the workspace for which to perform a specific task, and at the same time run them in parallel. A code example for this could look like the following:

`$PROJECT_ROOT/Makefile.toml`
```rust
[tasks.watch-flow]
description = "Watch all project files, and recompile and rerun the project on change."
workspace = false
clear = true
run_task = { tasks = [
  { name = "watch", member = "frontend" },
  { name = "watch", member = "backend" }
], fork = true, parallel = true }
```

`$PROJECT_ROOT/src/frontend/Makefile.toml`
```rust
[tasks.watch]
description = "Watch frontend files and recompile the project on change."
run_task = { name = ["build", "refresh-browser"] }
watch = true
```

`$PROJECT_ROOT/src/backend/Makefile.toml`
```rust
[tasks.watch]
description = "Watch backend files and rerun the project on change."
command = "cargo"
args = ["run"]
watch = true
```

An alternative would be to make `run_task = { name = "watch", fork = true, parallel = true }` be interpreted as start the `watch` task in each member in parallel. Right now only the first member gets a chance to start the task, while the other crates are starved.

**Comment by sagiegurari** [comment]
Let me think what can be done to simplify this use case without adding too much complexity to the run_task definition.

**Comment by sagiegurari** [comment]
Hi @lidin I've been thinking about this for a while. 
run_task supports many features (i just added cleanup_task as well) and it is becoming too complex.
i prefer not to have that attribute be also workspace aware and such.
i know you have a hacky solution that you are not a fan of, but parallel right now means running tasks from the list in parallel and not members in parallel. making it member aware, makes the whole parallel feature very unreadable and unpredictable.

another workaround to that, is to use duckscript, for example:

```toml
[tasks.watch-flow]
description = "Watch all project files, and recompile and rerun the project on change."
workspace = false
clear = true
script = [
'''
#!@duckscript

fn run_watch
  cd ./$1
  spawn cargo make watch
  cd ..
end

run_watch frontend
run_watch backend
'''
]
```

but it's not a great hack either.

**Comment by lidin** [comment]
Hi, @sagiegurari. Thank you for putting out the time to think about this. I totally agree that adding more complexity to the run_task feature is probably not a good idea. I will make do with the solution for now, and think about it a bit more, to see if there is a better way to do this. :) I’ll close this issue for now.
