### ISSUE TITLE
Cannot use relative path dependencies in Rust scripts (cargo-script)

### ISSUE THREAD

**Issue by emgre** [sagiegurari/cargo-make#454]
**Describe the bug**
When using a Rust script, specifying path dependencies fails to resolve. `cargo-make` seems to change the working directory of `cargo-script` and the crate resolution then fails. `cargo-script` supports setting the path for resolution using the environment variable `CARGO_SCRIPT_BASE_PATH` (see [this](https://github.com/DanielKeep/cargo-script#environment-variables)). However, setting that environment variable in `cargo-make` does not solve this issue. It seems to always be overrided.

**To Reproduce**

The following Makefile can be used to reproduce the bug. Of course, you need a Rust lib in the `foo` directory.

```toml
[config]
default_to_workspace = false

[env]
CARGO_SCRIPT_BASE_PATH = "${CARGO_MAKE_WORKING_DIRECTORY}"

[tasks.c-bindings]
script_runner = "@rust"
script = [
'''
//! ```cargo
//! [dependencies]
//! foo = { path = "foo" }
//! ```
fn main() {
    println!("{:?}", std::env::var("CARGO_SCRIPT_BASE_PATH"));
}
'''
]
```

**Error Stack**
```console
[cargo-make] INFO - cargo make 0.32.4
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: c-bindings
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: c-bindings
[cargo-make] INFO - Execute Command: "cargo" "script" "C:\\Users\\emile\\AppData\\Local\\Temp\\fsio\\g9V91YzSvS.rs"
error: failed to get `foo` as a dependency of package `g9V91YzSvS v0.1.0 (C:\Users\emile\AppData\Local\Cargo\script-cache\file-g9V91YzSvS-aa7d20e2c54705e2)`

Caused by:
  failed to load source for dependency `foo`

Caused by:
  Unable to update C:\Users\emile\AppData\Local\Temp\fsio\foo

Caused by:
  failed to read `C:\Users\emile\AppData\Local\Temp\fsio\foo\Cargo.toml`

Caused by:
  Le chemin d’accès spécifié est introuvable. (os error 3)
internal error: cargo failed with status 101
[cargo-make] ERROR - Unable to execute rust code.
[cargo-make] WARN - Build Failed.
```

**Comment by sagiegurari** [comment]
Thanks for reporting.
strange that CARGO_SCRIPT_BASE_PATH doesn't resolve that problem as i do not touch that env var myself at all.
so if you define it, it should stay accurate for any child process running.
can you remove the ```foo = { path = "foo" }``` and see what the output of CARGO_SCRIPT_BASE_PATH is? it should stay ok.

**Comment by sagiegurari** [comment]
oh... its windows.... its possible that CARGO_MAKE_WORKING_DIRECTORY on windows is just a '.' and not absolute path like on linux/mac (can't remember).
in which case i get why its not working.
how about doing this:

```toml
env_scripts = [
'''
#!@duckscript
dir = pwd
# if dir is not absolute path on windows maybe also add following line
# dir = canonicalize ${dir}
set_env CARGO_SCRIPT_BASE_PATH ${dir}
'''
]
```

**Comment by emgre** [comment]
This code:

```rust
fn main() {
    println!("{:?}", std::env::var("CARGO_SCRIPT_BASE_PATH"));
    println!("{:?}", std::env::var("CARGO_MAKE_WORKING_DIRECTORY"));
}
```

Prints the following:

```console
Ok("C:\\Users\\emile\\AppData\\Local\\Temp\\fsio")
Ok("D:\\Desktop\\test\\")
```

So the `CARGO_MAKE_WORKING_DIRECTORY` is properly set, but `CARGO_SCRIPT_BASE_PATH` is not set, even if I do it explicitly in the Makefile.toml.

**Comment by sagiegurari** [comment]
ok so i was reading the docs more carefully, it seems CARGO_SCRIPT_BASE_PATH is provided BY cargo-script and not TO cargo-script. so it doesn't matter what you set there.
seems like a limitation in cargo-script which is out of my scope.
not sure how complex what you are doing, but did you think about the embedded [duckscript](https://github.com/sagiegurari/duckscript) runner?

**Comment by emgre** [comment]
Oh, you are right. I misread the documentation. Sadly, duckscript won't be enough, I need the dependency to read info represented in Rust to generate Rust code. I'll stick with my current solution of just having another bin target in my workspace that depends on it and running it as a script with `cargo run --bin foo`. Thanks for your help!
