### ISSUE TITLE
How can i define a variable if it's not blank?

### ISSUE THREAD

**Issue by Kreyren** [sagiegurari/cargo-make#460]
In my C-based Makefiles i use (for example):

```Makefile
GIT ?= git

target:
	@ "$(GIT)" clone <repo> <destination>
```

Which is done to optimize the automatization of Continuous Integration (CI) or during the development as a part of code quality assurance.

Is there a way to assign a variable in `cargo-make` if it's not blank i.e `GIT ?= git` in C-based Makefile?

**Comment by Kreyren** [comment]
Found

```rs
PREFER_EXISTING = { value = "new", condition = { env_not_set = ["PREFER_EXISTING"] } }
```

which is quite ugly compared to C-based makefile, but usable.

Closing as solved.

**Comment by sagiegurari** [comment]
for your use case, ya maybe ugly but

1. I'm using toml format. your is just not valid
2. unlike make, conditions can check a lot more than just, not set. you can set env vara only if on right OS, rust channel, file exists and more. so tou need to look at the big picture.

**Comment by Kreyren** [comment]
> unlike make, conditions can check a lot more than just, not set. you can set env vars only if on right OS, rust channel, file exists and more. so you need to look at the big picture. @sagiegurari 

Agree that current conditions are superior to proposed and that other OS are a concern, but this is readability concern where i don't see why using

```toml
VAR ?= value
```

in toml woudn't be friendly to cross-platform development assuming that it would assign the value on systems that do not have a usable environment to get the variable from?

**Comment by Kreyren** [comment]
^ Note that i am not suggesting replacing the current, but adding this on top of that for the usecase where the conditions are making the code less readable

**Comment by sagiegurari** [comment]
readable is not always that objective. make syntax sometimes puzzles me :D
but seriously, i already get feedback from people that there are too many ways of doing same thing.
so, i prefer to keep it one way. maybe a bit verbose, ya agree, but very readable as in 'env_not_set' is more explanatory then ?= for people not coming from make

**Comment by Kreyren** [comment]
> make syntax sometimes puzzles me :D @sagiegurari 

FWIW that concern is mostly based on my experience with make where i try to write my code alike:

```makefile

...

#@ List all targets
list:
	@ true \
		&& grep -A 1 "^#@.*" Makefile | sed s/--//gm | sed s/:.*//gm | sed "s/#@/#/gm" | while IFS= read -r line; do \
			case "$$line" in \
				"#"*|"") printf '%s\n' "$$line" ;; \
				*) printf '%s\n' "make $$line"; \
			esac; \
		done

...

###! We are using '#& APPEND something' in the code that is being replaced with a code from a vendor using ed

<QA comments removed>
\@ Build the script
build: vendor
	$(info Building..)
	@ [ -d "$(BUILD)" ] || mkdir "$(BUILD)"
	@ [ -f "$(BUILD)/$(NAME).sh" ] || cp "$(SRC_DIR)/$(NAME).sh" "$(BUILD)/$(NAME).sh"
	@ true \
		&& $(PRINTF) 'INFO: %s\n' "Replacing '#& APPEND path' with requested code" \
		&& $(GREP) "^#& APPEND.*" "$(SRC_DIR)/$(NAME).sh" | while IFS= read -r string; do \
				true \
				&& $(PRINTF) '%s\n' "Processing $${string##*/} from appended" \
				&& $(CP) "$${string##\#& APPEND }" "vendor/$${string##*/}" \
				&& : "Remove shebang from appended code" \
				&& $(PRINTF) "g/^#!\/.*/d\nw\nq\n" | $(ED) -s "vendor/$${string##*/}" \
				&& : "Remove documentation comments from appended code" \
				&& $(PRINTF) "g/###! .*/d\nw\nq\n" | $(ED) -s "vendor/$${string##*/}" \
				&& : "Remove shellcheck directives from appended code" \
				&& $(PRINTF) "g/# shellcheck .*/d\nw\nq\n" | $(ED) -s "vendor/$${string##*/}" \
				&& : "Remove comments from appended code" \
				&& $(PRINTF) "g/^# .*/d\nw\nq\n" | $(ED) -s "vendor/$${string##*/}" \
				&& : "Remove the first three blank lines if they are present (mostly they are)" \
				&& $(PRINTF) "1;/./-d\\nw\\nq\\n" | ed -s "vendor/$${string##*/}" \
				&& : "Replace '#& APPEND ...' with content from the file" \
				&& $(PRINTF) "/^#& APPEND $$($(PRINTF) '%s\n' "$${string##\#& APPEND }" | $(SED) "s#\/#\\\/#gm")/d\n-1r vendor/$${string##*/}\\nw\\nq\\n" | ed -s build/dockervuantor.sh\
				&& $(PRINTF) '%s\n' "File '$$string' has been processed";\
			done \
		&& $(PRINTF) '%s\n' "Replaced all mensioning of '#& APPEND path' with requested code"
	@ true \
		&& $(PRINTF) '%s\n' "Removing tag 'BUILD-CHECK' allowing the script to run" \
		&& $(PRINTF) '/^#& BUILD-CHECK/d\nd\nw\nq\n' | ed -s "$(BUILD)/$(NAME).sh" \
		&& $(PRINTF) '%s\n' "tag 'BUILD-CHECK' and it's relevant code has been removed"
	@ true \
		&& : "Build userlands" \
		&& "$(BUILD)/$(NAME).sh" --create ascii beowulf chimaera ceres \
	$(info Build phase finished)
```

which cargo-make seems to have implemented in a better way so readability might not be as concerning, closing as solved for the time being..

---

> so, i prefer to keep it one way. maybe a bit verbose, ya agree, but very readable as in 'env_not_set' is more explanatory then ?= for people not coming from make @sagiegurari 

True it's more phonetic in terms of readability for those not experienced with c-based makefiles.

---

EDIT: Might be worth noting:

In my development size is also a concern so comparing:

```toml
PREFER_EXISTING = { value = "new", condition = { env_not_set = ["PREFER_EXISTING"] } }
```

to

```makefile
PREFER_EXISTING ?= new
```

on ASCII system seen as:

```
# C-based Makefile (47 bits)
80 82 69 70 69 82 95 69 88 73 83 84 73 78 71 32 63 61 32 110 101 119 
```

```
# Cargo-make (200 bits)
80 82 69 70 69 82 95 69 88 73 83 84 73 78 71 32 61 32 123 32 118 97 108 117 101 32 61 32 34 110 101 119 34 44 32 99 111 110 100 105 116 105 111 110 32 61 32 123 32 101 110 118 95 110 111 116 95 115 101 116 32 61 32 91 34 80 82 69 70 69 82 95 69 88 73 83 84 73 78 71 34 93 32 125 32 125 
```

(spaces excluded)

Makes cargo-make to require 4.25531914894 times more storage.

plain text to ascii converted using https://www.browserling.com/tools/text-to-ascii.
