### ISSUE TITLE
Expansion of env in scripts?

### ISSUE THREAD

**Issue by Kreyren** [sagiegurari/cargo-make#466]
## Features Description

Make it possible to expand variables in `script`:

![image](https://user-images.githubusercontent.com/11302521/94951611-e66eae80-04e4-11eb-9fa6-b32cd82ec7ba.png)

Expecting to return `text: something`.

## Rationale

My makefiles usually look like:

```makefile
...

# Build overrides
BUILD ?= "$(PWD)/build/"
VENDOR ?= "$(PWD)/vendor/"
SRC_DIR ?= "$(PWD)/src"
CACHE_DIR ?= "$(HOME)/.cache"

...

#& Build with linux kernel as backend
build-linux-standalone: vendor-linux
	@ [ -d "$(BUILD)" ] || "$(MKDIR)" "$(BUILD)"
	@ [ -d "$(BUILD)/$(PROJECT_NAME)/linux" ] || "$(MKDIR)" "$(BUILD)/$(PROJECT_NAME)/linux"
	@ scripts/deployment/filesystem.sh "$(BUILD)/$(PROJECT_NAME)/linux/standalone" --fsh3_0
	@ [ -d "$(BUILD)/$(PROJECT_NAME)/linux/standalone/bedrock" ] || "$(CP)" -r "$(SRC_DIR)/slash-bedrock" "$(BUILD)/$(PROJECT_NAME)/linux/standalone/$(PROJECT_NAME)"
	@ [ -s "$(BUILD)/$(PROJECT_NAME)/linux/standalone/run/init" ] || "$(CP)" "$(SRC_DIR)/init/init" "$(BUILD)/$(PROJECT_NAME)/linux/standalone/run/init"
	@ make -C "$(VENDOR)/linux" localmodconfig
	@ make --jobs "$$(nproc || printf 1)"
	@ INSTALL_PATH="$(BUILD)/$(PROJECT_NAME)/linux/standalone" make install

...
```

Which is one of the main reasons to use makefiles for the repository management for me and thus proposing it to be implemented.

## Concern about env expansion in scripts

It was mentioned in https://github.com/sagiegurari/cargo-make/issues/461#issuecomment-701922500

> scripts do not support env expansion. i'm not going to do that since that would lead to bugs. for example you wrote a bash where you define a var and than use it. if i expanded before invocation, it has the wrong value. @Sagie Gur-Ari

from my point of view the expansion prior to invocation is expected and to avoid conflicts alike bash expanding variables `${var}` this is done on for example makefile as `$${var}` that escapes the dollar sign.

**Comment by sagiegurari** [comment]
cargo-make doesn't work with internal variables, it works with env variables.
so setting 

```toml
[env]
MESSAGE = "something"
```

Sets an env var. That env var is available in all child processes like ecl scripts and you can pick them up from the env.
replacing that with your request is

* going to break backwards compatibility in a really critical way
* can cause lots of issues in terms of breaking the scripts - for example what is the variable has "word1 word2"? it might break the script invocation of that line. that doesn't happen in env expansion for commands.
* scripts will become less readable as they will be a mix of their respective lang syntax + cargo-make behaviour.


In general, cargo-make is not gnu make.
It doesn't aim to be and the approach is meant to be a lot more declarative and simple.

**Comment by Kreyren** [comment]
That works for me, thanks for info

![image](https://user-images.githubusercontent.com/11302521/95006811-8ec96380-0608-11eb-87c4-6991a64e6cbc.png)
