### ISSUE TITLE
Doesn't support command cargo --version in task

### ISSUE THREAD

**Issue by lygstate** [sagiegurari/cargo-make#476]
### Describe The Bug

The following task caused error
```
[tasks.build]
command = "cargo"
args = ["--version"]
```

**Comment by sagiegurari** [comment]
@lygstate thanks a lot for reporting this.
I see the automatic crate installation kicked in for that as well and tried to find a crate named --version which is naturally totally wrong :)
i'll have that fixed. thanks for reporting.

**Comment by sagiegurari** [comment]
@lygstate this is now fixed in the 0.32.8 development branch.

**Comment by sagiegurari** [comment]
@lygstate the fix is now published.
