### ISSUE TITLE
Conditional env vars

### ISSUE THREAD

**Issue by berkus** [sagiegurari/cargo-make#485]
Hi, not sure if this is implemented already, couldn't find it in the docs:

One common pattern I use is to set cargo-make env variable to corresponding env var if it's defined, or revert to a default value if not set:
```
QEMU = { value = "${QEMU}", condition = { env_set = ["QEMU"] } }
QEMU = { value = "qemu-system-aarch64", condition = { env_not_set = ["QEMU"] } }
```

Is there a shorter way to express that? If not, could it be added?

**Comment by sagiegurari** [comment]
you only need the second line, no?

**Comment by berkus** [comment]
Hmm, you're probably right, thanks! :)
