### ISSUE TITLE
JSON schema for Taplo

### ISSUE THREAD

**Issue by tamasfe** [sagiegurari/cargo-make#489]
You could submit a schema for [Taplo](https://github.com/tamasfe/taplo) for autocompletions and docs in its [VS Code extension](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml).

The easiest way would be to use [schemars](https://github.com/GREsau/schemars) and this project could have some VS Code IDE support with minimal effort.

**Comment by sagiegurari** [comment]
Cool idea. My only concern is the fact that i add new capabilities and require to change the format by adding more attributes or having attributes support additional data types.

**Comment by tamasfe** [comment]
Yeah, it's generally a good idea to version config files this complex, at least that's how [taskfile](https://taskfile.dev/#/) handles major changes. (although Taplo doesn't handle these kind of complex schemas nicely yet ([#57](https://github.com/tamasfe/taplo/issues/57)))

On a second thought, I'm planning to create some kind of repository, as every tool supports fetching via http instead of bundling schemas, this would make everything a lot more flexible.

**Comment by sagiegurari** [comment]
created an issue in taplo for it. once that is implemented, i'll work on creating a schema and uploading it to that new repo.
otherwise it will break very often.

**Comment by sagiegurari** [comment]
tamasfe/taplo#58

**Comment by tamasfe** [comment]
@sagiegurari This is now implemented for Taplo, and the documentation is [here](https://taplo.tamasfe.dev/configuration/#schemas) if you're still interested.

**Comment by sagiegurari** [comment]
this is great. I'll work on that. thanks a lot

**Comment by sagiegurari** [comment]
Started working on this one, but seems to be a lot of effort.
Would love to get some help with this.

**Comment by tamasfe** [comment]
I can look into this

**Comment by sagiegurari** [comment]
feels like ruat struct->json schema might be a good standalone project

**Comment by tamasfe** [comment]
Such project [exists](https://github.com/GREsau/schemars), this is what I also usually use, just slap `derive(JsonSchema)` on the structs in question and call `schema_for!()` somewhere.

The `taplo-cli` has schemars as a normal dependency, and it has a command to print its own config schema, but I have no idea how much bloat and compilation time it actually adds. Should something similar be done here as well?

**Comment by tamasfe** [comment]
Someone has submitted a schema (https://github.com/tamasfe/taplo/pull/164), so I believe this can be closed.

It seems to be hand-crafted, so I don't know how updates will be handled, nonetheless it should provide a better experience in IDEs than a generated one.

**Comment by sagiegurari** [comment]
@tamasfe thanks a lot, I see the PR
1500 lines by hand is crazy :)
