### ISSUE TITLE
Pass arguments to be used as variables

### ISSUE THREAD

**Issue by dakom** [sagiegurari/cargo-make#500]
### Feature Description
When running cargo make, allow arbitrary arguments to be used as variables in the tasks

### Problem

I have a situation where there is a repeatable pattern of stuff like this:

```rust
[tasks.user-local]
script_runner = "@duckscript"
script = '''
set_env APP_NAME user 
cm_run_task local
'''

[tasks.user-release]
script_runner = "@duckscript"
script = '''
set_env APP_NAME user 
cm_run_task release
'''

[tasks.admin-local]
script_runner = "@duckscript"
script = '''
set_env APP_NAME admin
cm_run_task local
'''

[tasks.admin-release]
script_runner = "@duckscript"
script = '''
set_env APP_NAME admin
cm_run_task release
'''

```

In this example, there are two things that need to happen:

1. the APP_NAME env var needs to be set
2. the sub-task needs to be run

### Solution

it would be great if I could instead do something like:

```
[tasks.generic-builder]
script_runner = "@duckscript"
script = '''
set_env APP_NAME ${ARG[0]}
cm_run_task ${ARG[2]}
'''
```

and then run it like `cargo make generic-builder -- user release` or `cargo make generic-builder -- admin local`

**Comment by sagiegurari** [comment]
I pretty sure thats already supported.
if we are talking about duckscript you should have variables 1 and 2 defined.
so you could do

```toml
[tasks.generic-builder]
script_runner = "@duckscript"
script = '''
set_env APP_NAME ${1}
cm_run_task ${2}
'''
```

**Comment by dakom** [comment]
this does work, thanks :)

Is there a way in Duckscript to exit early if ${1} isn't one of a predefined list of strings?

**Comment by sagiegurari** [comment]
you van create a set of strings and check if it is contained it that set.

https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md

if not, just do exit the script
