### ISSUE TITLE
Feature: Strict mode / validation

### ISSUE THREAD

**Issue by d4h0** [sagiegurari/cargo-make#506]
### Feature Description

It would be nice, if there was an option for a strict mode that validates `Makefile.toml` files.

For example, I had the following task:

```
[tasks.start-dev-server]
commad = "${NODE_BIN}/browser-sync"
args = ["start", "--server", "build/dev", "--no-open", "--watch"
```

...and was wondering why my live-reload server didn't work.

Turned out, I missed an "n" in "command".

### Describe The Solution You'd Like

Would it be possible to recognize cases like these, and fail or show a warning?

Maybe the [strsim](https://crates.io/crates/strsim) crate would be useful for nice error messages ("Unknown option 'commad', did you mean 'command'?"). But that just would be a 'nice to have', nothing essential.

Thanks, for creating `cargo make`!

**Comment by sagiegurari** [comment]
that is super interesting idea.
I will check what can be done (I will check serde docs).
by the way, PRs are always welcome as well :)

**Comment by d4h0** [comment]
Sounds good :)

Serde has the [`deny_unknown_fields` attribute](https://serde.rs/container-attrs.html#deny_unknown_fields) (`#[serde(deny_unknown_fields)]`), which might be useful. But I'm not sure if that would work with the feature set that `cargo make` has.

**Comment by sagiegurari** [comment]
thanks. the issue i see with that attribute is that its not something i can turn on/off when running deserialize.
its impacting always.

**Comment by sagiegurari** [comment]
@d4h0 this one feels like a good direction to me: https://github.com/dtolnay/serde-ignored

**Comment by d4h0** [comment]
I didn't know `serde-ignored` – thanks! Yes, that looks perfect.

**Comment by sagiegurari** [comment]
@d4h0 this is now implemented in the dev branch 0.32.11
give it a shot and tell me what you think.
it will print a warning for any unknown key found including which file it was found in.

**Comment by d4h0** [comment]
@sagiegurari: Works fantastic – thank you so much!

**Comment by sagiegurari** [comment]
thanks for the feedback.

**Comment by sagiegurari** [comment]
officially released.

**Comment by d4h0** [comment]
@sagiegurari: Awesome, thanks again!
