### ISSUE TITLE
With 'on_error_task' config, user's command line arguments are not sent to the running task.

### ISSUE THREAD

**Issue by nook1208** [sagiegurari/cargo-make#511]
### Describe The Bug
If I use `on_error_task` config, user's command line arguments are not sent to the running task.
When I check the code, If `on_error_task` is enabled `run_protected_flow` function is executed.
And It seems to need some code that pass command line arguments of user to a task that will be run.

### To Reproduce

1. Add 'on_error_task' to Makefile.toml
2. Define any task(like cli-args in README.md) to print user's arguments in Makefile.toml
3. Run `cargo make cli-args arg1 arg2 arg3`

### Error Stack
```console
$ cargo make cli-args arg1 arg2 arg3
[cargo-make] INFO - cargo make 0.32.11
[cargo-make] INFO - Project: cargo_test
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: cli-args
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Execute Command: "cargo" "make" "--disable-check-for-updates" "--no-on-error" "--loglevel=info" "--profile=development" "--makefile" "/home/eom/share/git/cargo_test/Makefile.toml" "cli-args"
[cargo-make][1] INFO - Project: cargo_test
[cargo-make][1] INFO - Build File: /home/eom/share/git/cargo_test/Makefile.toml
[cargo-make][1] INFO - Task: cli-args
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Running Task: cli-args
args are:
[cargo-make][1] INFO - Build Done in 0 seconds.
[cargo-make] INFO - Build Done in 0 seconds.
```

### Code Sample
In Makefile.toml
```rust
[config]
on_error_task = "catch"

[tasks.cli-args]
script = "echo args are: ${@}"

[tasks.catch]
script = '''
echo "Doing cleanups in catch"
'''
```

**Comment by sagiegurari** [comment]
@nook1208 thanks a lot for reporting this. This should be fixed now.

**Comment by sagiegurari** [comment]
officially release now. thanks for the raising this issue

**Comment by nook1208** [comment]
Yeah, It's fixed. Thank you!
And I'm appreciate this great product :]
