### ISSUE TITLE
cargo-make build without local git repository fail

### ISSUE THREAD

**Issue by Gamadril** [sagiegurari/cargo-make#52]
#### Problem Description
cargo make fails on projects without git repository. Stripped down example below for getting the 128 error code.

#### Steps to reproduce
cargo new hello_cargo --bin --vcs none
cd hello_cargo
cargo make

#### Error Stack/Info (if any)
[cargo-make] INFO - cargo-make 0.9.0
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - External file not found, skipping.
[cargo-make] INFO - Setting Up Env.
**[cargo-make] ERROR - Error while executing command, exit code: 128**
[cargo-make] WARN - Build Failed.

**Comment by sagiegurari** [comment]
Thanks, you are right.
I'll fix it later today.

**Comment by sagiegurari** [comment]
This is fixed as part of 0.9.1 version which I now published.
Please tell me if it solves your issue.

**Comment by Gamadril** [comment]
Thanks, works now. Had another error about rustfmt not supporting the "force" argument, but after updating to v0.10.0 everything is working. Thanks again for quick response and the fix.

**Comment by enfipy** [comment]
I faced the same issue. Every command I wrote to Makefile.toml is ignored if I inside any folder other than root.

Is there any way to fix it?

**Comment by sagiegurari** [comment]
can you open a new issue with an example run and error?
did you look at [search_project_root](https://github.com/sagiegurari/cargo-make#cargo-make-global-config)?

**Comment by enfipy** [comment]
> can you open a new issue with an example run and error?
> did you look at [search_project_root](https://github.com/sagiegurari/cargo-make#cargo-make-global-config)?

The issue was with `warkspace`. Maybe it would be better to change log info for this kind of error?

**Comment by sagiegurari** [comment]
sorry, i still have no idea what error you are talking about or how you resolved it. i need more info/output/something
