### ISSUE TITLE
Support `version` in `install_crate`

### ISSUE THREAD

**Issue by ndarilek** [sagiegurari/cargo-make#544]
### Feature Description

Support specifying an exact version when installing a crate.

### Describe The Solution You'd Like

I'm trying to build a wasm app. I need an exact match between wasm-bindgen and wasm-bindgen-cli, and unfortunately a dependency requires the use of 0.2.69. `cargo install wasm-bindgen-cli --version 0.2.69` works, but it'd be nice to encode the version requirement in my Makefile.toml. Note that it can't be `min_version`, since the versions need to match exactly.

### Code Sample

```
[tasks.install-wasm-bindgen-cli]
install_crate = { crate_name = "wasm-bindgen-cli", version = "0.2.69", binary = "wasm-bindgen", test_arg = "--help" }
```

**Comment by sagiegurari** [comment]
makes sense. I'll check it out.
thanks for the idea.

**Comment by sagiegurari** [comment]
@ndarilek i just pushed a support for this in the 0.32.17 dev branch. can you verify it please?

**Comment by ndarilek** [comment]
Works here. Thanks!

**Comment by sagiegurari** [comment]
this is no officially released
