### ISSUE TITLE
Variable isn't being set, and docs are unclear

### ISSUE THREAD

**Issue by ndarilek** [sagiegurari/cargo-make#546]
### Describe The Bug

This is probably a misunderstanding on my part, but neither cargo-make or duckscript's docs helped here. I'm trying to use cargo-make to package my software for end users, and am building out platform-specific tasks to copy release artifacts into directories for zipping. I'm trying to set up a standard directory and add that to the environment, but unfortunately the variable is blank even though the components seem fine.

### To Reproduce

Here's my task:

```toml
[tasks.release-pre]
script_runner = "@duckscript"
script = '''
set dist_dir dist/${CARGO_MAKE_PROJECT_NAME}-${CARGO_MAKE_RUST_TARGET_OS}-${CARGO_MAKE_RUST_TARGET_ARCH}
echo ${CARGO_MAKE_PROJECT_NAME}
echo ${CARGO_MAKE_RUST_TARGET_OS}
echo ${CARGO_MAKE_RUST_TARGET_ARCH}
echo dist_dir = ${dist_dir}
mkdir ${dist_dir}
'''
```

My goal is to set it as a local variable, then push it into the environment so platform-specific scripts can use it later. I've tried various combinations of quoting, but nothing seems to get this right.

Thanks for any help.

**Comment by sagiegurari** [comment]
set is used to set a local variable. what you are looking for is [set_env](https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__env__SetVar)

so its basically:

```toml
[tasks.release-pre]
script_runner = "@duckscript"
script = '''
set dist_dir dist/${CARGO_MAKE_PROJECT_NAME}-${CARGO_MAKE_RUST_TARGET_OS}-${CARGO_MAKE_RUST_TARGET_ARCH}
echo ${CARGO_MAKE_PROJECT_NAME}
echo ${CARGO_MAKE_RUST_TARGET_OS}
echo ${CARGO_MAKE_RUST_TARGET_ARCH}
echo dist_dir = ${dist_dir}
mkdir ${dist_dir}

set_env dist_dir ${dist_dir}
'''
```

by default cargo-make loads all env vars also as local duckscript vars so its easy to access them, instead of doing get_env for each one.

**Comment by ndarilek** [comment]
Thanks for the confirmation, figured that was the difference between set 
and set_env, and that the environment variable may not be ready.


What I'm saying is that my output is:


[cargo-make] INFO - Running Task: release-pre
rampage
windows
x86_64
dist_dir =


Clearly I'm setting dist_dir wrong but I don't know how I'm messing it up.

**Comment by sagiegurari** [comment]
right sorry missed the wrong set usage.
in duckscript, the set returns the value so you need to do:

```sh
dist_dir = set dist/${CARGO_MAKE_PROJECT_NAME}-${CARGO_MAKE_RUST_TARGET_OS}-${CARGO_MAKE_RUST_TARGET_ARCH}
```

**Comment by ndarilek** [comment]
Perfect, thanks for the quick help!
