### ISSUE TITLE
Disabling default cargo make tasks when there are no toml files that it can run?

### ISSUE THREAD

**Issue by Ragarnoy** [sagiegurari/cargo-make#550]
I keep running into an annoying issue, people who try building my project will accidentally run `cargo make` when they're not in the folder where my Makefile.toml is, which causes cargo make to try to build the project incorrectly with its default task and run rustfmt on all my files.
Is this preventable somehow ?

**Comment by sagiegurari** [comment]
there is machine level config to make it search up for project root but won't help you i think.

can you explain better what project it is, and from where they are running it from?

**Comment by Ragarnoy** [comment]
On my project ( https://github.com/abassibe/Gomoku ), if the default configuration is ran, it will not run my Makefile.toml (that clears the default task https://github.com/abassibe/Gomoku/blob/0a79de7433c843da254f60e2153a448d3f9fd28b/Makefile.toml#L6 and checks for requirements)

It will run the default one instead despite me clearing it, which reformats the whole codebase and leads the user to think that they built the project correctly

**Comment by sagiegurari** [comment]
i didn't fully understand that project. the makefile is not in the mater, but on some commit?

anyway, if there is a directory that you want to disable default invocation, you could create a makefile like this

```toml
[config]
skip_core_tasks = true

[tasks.default]
clear = true
command = "echo"
args = ["cargo make must be invoked in project root folder"]
```

reason is that cargo-make runs without any file is because it comes bulit in with lots of tasks and the whole point is that its usable by projects without writing any makefile or doing anything special.
i hated the fact i copied my builds in every project i wrote and wanted something useful without any work per project.

**Comment by Ragarnoy** [comment]
It's on the `feature/flexbile_build` branch ( https://github.com/abassibe/Gomoku/blob/feature/flexible_build/Makefile.toml )

Isn't calling rustfmt every time a bit extreme though ? 
I didn't know about the skip core task variable, i'll try it out next time I'm working on this branch. I'll let you know how it goes.

**Comment by sagiegurari** [comment]
> Isn't calling rustfmt every time a bit extreme though ?

for me personally its important to make sure its formatted well always.
the perf of the formatter is awesome so i don't feel it as a bottleneck. the build is much worse :)

also you can configure the default task to do whatever you want and you can disable it.
default tasks are there to give a nice quick headstart for your project, but they are not mandatory.
