### ISSUE TITLE
Random name generated for @rust tasks results in non_snake_case warning

### ISSUE THREAD

**Issue by pheki** [sagiegurari/cargo-make#551]
### Describe The Bug

When any @rust script is run (at least with `rust-script`), a `.rs` file name is generated with mixed case letters. This name is then used by `rust-script` for the crate name, which makes cargo emit a non_snake_case warning.

`Makefile.toml` used:

```toml
[config]
skip_core_tasks = true

[tasks.rust-script]
script_runner = "@rust"
script = """
fn main() {
    println!("test");
}
"""
```

Output (with path slightly changed):

```console
$ cargo make rust-script
[cargo-make] INFO - cargo make 0.32.17
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: rust-script
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: rust-script
[cargo-make] INFO - Execute Command: "rust-script" "/path/to/tmp/file/xIL5ulxZRK.rs"
warning: crate `xIL5ulxZRK_684b1228c0599821340f3fc3` should have a snake case name
  |
  = note: `#[warn(non_snake_case)]` on by default
  = help: convert the identifier to snake case: `x_il5ulx_zrk_684b1228c0599821340f3fc3`

warning: 1 warning emitted

test
[cargo-make] INFO - Build Done in 1.07 seconds.
```

### To Reproduce
Create the Makefile.toml above and run `cargo make rust-script` in the directory.

### Error Stack

No actual error

### Code Sample

See above

### Workaround

`#![allow(non_snake_case)]` can be added to the script to ignore the warning.

**Comment by sagiegurari** [comment]
@pheki agree its annoying.
why not fix it in the source? meaning in [rust-script](https://github.com/fornwall/rust-script) instead of a workaround in cargo-make?

**Comment by pheki** [comment]
I've opened an issue in rust-script to gather their opinion on the matter

**Comment by pheki** [comment]
I've sent a PR to fix their issue, so that the characters are now converted to lowercase. This will be fixed by updating `rust-script` whenever it is released (or installing from git).

Thanks!

**Comment by sagiegurari** [comment]
thanks :)

**Comment by sagiegurari** [comment]
@pheki i also validated it and it works great. thanks a lot for the help :)

**Comment by pheki** [comment]
:) always glad to help!
