### ISSUE TITLE
[FR] A script_file key for running external scripts using path

### ISSUE THREAD

**Issue by ajeetdsouza** [sagiegurari/cargo-make#553]
Hey, thanks for this incredible tool!

Currently, the `script` key uses a multi-line string for running external scripts, such as `@rust` or `@shell`. It would be nice if I could specify the path to the script instead. That way, I can make use of syntax highlighting, linting, IDE support etc, which is not available when writing in a TOML string.

**Comment by sagiegurari** [comment]
thanks a lot.
you can do the following:

```toml
script = { file = "script.sh" }
```

just fyi, for syntax, i use neovim with cargo-make plugin so i get syntax highlighting in these blocks as well :)

**Comment by ajeetdsouza** [comment]
Oh, sorry - I missed that when going over the README. Thanks a lot!

I don't use Neovim, unfortunately, but a VS Code plugin for this would be great to have!
