### ISSUE TITLE
`CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY` is canonicalized with the `\\?\` prefix

### ISSUE THREAD

**Issue by WilliamVenner** [sagiegurari/cargo-make#561]
### Describe The Bug
Unfortunately, something very annoying about Rust's `std::fs::canonicalize` is that on Windows, it prefixes `\\?\` to the path.

https://stackoverflow.com/a/21194605/7471684

Whilst this is all up to spec, and theoretically is correct, annoyingly A LOT of programs, commands, etc on Windows do not support this prefix. `robocopy`, `xcopy` are two culprits.

I'm sure there may be other environment variables that Cargo Make sets which have this problem.

There is a crate that works around this problem: https://docs.rs/dunce/1.0.1/dunce/

### To Reproduce
Use `CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY` on Windows

**Comment by sagiegurari** [comment]
ya, i know of that issue. i fixed it for cwd env var i setup.
this env var is minor so forgot about it, but I'll fix it as well. no need for extra crate, it's basically just removing that prefix, if i remember correctly

**Comment by WilliamVenner** [comment]
I did try and tackle the issue; I found that https://github.com/sagiegurari/cargo-make/blob/e47e3e949b41d8f3839fe57e24f8dd0affa4ecac/src/lib/environment/mod.rs#L564 caused my path to fallback to a `.` somehow:

![image](https://user-images.githubusercontent.com/14863743/120656998-fed00800-c47b-11eb-866f-bb092cf72b13.png)

**Comment by sagiegurari** [comment]
if you can help with this an provide a PR, that would be awesome. i personally don't have a windows machine.
so I'm usually doing guess work :)

**Comment by WilliamVenner** [comment]
My working solution does make use of the dunce crate - for consistency I removed the unc prefix stripper and respective tests. It's a bit of a cowboy move but the dunce crate should guarantee the correct behaviour.
