### ISSUE TITLE
Shell completions

### ISSUE THREAD

**Issue by simlay** [sagiegurari/cargo-make#565]
### Feature Description

Hi there! Love this project!

Been using this project for a while and the only thing I wish it had is shell completions. I have no idea how hard this feature would be to implement. I'm partially writing this task because it's not been written so others can see that it was at least talked about and maybe someone (or me) would do the work if you're interested in the PR(s).

### Describe The Solution You'd Like

I'd put something like `source <(cargo make completions bash)` (I know this may not be the right way to do it) in my bash profile and then have tab completions.

This should also work with act the same for things like `zsh` or other shells.

**Comment by sagiegurari** [comment]
awesome suggestion.
i already have a cli command to list all tasks that are found/relevant.
so i could use it to build the completion script.

I'll probably take a look on building this for bash, and let others use it as reference to build it to other shells (which I don't use)

the only thing I'm not sure about, is that i could probably make it work for the makers executable, but not cargo make (they are the same) since its a sub command of another executable.
but, I'm not an expert on that and might be wrong.

**Comment by sagiegurari** [comment]
by the way, if you want to take a shot at it and submit a PR, that would be even better. just tell me.
i can guide you if needed.

**Comment by sagiegurari** [comment]
@simlay I've implemented a bash auto complete for makers in 0.34.1 branch.
you will have to install the new cargo-make for it (contains simplified output for list tasks command) + source the new file in the extra/shell folder.
it would take a bit to run it as it calls cargo make to pull all task names that are actually available for you to use.

any feedback and suggestions are welcome.

**Comment by sagiegurari** [comment]
@simlay did you have a chance to look at it?

**Comment by sagiegurari** [comment]
released in official version

**Comment by sassman** [comment]
In the docs it is written to 

```
source ./extra/shell/makers-completion.bash
```

However it seems that the `extra` folder is not packaged as part of the crate, so it would not appear at `~/.cargo` e.g. under `~/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-make-0.36.0/`

The most simplest fix for this would be to include the `extra` folder in the `Cargo.toml` in the `include` section.

**Comment by sagiegurari** [comment]
didnt think someone would search it there....
in my mind people would do clone, source the file and delete

**Comment by sassman** [comment]
> didnt think someone would search it there....
> in my mind people would do clone, source the file and delete

That's also an option. But since the code is already locally available after a cargo install it would be way more convenient to not have to clone the repo and rather reuse the local available crate code, specifically also the shell completion script.

**Comment by sagiegurari** [comment]
cool. feel free to PR this if you want, or open a new issue so i can track and do it

**Comment by sagiegurari** [comment]
@sassman i've added it. currently not published, only in dev branch.

**Comment by sassman** [comment]
Thanks, I was about to create the PR but thanks for the very fast help.

Maybe it's worth to mentioning the approach in the docs? Then I could prepare this PR, if you don't mind.

**Comment by sagiegurari** [comment]
you can PR the documentation, since i already pushed the cargo.toml change.
if you do, the doc is in the content.md that is the source of the readme.md
