### ISSUE TITLE
Typo in env var of default workflow

### ISSUE THREAD

**Issue by dbanty** [sagiegurari/cargo-make#566]
### Describe The Bug
In the default Rust workflow, an environment variable is spelled incorrectly. It is defined as `CARGO_MAKE_TEST_USE_MUTLI_TEST_PHASES` (mutli instead of multi). Unfortunately fixing it is probably going to break some folks' workflows if they have that defined to use `test-custom` (like I do).

https://github.com/sagiegurari/cargo-make/blob/4e824ad95a105932fe20c7e2af702a4da8a1429f/src/lib/descriptor/makefiles/rust.toml#L443

**Comment by sagiegurari** [comment]
oh man. i'll fix it but also define the old env var as well to default to the new var (if undefined) or to update the new var (if defined).
that way it won't break anyones stuff. but i'll have to think how to do it the best way....
thanks a lot for reporting it

**Comment by sagiegurari** [comment]
@dbanty i've pushed a fix to the dev branch.
basically at the start, before running any task, it will run an env migration task with the logic i stated before.
it will warn if an old env was defined in the global env block.
it will not fix your env, if you defined it in the task level.

**Comment by dbanty** [comment]
Great, thanks for the quick response!

**Comment by sagiegurari** [comment]
released in official version
