### ISSUE TITLE
example cross complie

### ISSUE THREAD

**Issue by x37v** [sagiegurari/cargo-make#570]
### Feature Description

I'd like to compile for a variety of other platforms, on either osx or linux.

I see this in the enviroment variable documentation:
```
CARGO_MAKE_RUST_TARGET_ARCH - x86, x86_64, arm, etc ... (see rust cfg feature)
CARGO_MAKE_RUST_TARGET_ENV - gnu, msvc, etc ... (see rust cfg feature)
CARGO_MAKE_RUST_TARGET_OS - windows, macos, ios, linux, android, etc ... (see rust cfg feature)
```

but I'm not sure where the `rust cfg feature` is... with cargo i can just specify `cargo build --target aarch64-apple-darwin` for instance, and it looks like I have full control over the `cargo build` arguments in `cargo-make` but I'm wondering what the best approach is for supplying the information on the `cargo make` command line and getting the appropriate environment variables filled in.

### Describe The Solution You'd Like

A nice example of how to do this.

### Code Sample

```rust
cargo make --target aarch64-apple-darwin
```

**Comment by sagiegurari** [comment]
i think you got those backwards :)
those env vars are to be read, not to be set by you. cargo-make sets them based on your rust setup.
if you want to target a different arch, you need to update the build task to include the needed args, or use a task that calls cross for example.

for example:

```toml
[tasks.build]
args = [
  "build",
  "--release",
  "--all-features",
  "--target",
  "${@}",
]
```

than you can call it like this:

```sh
cargo make build aarch64-apple-darwin
```

**Comment by x37v** [comment]
Okay, that makes sense. I have a number of settings that I base on environment variables to determine, for instance, a dylib suffix or replacement.. I guess I can just default based on the default os and architecture but then override if I want to cross compile.

Jul 17, 2021 8:06:43 AM Sagie Gur-Ari ***@***.***>:
