### ISSUE TITLE
condition_script not failing if the script exits non-zero

### ISSUE THREAD

**Issue by edmorley** [sagiegurari/cargo-make#583]
### Describe The Bug
The cargo-make docs describe using `condition_script` along with `condition` + `fail_message` to run a script and fail with an error message if it doesn't pass. However trying the example from the docs doesn't result in a failure, or the error message being printed, which seems like a bug.

Docs:
https://sagiegurari.github.io/cargo-make/#usage-conditions-script

### To Reproduce
1. `cargo new testcase-cargo-make`
2. Create a `Makefile.toml` with contents shown below.
3. `cargo make test-condition-script-with-message`

```toml
# Makefile.toml
[tasks.test-condition-script-with-message]
condition = { fail_message = "Condition Script Failed." }
condition_script = [
    "exit 1"
]
command = "echo"
args = ["condition was met"]
```

### Expected
The cargo make command exits non-zero, with the "Condition Script Failed" message visible in the output.

### Actual

```
$ cargo make test-condition-script-with-message
[cargo-make] INFO - cargo make 0.35.0
[cargo-make] INFO - Project: testcase-cargo-make
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: test-condition-script-with-message
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Build Done in 0.04 seconds.
$ echo $?
0
```

### Versions

```
$ cargo --version
cargo 1.54.0 (5ae8d74b3 2021-06-22)

$ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/emorley/.rustup

installed targets for active toolchain
--------------------------------------

x86_64-apple-darwin
x86_64-unknown-linux-musl

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.54.0 (a178d0322 2021-07-26)
```

**Comment by edmorley** [comment]
Oh, using `--verbose`, I see:

```
[cargo-make] VERBOSE - Skipping Task: test-condition-script-with-message Condition Script Failed.
```

So I guess:
(a) it is being run - just no output shown (which is counter-intuitive, given `fail_message` suggests there is a purpose to setting the message?)
(b) conditions are not mean to be fatal

Now (b) isn't a bug (just a design decision), however I wonder for (a) whether the message should always be shown even without `--verbose`, if someone has set a custom `fail_message`?

**Comment by sagiegurari** [comment]
there have been complaints every now and than that there is too much console output.
so i have moved this one by default to verbose.
however, there is a way to control it, just add the following:

```toml
[config]
reduce_output = false
```

I'll definitely need to update the docs with this one.

**Comment by sagiegurari** [comment]
also, ya conditions are not fatal. if you exit 1 it means condition failed and task is skipped. it doesn't mean task failed.

**Comment by edmorley** [comment]
It does make sense that a conditional task wouldn't be fatal - not sure why I thought that.
Perhaps it was because the option is named `fail_message` rather than say `skip_message`?

I wonder if one way to make this clearer would be to change the example from:
```
condition = { fail_message = "Condition Script Failed." }
```

...to:
```
condition = { fail_message = "Condition Script Failed - Skipping Task." }
```

**Comment by sagiegurari** [comment]
@edmorley not sure it would be clearer as the " Skipping Task." is already automatically printed so they would see it twice.

**Comment by edmorley** [comment]
The "Skipping task" message is not printed by default (new users aren't likely to know about or use `reduce_output = false`).

The reason for adjusting the example, was less about the message that gets printed, and more about how a user understands the example when reading it through as part of the docs.

**Comment by sagiegurari** [comment]
ya, i just updated the docs (in the dev branch) to reflect the needed config changes
