### ISSUE TITLE
Update coverage pattern requirements

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#59]
* support user level configuration to allow user level pattern instead of internal to include/exclude tests
* exclude binaries with same name as crate name

Based on comments in #44

**Comment by sagiegurari** [comment]
release new version with the changes from pr #60 with slight changes and fixes.
@azriel91 please pay attention that I changed the env var name a bit and how it is defined by default (using FS crate name).

**Comment by azriel91** [comment]
Cool thank you! :tada:
