### ISSUE TITLE
Unable to specify the exact version of one crate

### ISSUE THREAD

**Issue by lnshi** [sagiegurari/cargo-make#612]
### Describe The Bug

I followed the instruction in the README.md: [here](https://github.com/sagiegurari/cargo-make#defining-version), and tried to specify a specific version of `rustfmt` by doing:
```
[tasks.fmt]
install_crate = { crate_name = "rustfmt", binary = "rustfmt", version = "1.4.38", test_arg = "--help" }
command = "cargo"
args = ["fmt", "--all", "--manifest-path=rsmain/Cargo.toml"]
```

but result in the below warning, and still the installed old version of `rustfmt` is used:
```
[cargo-make] INFO - cargo make 0.35.6
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: fmt
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] WARN - Unable to read currently installed version for crate: rustfmt
[cargo-make] INFO - Execute Command: "cargo" "fmt" "--all" "--manifest-path=rsmain/Cargo.toml"
[cargo-make] INFO - Build Done in 2.21 seconds.
```

But in the same console if i do `rustfmt --version` i got `rustfmt 1.4.37-stable (59eed8a2 2021-11-01)` correctly, no idea what the WARN is complaining.

### To Reproduce

Just create a default Makefile.toml and copy in the above task definition and run.

Wha am i missing? How should i make sure the version i want get installed?

**Comment by sagiegurari** [comment]
thanks for notifying me. i'll check it out.

**Comment by sagiegurari** [comment]
@lnshi the reason it didn't work for you is that rustfmt is installed from rustup which seems not to update the .crates.toml which i use to find the version.
I'm going to add an additional check using the --version cli command to find out of those type of crates.
however, in your specific use case, it won't help, because i think rustfmt installation instructions do not talk about simple cargo install. so maybe it will solve your issue, maybe it won't.

**Comment by sagiegurari** [comment]
@lnshi you can try out the dev branch 0.35.7 which now has the fix for this.
would love your feedback to understand if it starts up the cargo install.

**Comment by lnshi** [comment]
@sagiegurari thanks for the quick response, i will try it out

**Comment by sagiegurari** [comment]
@lnshi this is now officially released. if you still face issues, feel free to open a new issue.
