### ISSUE TITLE
Task quits in the middle of a script. 

### ISSUE THREAD

**Issue by MikeWallaceDev** [sagiegurari/cargo-make#625]
### Describe The Bug
I have a main task which calls the task shown below (generate-language-files), and then a second second task (not shown).For some reason half of the first script is run, and then it returns without running the second half, and the second script (flutter-build) starts.

[tasks.generate_language_files]
script = [
  """
  cd app_flowy/ 
  flutter clean
  flutter pub get
  flutter pub run easy_localization:generate -S assets/translations/
  flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart -S assets/translations  
  """,
]
script_runner = "@shell"

![image](https://user-images.githubusercontent.com/5375835/150248441-101d7ff3-2512-40e7-b55a-af4a25a1d5fc.png)

Please note that I have also asked a [question on StackOverflow](https://stackoverflow.com/questions/70779672/why-does-my-cargo-make-task-return-half-way-through), but somehow I think this is more likely a bug.

### Error Stack
There are no errors printed out. No exit errors.

### Code Sample
See above

**Comment by sagiegurari** [comment]
with this amount of details, its really hard for me to know what is going on.
since it involves flutter and some repo, i can't just repo it. i don't have any windows machine, but i would have tried on linux if you gave me enough info.
with these details all i can say
1. try moving away from scripts and to commands. 1 command per task. in general i always favor commands since i can do lots of tricks there that i can't in scripts.
2. if you really want a script, but want to debug this better, move to duckscript. you can keep the script almost the same.
i guess cd would be -> cd ./app_flowy/ (add the ./) and invoking flutter would require prefix of 'exec --fail-on-error'
and change ```@shell``` to ```@duckscript``` and maybe we will have more details.

**Comment by MikeWallaceDev** [comment]
Hello, thanks for your quick reply.

Indeed, my partner on the night shift discovered that this script does not work as is, but rather needs to be duckscript : 


[tasks.generate_language_files.windows]
script_runner = "@duckscript"
script = [
  '''
  cd app_flowy
  exec cmd.exe /c flutter clean
  exec cmd.exe /c flutter pub get
  exec cmd.exe /c flutter pub run easy_localization:generate -S assets/translations/
  exec cmd.exe /c flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart -S assets/translations
  '''
]

We got it to work, thank you.  I must say that I didn't find it evident that this script wouldn't work. Lots of time wasted. It would be good if the documentation could be updated to better reflect this limitation.

Thanks again :)

**Comment by sagiegurari** [comment]
@MikeWallaceDev i'm not sure what limitation there is. i can't debug your script.
duckscript is just an idea to have a better shell env that is much more stable than cmd.
also
1. why exec cmd.exe /c <command> and not exec <command>? if you do it as i suggested, it would work (same script) for windows and other OS. is flutter a script so it can't find it without cmd.exe?
2. you should add exec --fail-on-error or an error will just print and not kill the task.

**Comment by MikeWallaceDev** [comment]
Hello @sagiegurari ,
The limitation is that for some reason the script would quit halfway.  I can't say why it quit thought, because there was no error or anything.

1. Why? Cause that's what my colleague used, so I just copied it. If you are saying that your way will be cross platform, then obviously that's a better idea. I'll try that.

1.5  What I would REALLY like to do is call a script from a task.  We already have those calls in a script that needs to be called from elsewhere, and now we are just duplicating the calls in a script and in a cargo task.  Is it possible to call a script? (I tried yesterday and it didn't work. )

2.  Yesterday I had added the ignore-error (or whatever it's called) to the task. That did nothing, the commands don't have an error.

**Comment by MikeWallaceDev** [comment]
So I tried it your way : 
[tasks.generate_language_files]
script_runner = "@duckscript"
script = [
  '''
  cd ./app_flowy/
  exec --fail-on-error flutter clean
  exec --fail-on-error flutter pub get
  '''
]
and it didn't work. "Error, program not found".  The same script did work on Linux.  I think you may have been right in thinking that it's because "flutter" is a script. I have no clue why it would find a binary, but not a script. The script is in the path.

**Comment by sagiegurari** [comment]
feels like the flutter script is the problem. no limitation to document on cargo-make side that i can see.
the cmd and --fail-on-error are not related by the way, and i suggest to keep the flag.
the ignore_error is a task level flag which is not related.
if you are going with a windows only version, i think you can do something simpler, but it doesn't matter.

**Comment by MikeWallaceDev** [comment]
Thank you very much for you help. I used all of your information to make it work, and everything is great now.  I hope that I didn't come off too asshole'ish, I was just tired. Apologies if that is the case :)

Have a great weekend!
