### ISSUE TITLE
env_files + additional_profiles = unexpected behaviour

### ISSUE THREAD

**Issue by Justice4Joffrey** [sagiegurari/cargo-make#626]
### Describe The Bug
When an env_file for a custom profile exists, it is loaded regardless of profile, presumably in relation to its order in the array.

### To Reproduce
https://github.com/Justice4Joffrey/cargo-make-bug

```
>>> cargo make -p production echo                                                                                                                                              13:41:18
[cargo-make] INFO - cargo make 0.35.8
[cargo-make] INFO - Project: xxx
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: echo
[cargo-make] INFO - Profile: production
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "echo" "trace"
trace
[cargo-make] INFO - Build Done in 0.43 seconds.
```
Uses production profile, but `RUST_LOG=info` in `./etc/prod.env`.

EDIT: I can avoid the `local.env` being loaded by putting it first in the list.

**Comment by Justice4Joffrey** [comment]
I see - I think this is a misunderstanding on my part. I was expecting `additional_profiles` to be where I specify custom 'valid' profiles. Turns out that's not the case, this is (I think) how I can specify to load multiple profiles at runtime regardless of what profile I've loaded with `--profile`.

Looking back at the docs, it is a touch ambiguous how `additional_profiles` works.

> Additional` profiles can be used to define additional environment blocks and they will be defined in a new environment variable CARGO_MAKE_ADDITIONAL_PROFILES

I think I read this as, in order to say -

```
[env.local]
FOO=value
```

I would have to define "local" in `additional_profiles`. But it turns out that would make the "local" env _always_ run.

Thanks for getting back so promptly on this, and for a super useful library.

**Comment by sagiegurari** [comment]
no problem. i'm happy to get a doc PR if you wish to improve that section (in the content.md) to make it clearer.

**Comment by Justice4Joffrey** [comment]
Sure - #633
