### ISSUE TITLE
Support modifying environment from Rust scripts

### ISSUE THREAD

**Issue by ndarilek** [sagiegurari/cargo-make#629]
### Feature Description

Not sure if this exists already, but I'd like some way for Rust scripts to modify the environment

### Describe The Solution You'd Like

Not sure what the best way to handle this is. I wonder if the environment can be reread and changed after executing a Rust script, in case the script added new variables intended to be available later on in the pipeline? Or maybe scripts can `println!` environment changes that the makefile picks up?

### Code Sample

Here's an example build task:

```
[tasks.changes]
script_runner = "@rust"
script = '''
//! ```cargo
//! [dependencies]
//! regex = "1"
//! ```
use std::{env, fs};

use regex::Regex;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let readme = fs::read_to_string("README.md")?;
    let changes = Regex::new(r"### Version (?P<version>.+)\n\n(?P<changes>(?s:.+?))\n\n")?;
    if let Some(captures) = changes.captures(&readme) {
        if let Some(changes) = captures.name("changes") {
            let changes = changes.as_str();
            env::set_var("changes", changes);
        }
    }
    Ok(())
}
'''
```

This parses my README and naively tries adding the most recent changelog changes to the environment. Next I do:

```
[tasks.changes2]
dependencies = ["changes"]
script_runner = "@duckscript"
script = '''
echo In script
echo ${changes}
'''
```

But either I'm doing something wrong or, as I suspect, the environment can't be changed from a Rust script like this.

If there's another way to achieve this then please let me know. Thanks!

**Comment by ndarilek** [comment]
I looked at duckscript, and it seems there's no regexp-matching. Is that 
correct?

If so, I'm not sure how any new capability using it will help me here, 
though maybe I'm misreading your comment or mistaken on the regexp/more 
complex pattern-matching.

Thanks.

**Comment by sagiegurari** [comment]
adding more commands to duckscript isnt that hard and than its available to cargo make.

**Comment by sagiegurari** [comment]
@ndarilek i just published an example how to create a task and plugin to invoke it which sets the env for the parent cargo make process.
hope it helps

**Comment by sagiegurari** [comment]
@ndarilek did it help? did you checkout my example?

**Comment by ndarilek** [comment]
Sorry. I will check it out today and report back.

**Comment by sagiegurari** [comment]
A solution was provided. i think we can close this one.

**Comment by wmmc88** [comment]
It seems that your plugin example has some limitations since plugins don't seem to be supported everywhere. From my understanding of the docs, `env_scripts` do not support plugins, so if i wanted an `env_scripts` script to modify the env with a `rust-script`, I would have to use `duckscript` in the `env_scripts` script to invoke a task that has the actual `rust-script` with the rust-env `plugin`

**Comment by sagiegurari** [comment]
@wmmc88 what you could so is
1. implement the init task - that task is called at the start of every flow and you can define a custom name via config
https://github.com/sagiegurari/cargo-make#usage-init-end-tasks
2. init task would trigger the duckscript code or plugin to setup the env before any other task starts

there are a lot of other ways to define the env without plugin/task as you know. via cli, env block, env script but to do it via task/plugin can only happen once tasks are loaded and starting. and for that you have the init task always invoked.
