### ISSUE TITLE
Support bash source

### ISSUE THREAD

**Issue by janosimas** [sagiegurari/cargo-make#632]
### Feature Description
Allow using a script file to setup the environment, like the `source` command in bash.

### Describe The Solution You'd Like
I think the ideal solution would be to support something like:
```
env_scripts = [
    { file = "shell/env" }
]
```

### Context
I already have a bash environment script defined by the project.
I use `cargo-make` for my personal setup.

**Comment by sagiegurari** [comment]
unfortunately bash scripts are invoked as child processes so they can't change the parent process env.
there are 2 alternatives
1. env files - https://github.com/sagiegurari/cargo-make#usage-env-file
2. duckscript scripts - those run in parent process and can modify its env (i explain it a bit in the section you probably read - https://github.com/sagiegurari/cargo-make#env-setup-scripts)

in order to support bash changing the parent process env, i'll have to basically embed bash in cargo-make which i think is something i can't manage.

**Comment by janosimas** [comment]
Thanks for the quick reply.

I saw those approaches but they are not ideal in my case because I already have an official setup script.
It's not a simple script and duplicating would also mean keeping it up to date with any changes.

I'll think about this and see if I come with an idea.

**Comment by sagiegurari** [comment]
so what you could do is
1. the bash script can accept a 'verbose' flag
2. if flag is provided, bash script will printout the needed env vars at the end of execution
3. call the bash script via duckscript with the flag
4. parse the output in duckscript and set the env

this is very similar to an example i wrote about having a rust script modify the cargo-make env.
that example is using a plugin for a task, but the general concept is the same.
https://github.com/sagiegurari/cargo-make#usage-plugins-plugin-example-rustenv

**Comment by janosimas** [comment]
It's not an ideal solution but would it be possible to make a diff of the environment variables and set as `env`?

It would still loose bash defined functions but it's a compromise.

**Comment by janosimas** [comment]
I had the page open and didn't see your comment.

**Comment by sagiegurari** [comment]
did it solve your issue?

**Comment by sagiegurari** [comment]
@janosimas did it resolve your issue?

**Comment by janosimas** [comment]
I'll have to investigate more, I don't think I'll be able to work on this in the next weeks.

**Comment by janosimas** [comment]
This will be a lot of effort in my case.

I'll still but I'll close the issue as it is not solvable.

**Comment by sagiegurari** [comment]
> This will be a lot of effort in my case.

i gave a simple example to look at
