### ISSUE TITLE
`cargo make` hangs if there is a bad internet connection

### ISSUE THREAD

**Issue by sffc** [sagiegurari/cargo-make#639]
### Describe The Bug

Running `cargo make` when the internet connection is weak (e.g., long ping time / lost packets) causes the command to hang for an indefinite amount of time.

### Suggested Fix

1. Add a command-line flag to `cargo make` to prevent it from phoning home to check for updates.
2. If the request hangs for more than ~3 seconds, skip the update check.

**Comment by sagiegurari** [comment]
by default, updates are checked no more than once per week and you can turn it off via configuration:
https://github.com/sagiegurari/cargo-make#cargo-make-global-config
or via cli --disable-check-for-updates param

however, there are many other things that cause network checks for example if you invoke some cargo plugin, and its not there i install it.

**Comment by sagiegurari** [comment]
@sffc did you check the disabling the update via config/cli?

**Comment by sagiegurari** [comment]
closing due to lack of feedback and existing config
