### ISSUE TITLE
`cargo install cargo-make` fails

### ISSUE THREAD

**Issue by gilescope** [sagiegurari/cargo-make#645]
I get the following when trying to install:

```
error: failed to run custom build command for `openssl-sys v0.9.72`
```

The bug seems to be that it's not using the pure rust `rustls` by default. If it did then it would just install and not complain that it can't find some dodgy c library.

**Comment by sagiegurari** [comment]
@gilescope thanks for the feedback.
you could try ```cargo install --no-default-features --force cargo-make``` for simpler no tls installation or even simpler just download the precompiled binaries available in the release tab.

when using tls, i'm using the openssl dependency (well... not directly, via duckscript with attohttpc which is http client, see #614) and i'm not sure its considered 'dodgy' as it is very common lib used by many rust (and non rust) libraries/binaries.
however, if you feel there is a better way to set that up, a PR on the duckscript repo would really be helpful :)

**Comment by sagiegurari** [comment]
@gilescope did you check the options I detailed?

**Comment by sagiegurari** [comment]
closing due to lack of feedback and existing solutions
