### ISSUE TITLE
Logging of script lines de-synced from script output

### ISSUE THREAD

**Issue by mightyiam** [sagiegurari/cargo-make#655]
### Describe The Bug

I wouldn't expect to see [this line](https://github.com/mobusoperandi/michie/runs/6372140047?check_suite_focus=true#step:6:116) where I see it.

I'm hoping there's no need for a reproduction... But if the cause of this issue is not immediately apparent to you then well I guess I could come up with one.

**Comment by sagiegurari** [comment]
logging of script lines in linux/mac is done via bash built in flags.
cargo-make doesn't output it on it's own.

**Comment by mightyiam** [comment]
```
Message - "foo bar\n\n"
	X - Commit title does not comply with the Conventional Commits V1.0.0 specification.
+ exit_code=1
	X - Commit title does not use an Angular type.
```

line 3 is in between lines that are from a process that I expect to already have exited before the code in line 3 is executed.

That means line 4 is from a process that had exited before the code in line 3 had executed.

Does this provide a good enough clue for what could be the cause or do we need a reproduction?

**Comment by mightyiam** [comment]
Yes, it was in GitHub Actions. And their log web UX has some issues. I didn't realize that it's that serious, though. Ordering is kind of important.
