### ISSUE TITLE
Workaround to install on illumos

### ISSUE THREAD

**Issue by Toasterson** [sagiegurari/cargo-make#657]
### Describe The Bug
This crate cannot be installed on illumos

### To Reproduce
On any illumos machine
```bash
cargo install cargo-make
```

### Workaround
- Clone this repo locally
- cd into repo
- Add the following patch
```patch
diff --git a/Cargo.toml b/Cargo.toml
index cd123d4d..242d6ad2 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -82,3 +82,6 @@ default = ["tls"]
 branch = "master"
 repository = "sagiegurari/cargo-make"
 service = "github"
+
+[patch.crates-io]
+users = { git = 'https://github.com/papertigers/rust-users.git', branch = "illumos" }
````
- Install with `cargo install --path ./`

### PR Link
ogham/rust-users#49

**Comment by sagiegurari** [comment]
@Toasterson with the new fsio release, is this patch still needed to make cargo-make install and work on illumos?

**Comment by Toasterson** [comment]
Yes, tested with fsio v0.3.1 and the patch can be removed.
