### ISSUE TITLE
Default environment variable

### ISSUE THREAD

**Issue by jingzhaoou** [sagiegurari/cargo-make#666]
### Feature Description

In Makefile, I can do 
```
AN_OPTION ?= default_value
```
That is, if user does not define `AN_OPTION`, default its value to `default_value`. I searched for a while and don't see any solution how to achieve such behavior with `cargo make`. 

I think I can implement this through env scripts. However, I am curious if there are any better solutions. Thanks a lot!

**Comment by sagiegurari** [comment]
PREFER_EXISTING = { value = "new", condition = { env_not_set = ["PREFER_EXISTING"] } }

**Comment by jingzhaoou** [comment]
Wow, that is exactly what I am looking for. I highly recommend to add that to the document. More than happy to help out the `cargo make` project whenever possible. I am using it daily since I found it two weeks ago.

**Comment by sagiegurari** [comment]
i actually copied it from the documentation :)
