### ISSUE TITLE
Missing Cargo.lock in the repository / release tarballs

### ISSUE THREAD

**Issue by jirutka** [sagiegurari/cargo-make#670]
Please include `Cargo.lock` in the repository and keep it up-to-date when releasing new versions. It’s important for (linux) distributions to ensure reproducible builds.

**Comment by sagiegurari** [comment]
I'm not sure cargo-make is packaged by any linux dist. could be wrong.

**Comment by jirutka** [comment]
You are wrong… https://repology.org/project/cargo-make/versions. ;) And I’m currently packaging it for Alpine Linux.

**Comment by sagiegurari** [comment]
oh wow. nice. any chance you can also do some PR to update the docs and put some installation instructions using package managers for relevant dists?

**Comment by sagiegurari** [comment]
this is now officially released
