### ISSUE TITLE
warning: the following packages contain code that will be rejected by a future version of Rust: winapi v0.2.8

### ISSUE THREAD

**Issue by frederikhors** [sagiegurari/cargo-make#676]
Installing it on Windows with `cargo install cargo-make` it works but prints this warning:

```
warning: the following packages contain code that will be rejected by a future version of Rust: winapi v0.2.8
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

**Comment by sagiegurari** [comment]
I don't use that directly. what rust version do you use?

**Comment by frederikhors** [comment]
```
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: The currently active `rustc` version is `rustc 1.62.1 (e092d0b6b 2022-07-16)`
```

**Comment by sagiegurari** [comment]
@frederikhors this is due to the ftp crate i'm using in duckscript for ftp commands.
the project feels abandoned, so I'll probably move to another crate. maybe suppaftp

**Comment by sagiegurari** [comment]
@frederikhors this should be resolved now. i can't be 100% sure since i don't have windows, but i believe based on the signals i'm seeing. if its not, feel free to reopen.

**Comment by frederikhors** [comment]
I can confirm it works now.

**Comment by sagiegurari** [comment]
thanks
