### ISSUE TITLE
[FR] Reduce logs info

### ISSUE THREAD

**Issue by frederikhors** [sagiegurari/cargo-make#678]
Is there a way to remove all the messages like these below?

```
[cargo-make] INFO - makers 0.35.15
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: start
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: start
```

**Comment by sagiegurari** [comment]
you can change to err logs using the quite flag or loglevel flag. even change the default log level via machine level config.

**Comment by frederikhors** [comment]
Thanks, I tried and `--quiet` works.

But since I would like to use makers every day to perform routine operations calling it by hand in the terminal I would like to avoid using that flag every time.

What do you think of a config like this?

```toml
[config]
log_level = "error"
```

Obviously it would be a low priority config because it would then be overridden by the other methods of changing the log level.

**Comment by sagiegurari** [comment]
no, that would be too late since cargo-make loads and prints before it loads the toml file.
like i wrote, you can configure it in machine level via log_level flag.
See: https://github.com/sagiegurari/cargo-make#cargo-make-global-config

**Comment by frederikhors** [comment]
I tried your suggestion from https://github.com/sagiegurari/cargo-make/issues/678.

I read the guide https://github.com/sagiegurari/cargo-make#global-configuration-1.

But it seems to me that the path for Windows must be `C:\Users\Fred\AppData\Roaming` which can be found with powershell using `$env:appdata` or with `%APPDATA%` in Win+R command.

I then created a `config.toml` file there with `log_level = "error"` in it but it doesn't work, I can still see all the `INFO` logs.

**Comment by sagiegurari** [comment]
can you try to create a subdir there called cargo-make and put the file there?
I think you misunderstood the docs.

**Comment by sagiegurari** [comment]
@frederikhors please check my answer and reopen if its not solved

**Comment by frederikhors** [comment]
It works! Thanks!
