### ISSUE TITLE
JSON schema outdated?

### ISSUE THREAD

**Issue by frederikhors** [sagiegurari/cargo-make#679]
i think the JSON schema is outdated: https://github.com/tamasfe/taplo/issues/294#issuecomment-1200476690

**Comment by sagiegurari** [comment]
@frederikhors thanks for updating me. ya, i'm not the one who originally wrote it and I do not maintain it.
However, if you could push a PR to that repo to update it, it would be appreciated :)
since the code is not hosted in this repo, i'll be closing this issue since its not actionable here.

**Comment by frederikhors** [comment]
The repo I linked is not who maintains the json schema.

Do you know which is the repo? I can PR if we know which is.

**Comment by frederikhors** [comment]
Sorry we can PR here: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/cargo-make.json.

**Comment by frederikhors** [comment]
Done https://github.com/tamasfe/taplo/issues/294#issuecomment-1200476690.

**Comment by sagiegurari** [comment]
thanks a lot @frederikhors
