### ISSUE TITLE
Cargo make incompatible with Rust 1.64 Workspace Inheritance

### ISSUE THREAD

**Issue by Voxelot** [sagiegurari/cargo-make#712]
### Describe The Bug
As of Rust 1.64, a package version can be set using `version.workspace = true`. 

cargo-make expects PackageInfo.version to be an `Option<String>`, and is unable to parse the new map structure.

https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table

### To Reproduce
Using Rust 1.64, set "version.workspace = true" in a workspace package to trigger the parsing error.

### Error Stack

```console
[cargo-make] INFO - cargo make 0.36.0
thread 'main' panicked at 'Unable to parse Cargo.toml, invalid type: map, expected a string for key `package.version` at line 3 column 21', /home/voxelot/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-make-0.36.0/src/lib/environment/crateinfo.rs:194:27
```

**Comment by sagiegurari** [comment]
oh... thanks for reporting. I'll handle that today

**Comment by Voxelot** [comment]
I also forgot to mention that this may also affect the parsing of inherited package deps, but I didn't get far enough to test if that was an issue or not for cargo-make.

**Comment by sagiegurari** [comment]
@Voxelot i've pushed a fix for the package inherit support in a dev branch 0.36.1
would love your feedback if it works well for you.

as for dependencies, it might be less critical, but also more tricky as i support workspace emulation.

**Comment by sagiegurari** [comment]
@Voxelot the fix is now released. you can reinstall cargo-make to get it. thanks for notifying me
