### ISSUE TITLE
CARGO_PROFILE sometimes does not get resolved

### ISSUE THREAD

**Issue by morenol** [sagiegurari/cargo-make#715]
### Describe The Bug
When using something like:

`cargo make --env-file .env <some-target>`
Sometimes, CARGO_PROFILE and CARGO_MAKE_GIT_HEAD_LAST_COMMIT_HASH don't get resolved.

I will try to create a sample project with the issue. At least with version 0.34.0, I don't experience that issue

**Comment by sagiegurari** [comment]
* CARGO_PROFILE - cargo make doesn't set that env var at all actually. it is cargo that does that. Did you mean CARGO_MAKE_CARGO_PROFILE that is defined by cargo-make and can be used in your tasks? or CARGO_MAKE_PROFILE which is not related to cargo at all, but to the cargo-make run?
* CARGO_MAKE_GIT_HEAD_LAST_COMMIT_HASH - only set if you are in git repo with value that i'm able to extract. I use the git_info crate (also mine) to do that

same project would be best if you can

**Comment by sagiegurari** [comment]
closing due to lack of feedback
