### ISSUE TITLE
`set_env` doesn't work in `env_scripts`

### ISSUE THREAD

**Issue by Alfred-Mountfield** [sagiegurari/cargo-make#718]
### Describe The Bug
I've tried to follow the minimal example for `env_scripts` and `set_env` cannot be found. 
My PC specs:
- macOS Monterey 12.5.1
- Macbook Pro 16-inch 2021
- Apple M1 Max

Toolchain: `stable-aarch64-apple-darwin rustc 1.63.0 (4b91a6ea7 2022-08-08)` 

### To Reproduce
```toml
env_scripts = [
    '''
    #!@duckscript
    set_env REPO_ROOT git rev-parse --show-toplevel
    ''',
]
```

### Error Stack

```console
> cargo make potato
[cargo-make] INFO - cargo make 0.36.1
/var/folders/3_/899yxp217tgd1v7mzt8pqqx80000gn/T/fsio_rCnYX5F81S.sh: line 4: set_env: command not found
[cargo-make] ERROR - Error while executing command, exit code: 127
[cargo-make] WARN - Build Failed.
```

**Comment by sagiegurari** [comment]
duckscript set_env gets a name and value. not a command.
i have other examples on how to set and env from command and its using the env block (no duckscript).

if you do want to use the duckscript option for more complex stuff, than first exec the command and use its output for the set_env

**Comment by Alfred-Mountfield** [comment]
Apologies, my example was probably misleading, the bug is simpler. It's not about the script, it's about `set_env` not being found.

In my various experimentations I did attempt to exec it first and then use it (as you've shown in some examples), I just copied an intermediary state that had other problems (again, sorry!)

Please see the following:

```toml
env_scripts = [
    '''
    #!@duckscript
    set_env REPO_ROOT test
    ''',
]

[tasks.potato]
command = "echo ${REPO_ROOT}"
```

```console
[cargo-make] INFO - cargo make 0.36.1
/var/folders/3_/899yxp217tgd1v7mzt8pqqx80000gn/T/fsio_bIKBmjtZ7e.sh: line 4: set_env: command not found
[cargo-make] ERROR - Error while executing command, exit code: 127
[cargo-make] WARN - Build Failed.
```

**Comment by sagiegurari** [comment]
I think the issue is with your first line.
the shebang needs to start from start of the line without spaces before it.
also, commands are not scripts. command comes with args.
so either use script or command+args.

```
env_scripts = [
    '''
#!@duckscript
    set_env REPO_ROOT test
    ''',
]

[tasks.potato]
command = "echo"
args = ["${REPO_ROOT}"]
```

**Comment by Alfred-Mountfield** [comment]
Ah, it's the indentation. I had copy pasted your examples but my IDE had added indentation when I did paste.

Sorry for wasting your time!

**Comment by sagiegurari** [comment]
no problem :)

**Comment by sagiegurari** [comment]
@Alfred-Mountfield i've pushed a fix (Dev branch currently) that hopefully will prevent such issues in the future and indentation won't break the shebang. thanks for notifying me of this
