### ISSUE TITLE
Multiple tasks?

### ISSUE THREAD

**Issue by qtfkwk** [sagiegurari/cargo-make#719]
### Describe The Bug

Assumption: Usage suggests `<TASK_CMD>...` that I can specify more than one task to be run via `cargo make task1 task2` (or perhaps `cargo make -- task1 task2`?).

```
$ cargo make -h
cargo-make 0.36.1
Sagie Gur-Ari <sagiegurari@gmail.com>
Rust task runner and build tool.

USAGE:
    [makers | cargo make | cargo-make make] [OPTIONS] [--] [<TASK_CMD>...]

ARGS:
    <TASK_CMD>    The task to execute, potentially including arguments which can be accessed in the task itself.
...
```

However when I try it, it ignores task2 and just does task1.

### To Reproduce

Run `cargo make` with 2 or more tasks specified and it should only do the first task.

### Error Stack

n/a

### Code Sample

n/a

**Comment by sagiegurari** [comment]
answer provided.
closing due to lack of feedback

**Comment by qtfkwk** [comment]
> answer provided.
> 
> closing due to lack of feedback

Sorry! Yes, understand it does not do multiple tasks by design. Thank you for clarifying!

**Comment by qtfkwk** [comment]
Meant to leave a link here to my [mkrs crate](https://crates.io/crates/mkrs) which supports multiple targets, among other significant differences with cargo-make.
