### ISSUE TITLE
Task-scoped `env_files` ignores environment variables

### ISSUE THREAD

**Issue by Alfred-Mountfield** [sagiegurari/cargo-make#723]
### Describe The Bug
I was trying to use an environment variable in the path in a task-scoped `env_files` attribute. It seems to just be parsed as a string and therefore always raises an IoError about path not found.

I can see logic that the `env_files` is responsible for loading part of the environment so it might not have environment variables available to it, however this behaves differently to other environment setup mechanisms, and I'd expect it to have anything defined before it in the order specified in the guide:

> Loading Order
> cargo-make will load the environment variables in the following order
> 
> - Load environment file provided on the command line
> - Setup internal environment variables (see Global section). Not including per task variables.
> - Load global environment files defined in the env_files attribute.
> - Load global environment variables provided on the command line.
> - Load global environment variables defined in the env block and relevant sub env blocks based on profile/additional profiles.
> - Load global environment variables defined in the env.[current profile] block.
> - Load global environment setup scripts defined in the env_scripts attribute.
> - **Per Task**
>   - **Load environment files defined in the env_files attribute (relative paths are treated differently than global env_files).**
>   - Setup per task internal environment variables (see Global section).
>   - Load environment variables defined in the env block (same behavior as global env block).

### To Reproduce
Have a basic Rust project inside of a git repository

```.env```
```
TESTING_ENV="Testing"
```

```Makefile.toml```
```toml
[env]
REPO_ROOT = { script = ["git rev-parse --show-toplevel"] }

[tasks.works]
command = "echo"
args = ["${TESTING_ENV}"]
env_files = ["./.env"]

[tasks.broken]
command = "echo"
args = ["${TESTING_ENV}"]
env_files = ["${REPO_ROOT}/.env"]
```
### Error Stack
```sh
> cargo make works
[cargo-make] INFO - cargo make 0.36.1
[cargo-make] INFO - Project: rust_sandbox
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: works
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "echo" "Testing"
Testing
[cargo-make] INFO - Build Done in 0.16 seconds.

> cargo make broken
[cargo-make] INFO - cargo make 0.36.1
[cargo-make] INFO - Project: rust_sandbox
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: broken
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] ERROR - Unable to load env file: ${REPO_ROOT}/.env Error: ReadFile(
    "Unable to read file.",
    IOError(
        "Unable to read file: \"${REPO_ROOT}/.env\"",
        Some(
            Os {
                code: 2,
                kind: NotFound,
                message: "No such file or directory",
            },
        ),
    ),
)
[cargo-make] WARN - Build Failed.
```

**Comment by sagiegurari** [comment]
@Alfred-Mountfield thanks for raising this issue. its actually not related to loading order, but to the fact that makefiles are not shell scripts. not all attributes support env vars.
in this case env_files do not, but i'll add that support now.

**Comment by sagiegurari** [comment]
@Alfred-Mountfield this is now fixed in dev branch 0.36.2
Would love for you to also check it out and tell me it resolves your issue.

**Comment by sagiegurari** [comment]
@Alfred-Mountfield did you by any chance verify this? i would like to release it.

**Comment by Alfred-Mountfield** [comment]
Hi @sagiegurari, really sorry about such a late reply, I completely missed the notification!

Just pulled in your changes and tested it and it seems to be working 👍 , cheers!

**Comment by sagiegurari** [comment]
@Alfred-Mountfield this is now officially released. thanks a lot for checking.
