### ISSUE TITLE
Suggestion: Execute task if (not when) files changed

### ISSUE THREAD

**Issue by adiba** [sagiegurari/cargo-make#73]
Watch changes like in https://github.com/sagiegurari/cargo-make/issues/13, but execution should happen when cargo-make is manually invoked.

**Comment by sagiegurari** [comment]
this is implemented by the commands themselves for example 

* rustc will not recompile if no file was changed.
* cargo watch is given the files/dirs to watch for changes.

Currently this type of monitoring is not even possible in cargo-make which is not aware of what files are being impacted by the task, so this out will have to stay out of scope.

**Comment by adiba** [comment]
Sorry, misunderstood the role of watch task!
