### ISSUE TITLE
Caching capabilities 

### ISSUE THREAD

**Issue by aminya** [sagiegurari/cargo-make#741]
### Feature Description
cargo-make should support skipping a task if its given inputs/output have not changed. Not all the tools have built-in caching capabilities, so the task runner can help.

### Describe The Solution You'd Like

Some of the possible designs:
- `gnu make`: https://www.gnu.org/software/make/manual/html_node/Rules.html#Rules
-  `go task`: https://taskfile.dev/usage/#prevent-unnecessary-work
- `turbo`: https://turbo.build/repo/docs/core-concepts/caching
- ...

### Code Sample

This can be achieved by adding `inputs` and `outputs` properties and checking if they have changed. 

```rust
[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]
inputs = ["**/*.rs", "Cargo.toml", "Cargo.lock", ".cargo/config.toml", "rust-toolchain.toml"]
outputs = []
```

**Comment by sagiegurari** [comment]
I agree its something missing in cargo-make and i'm worried about confusion, so better talk about the meaning of this first.
for example, i have task 'compile' that has a list of input/output files. but task compile has dependencies. lets say only one: 'lint'.
Let's say we see compile is not needed and can be skipped, would i also skip the 'lint'? i would prefer not but is it clear to users?
how are some other tools with similar capability behave?

**Comment by aminya** [comment]
The dependencies should be processed separately before tackling the task itself. The inputs/outputs can only skip the task itself not its dependencies

**Comment by aminya** [comment]
Thanks for the update. I'll test it out.

**Comment by aminya** [comment]
I tried to use cargo-make, however, I faced multiple issues. Not sure if my setup is not correct, but I used the simple example in the readme.

1) it didn't use my makefile commands until I explicitly specified the path to `Makefile.toml`. 
```ps1
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: mytest
[cargo-make][1] INFO - Profile: development
[cargo-make][1] ERROR - Task mytest not found
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 5 - Error while executing command, exit code: 1
```

2) Instead of running the command in the workspace root, it ran it for a package of the workspace, and I have to have `Makefile.toml` in both directories.
```ps1
[cargo-make] INFO - cargo make 0.36.2
[cargo-make] ERROR - Descriptor file: ".\\./Makefile.toml" not found.
[cargo-make] WARN - Build Failed.
```

3) the command input doesn't seem to support external apps like `dprint`. 

```ps1
[cargo-make][1] INFO - Execute Command: "dprint.exe" "check"
[cargo-make][1] ERROR - Error while executing command, error: Error {
    kind: NotFound,
    message: "program not found",
}
```

**Comment by sagiegurari** [comment]
> [cargo-make][1] ERROR - Task mytest not found

without the makefile and sh command you ran can't be sure but feels you haven't defined the task

> [cargo-make] ERROR - Descriptor file: ".\\./Makefile.toml" not found.

same

> [cargo-make][1] INFO - Execute Command: "dprint.exe" "check"
> [cargo-make][1] ERROR - Error while executing command, error: Error {
>     kind: NotFound,
>     message: "program not found",
> }

feels like this exe is not on the path so it can't find it

**Comment by sagiegurari** [comment]
This is now officially released
