### ISSUE TITLE
Whether to split the command into several lines in the script?

### ISSUE THREAD

**Issue by jm-observer** [sagiegurari/cargo-make#760]
hello, Whether to split a command into several lines in the script, The format is similar to
```
[tasks.build-mipsel]
script = '''
wget \
      -o \
      https://github.com/sagiegurari/cargo-make/issues/new
'''
```
the reason for this ack is that my commands are too long to read

**Comment by sagiegurari** [comment]
OS scripts are written to files and executed as is.
so i think what you did should work, no? unless toml format is messing things up?

**Comment by jm-observer** [comment]
Yes，you are right! thanks very much! and use "`" to split in Powershell, and use "^" in Cmd.

**Comment by jm-observer** [comment]
hello, Whether to split a string into several lines in the script, The format is similar to
```
[tasks.build-uclibc-window]
script = '''
docker run --rm -it me/rust-uclibc-openssl:1.65.0_stable_1.0.2u sh -c "echo 'abc' &&
 cat /root/.git-credentials"
'''
```
equal to
```
[tasks.build-uclibc-window]
script = '''
docker run --rm -it me/rust-uclibc-openssl:1.65.0_stable_1.0.2u sh -c "echo 'abc' && cat /root/.git-credentials"
'''
```

**Comment by sagiegurari** [comment]
@jm-observer is this a question/comment/solution? can you please explain?

**Comment by sagiegurari** [comment]
@jm-observer not sure how this is related to cargo make. as i explained, i take the text, put it in a file and run it so it depends on the shell.

for cmd, i googled for it

https://stackoverflow.com/questions/69068/split-long-commands-in-multiple-lines-through-windows-batch-file
