### ISSUE TITLE
Darwin arm64 binaries

### ISSUE THREAD

**Issue by RDIL** [sagiegurari/cargo-make#766]
### Feature Description

It would be cool if pre-built binaries could be enabled for macOS with M1 chips, as they are growing more and more popular.

### Describe The Solution You'd Like

Ship macOS arm64 binaries.

**Comment by sagiegurari** [comment]
actions/runner-images#2187

**Comment by dbanty** [comment]
I do this today by cross-compiling. I run on `macos-latest` and do a `rustup target add aarch64-apple-darwin`, then `cargo build --release --target aarch64-apple-darwin`.

Maybe there is something different about this project which prevents that here, but feel free to look at [Knope](https://github.com/knope-dev/knope/blob/0628ab1f310922b3cb0199bb9c88f30c28d82e31/.github/workflows/publish.yml#LL31C21-L31C41)

**Comment by sagiegurari** [comment]
@dbanty thanks. if you can try it out and push a PR that would be awesome
