### ISSUE TITLE
Incorrect composite environment variables resolution order

### ISSUE THREAD

**Issue by kostko** [sagiegurari/cargo-make#78]
It seems that when an `[env]` section is declared with some composite variables, the variables are *sometimes* not resolved correctly. It looks like this happens due to the incorrect resolution order. Looking at the code it seems that it iterates over a hashmap (which uses arbitrary ordering) and this may be a potential reason for this issue.

For example with:
```toml
[env]
FOO = "bar"
BAR = "${FOO}/foo"
```

Sometimes the `BAR` variable is rendered as `${FOO}/foo` (as if the `FOO` variable was not resolved).

**Comment by sagiegurari** [comment]
Thanks, I'll check it out and fix if needed.
I do have tests around that area, so I'll add few more.

**Comment by kostko** [comment]
The problem is most apparent when using `extend`, most likely because in `merge_env` you copy the elements one-by-one from one map to a new (merged) map, which may affect the order.

I've changed all uses of `HashMap` to `BTreeMap` and this makes the problem go away (see PR #79).

**Comment by sagiegurari** [comment]
cargo-make 0.10.4 was just published with your fix.

**Comment by kostko** [comment]
That's great, thanks!
