### ISSUE TITLE
"Execute Command" log becomes too verbose

### ISSUE THREAD

**Issue by xxchan** [sagiegurari/cargo-make#780]
### Describe The Bug

Take the example in readme as an example:  https://github.com/sagiegurari/cargo-make#simple-example
<img width="805" alt="image" src="https://user-images.githubusercontent.com/37948597/215149272-ddb2e36c-5c6a-4c0b-843b-c1bdc306b913.png">

Now it becomes:
```
❯ cargo make --makefile simple-example.toml my-flow
[cargo-make] INFO - cargo make 0.36.4
[cargo-make] INFO - Project: aaa
[cargo-make] INFO - Build File: simple-example.toml
[cargo-make] INFO - Task: my-flow
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: Command {
    program: "cargo",
    args: [
        "cargo",
        "fmt",
        "--",
        "--emit=files",
    ],
    stdin: Some(
        Inherit,
    ),
    stdout: Some(
        Inherit,
    ),
    stderr: Some(
        Inherit,
    ),
}
[cargo-make] INFO - Execute Command: Command {
    program: "cargo",
    args: [
        "cargo",
        "clean",
    ],
    stdin: Some(
        Inherit,
    ),
    stdout: Some(
        Inherit,
    ),
    stderr: Some(
        Inherit,
    ),
}
[cargo-make] INFO - Execute Command: Command {
    program: "cargo",
    args: [
        "cargo",
        "build",
    ],
    stdin: Some(
        Inherit,
    ),
    stdout: Some(
        Inherit,
    ),
    stderr: Some(
        Inherit,
    ),
}
   Compiling aaa v0.1.0 (/Users/xxchan/Projects/aaa)
   ...
```

It might be better if such detailed logging is only shown when `-v`

### Error Stack

```console
The error stack trace
```

### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
while i totally agree, this actually doesn't happen to me.
i created a new machine via gitpod, installed cargo make, created a new lib crate via cargo and tested:

```
cargo make --makefile simple-example.toml my-flow
[cargo-make] INFO - cargo make 0.36.4
[cargo-make] INFO - Project: _temp1
[cargo-make] INFO - Build File: simple-example.toml
[cargo-make] INFO - Task: my-flow
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "cargo" "fmt" "--" "--emit=files"
[cargo-make] INFO - Execute Command: "cargo" "clean"
[cargo-make] INFO - Execute Command: "cargo" "build"
   Compiling _temp1 v0.1.0 (/workspace/cargo-make/target/_temp1)
    Finished dev [unoptimized + debuginfo] target(s) in 0.41s
[cargo-make] INFO - Execute Command: "cargo" "test"
   Compiling _temp1 v0.1.0 (/workspace/cargo-make/target/_temp1)
    Finished test [unoptimized + debuginfo] target(s) in 0.39s
     Running unittests src/lib.rs (target/debug/deps/_temp1-1f98102cfa961eb9)

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests _temp1

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

[cargo-make] INFO - Build Done in 1.89 seconds.
```

**Comment by sagiegurari** [comment]
@xxchan any chance you modified cargo-make code? or something else global in that machine/rust installation?

**Comment by xxchan** [comment]
After I re-install cargo-make, the problem disapperd. It's quite weird.. Thanks for your quick response anyway!

**Comment by xxchan** [comment]
Hi @sagiegurari I observed the behavior again...

https://buildkite.com/risingwavelabs/pull-request/builds/17098#01863558-a17c-4e39-a2d3-66ad92f7b56d

FWIW the CI runs inside this docker image: `public.ecr.aws/x5u3w5h6/rw-build-env:v20230208_05`

<img width="351" alt="image" src="https://user-images.githubusercontent.com/37948597/217772706-dcf7aa23-599b-4917-b189-c89d21e03a7f.png">

**Comment by sagiegurari** [comment]
from where do these dockers getting cargo-make installation? maybe its some local thing you modified?

**Comment by xxchan** [comment]
I find the reason: It's due to this PR (merged on Dec 27, 2022) [More verbose \`Debug\` implementation of \`std::process:Command\` by kraktus · Pull Request #97176 · rust-lang/rust](https://github.com/rust-lang/rust/pull/97176)

So this line of `cargo-make` is affected:

https://github.com/sagiegurari/cargo-make/blob/7941d5eb13c8be7259a7ec40856d33c1f073a804/src/lib/command.rs#L183

It happens if the latest nightly rust toolchain is used (in our repo we are using `nightly-2023-01-18`, so ...)

**Comment by sagiegurari** [comment]
awesome find! ya, i can lower the detail in the print from debug format to fix that.
or would you like to submit a PR for that?

**Comment by xxchan** [comment]
PR submitted 😄

**Comment by sagiegurari** [comment]
The new cargo-make version is now published.
