### ISSUE TITLE
Document the cwd Attribute

### ISSUE THREAD

**Issue by anlumo** [sagiegurari/cargo-make#787]
### Feature Description

According to [this reddit post](https://www.reddit.com/r/rust_gamedev/comments/10qyf0v/comment/j7fne6h/?utm_source=reddit&utm_medium=web2x&context=3), there's an undocumented `cwd` attribute for command tasks.

### Describe The Solution You'd Like

Documentation for this attribute.

**Comment by sagiegurari** [comment]
thanks @anlumo for reporting
added this section: https://github.com/sagiegurari/cargo-make#usage-setting-up-working-directory
