### ISSUE TITLE
Better Documentation for fork and parallel

### ISSUE THREAD

**Issue by anlumo** [sagiegurari/cargo-make#788]
### Feature Description

The `fork` and `parallel` attributes are very useful for many nonstandard applications, but the documentation is lacking.

### Describe The Solution You'd Like

> It is also possible to run the sub task as a forked sub process using the fork attribute.  
> This prevents any environment changes done in the sub task to impact the rest of the flow in the parent process.

This does not mention that the forked processes are joined again for example, which is mentioned in [this reddit post](https://www.reddit.com/r/rust_gamedev/comments/10qyf0v/comment/j7fozn8/?utm_source=reddit&utm_medium=web2x&context=3).

Also, the use cases for combining `parallel` and `fork` should be documented.

**Comment by sagiegurari** [comment]
@anlumo thanks for reporting. this is now added to the docs :)

https://github.com/sagiegurari/cargo-make#usage-watch-running-multiple-blocking-watches
