### ISSUE TITLE
Very slow startup on large projects

### ISSUE THREAD

**Issue by vitalytarasov** [sagiegurari/cargo-make#795]
### Describe The Bug
A large project with over 100+ dependencies may take up to a minute to execute a single task, no matter how small or simple. It appears that cargo-make invokes other processes before running tasks. For example if a task merely calls to `cp FILE DESTINATION` than clearly there is no need to run any `cargo` commands such as `update` which seems to be running by default. This is not ideal and slows down development and debugging.

### To Reproduce
Use a large project: observe the startup and execution time of `cargo-make`.

### Code Sample

**Comment by vitalytarasov** [comment]
`CARGO_NET_OFFLINE=true` speeds it up a great deal, my question is why does `cargo-make` call `cargo` if there are no `cargo` commands in tasks?

**Comment by sagiegurari** [comment]
mostly checks the project structure. there are few other scenarios.
worth adding your config to the section i pointed to as another perf tuning suggestion.

**Comment by vitalytarasov** [comment]
not ideal in my opinion - a simple task unrelated to `cargo` should not require checking project structure; e.g. GNU `make` does not check sources syntax or styling when asked to compile a file, it is not its job

**Comment by sagiegurari** [comment]
i can only comment if you give me example makefile.toml

**Comment by vitalytarasov** [comment]
here is what i am using at the moment:

```[config]
default_to_workspace = false

[env]
BUNDLE = "/srv/nfs/972604/v2.4.1/build/bundle/bundle.zip"

[tasks.bundle]
command = "cp"
args = ["-v", "build/bundle/app.bundle.zip", "${BUNDLE}"]```

**Comment by sagiegurari** [comment]
another issue was opened to add additional perf logging. 
for now, maybe adding --time-summary when you run might give a bit more info....
but once i do the extra logging it would show more

**Comment by sagiegurari** [comment]
@vitalytarasov 
1. if you check the dev branch 0.36.5 and use the --time-summary flag, you should see a better breakdown of the time and i think you will see it spent in project structure or crate info which would lead me to suspect cargo-metadata (i use that to understand the project structure).
most of the times it is slow when registry is deleted locally. if its not, it takes around a second to finish in my weak pi.
I saw i have an extra call for it and removed it. so on weak machines like mine that saves a second.
2. cargo make does not call other cargo commands like formatting or syntax checks for the makefile you provided. it only uses cargo metadata to understand the project itself, for example workspace members.

**Comment by vitalytarasov** [comment]
thanks; i am a bit frustrated by the fact that cargo-make does things i did not ask it to do, like checking project structure; perhaps it is not the best tool for my task

**Comment by sagiegurari** [comment]
its not check project structure as linter. it checks project structure to determine things like
1. its a workspace and i need to run those tasks on each member
2. prepopulate env vars wirh crate info - you can disable this

feel free to use other tools that better suite your needs
