### ISSUE TITLE
Panic on failing task

### ISSUE THREAD

**Issue by theduke** [sagiegurari/cargo-make#8]
Seems like the current stable version panics when a task fails.

Simple example:

```toml
[tasks.post-build]
dependencies = [
    "format",
    "clippy"
]
```

```bash
...
...
warning: rustfmt may have failed to format. See previous 1 errors.
[cargo-make] ERROR - Error while executing command, exit code: 3
thread 'main' panicked at 'Build Failed.', /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-make-0.3.75/src/logger.rs:56:16
stack backtrace:
   0:     0x560a6c305393 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::ha36f9d6000a258d0
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x560a6c3019ca - std::sys_common::backtrace::_print::h9e51e0c7e57504cc
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x560a6c308fe3 - std::panicking::default_hook::{{closure}}::h6ad513f5b7fa7e45
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x560a6c308d52 - std::panicking::default_hook::h92972e21fe795ab1
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x560a6c309447 - std::panicking::rust_panic_with_hook::h8231d9bc11839b47
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x560a6c198f2a - std::panicking::begin_panic::h527cec84396e91a6
   6:     0x560a6c1b4e43 - cargo_make::logger::init::{{closure}}::h47bedaf674e30241
   7:     0x560a6c2e861c - <fern::log_impl::Dispatch as fern::FernLog>::log_args::h632e7f5f8ffa61f3
   8:     0x560a6c2f3f1a - log::__log::h70c54316b85ca3db
   9:     0x560a6c1b8c94 - cargo_make::command::validate_exit_code::h1aeb6ec528c2e2c5
  10:     0x560a6c1ba24a - cargo_make::command::run_command::hea93f14a5edab934
  11:     0x560a6c1bb498 - cargo_make::runner::run_task::hb7027958db09b457
  12:     0x560a6c1bd56b - cargo_make::runner::run_flow::h6ce16b508ef6d43c
  13:     0x560a6c1bd68f - cargo_make::runner::run::hcb7541bc671237da
  14:     0x560a6c1a98db - cargo_make::main::he7241edaf43a5955
  15:     0x560a6c31024c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  16:     0x560a6c309c6b - std::rt::lang_start::hb98200139e7807ed
                               at /checkout/src/libstd/panicking.rs:459
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:59
  17:     0x7fc8c99404c9 - __libc_start_main
  18:     0x560a6c182719 - _start
  19:                0x0 - <unknown>
```

**Comment by sagiegurari** [comment]
correct. if a task fails, the entire build fails (unless you defined force=true for that specific task). the build fails with an error and than panics with the stack. I could prevent the panic for that specific case and just stop if it will look better.

**Comment by theduke** [comment]
Yeah I think the panic is ugly, panics should only occur on abnormal conditions.

Just a nice error output and then exit the process with a non-zero exit code is much cleaner, imo.

**Comment by sagiegurari** [comment]
done

**Comment by theduke** [comment]
I was it.

I love how responsive you are here, how quickly you incorporate feedback and how good the documentation is.

Great job!

Just two notes:

I don't think you need to release a new version with every small change, that adds a lot of noise for users.
I'd let changes accumulate for a little bit and then release a new version when appropriate.

Also, you need to be careful with changes that affect users.
For example, https://github.com/sagiegurari/cargo-make/commit/1cf0bd5dda07a9e83a84a2a4892ae61bba554062 definitely was a breaking change: it could easily cause builds to fail that worked fine before (as I saw with Juniper). 

The included default tasks are basically part of the public API, so changes there that can change/affect builds are a breaking change, imo.

**Comment by sagiegurari** [comment]
I bump the minor version on breaking changes, that's why I am at 0.3
 which would result in fixes getting stuck. I should try to plan here but that is the main issue with open source I guess, you work on it when you can.

**Comment by theduke** [comment]
Yeah the rust convention is below 1.0, 0.3 to 0.4 is a breaking change.

What I'm saying is that https://github.com/sagiegurari/cargo-make/commit/1cf0bd5dda07a9e83a84a2a4892ae61bba554062 would technically have required bumping to 0.4.

**Comment by sagiegurari** [comment]
Agree, but like I said, didn't think it would break anything so didn't bump and it's probably my mistake there.
