### ISSUE TITLE
Line endings 

### ISSUE THREAD

**Issue by Future998** [sagiegurari/cargo-make#801]
When adding a vendor to git, the line endings is forced to change. What contributes to the breakage of the building for Linux.
This is due to line 1 of the .gitattributes file.

**Comment by sagiegurari** [comment]
i need more info to help here.

**Comment by Future998** [comment]
1. I enter **cargo vendor**,
2. I enter **git add vendor/**,
3. Warnings appear:
**warning: CRLF will be replaced by LF**
(Problem occurs on Linux)

**Comment by Future998** [comment]
You can remove first line in .gitattributes

**Comment by sagiegurari** [comment]
but what problem you have that is related to cargo make?
that warning is coming from git executable

**Comment by Future998** [comment]
The problem is that line endings are specified explicitly in the .gitattributes file.

**Comment by sagiegurari** [comment]
you mean this cargo-make repo gitattributes? i'm not sure why that would matter. you are running a binary in your repo directory.
i'm really having hard time to understand 
1. what you are doing
2. what you are seeing
3. what you expect

**Comment by Future998** [comment]
1. I enter cargo vendor and enter git add vendor/
2. Warnings appear:
**warning: CRLF will be replaced by LF**
(Problem occurs on Linux)
3. I expect line endings to be like on my operating system (Linux). And there will be no warnings.

**Comment by sagiegurari** [comment]
any chance you can send me console commands and output?
i still don't get how this is even related to cargo-make

**Comment by Future998** [comment]
1. I enter `cargo vendor` and enter `git add vendor/`
2. Warnings appear:
`warning: CRLF will be replaced by LF`
(Problem occurs on Linux)
3. I expect line endings to be like on my operating system (Linux). And there will be no warnings.

**Comment by sagiegurari** [comment]
if its in your repo, how is it related to cargo make?

**Comment by Future998** [comment]
It is in the upstream repository that the .gitattributes file says: `* text eol=lf`.

**Comment by sagiegurari** [comment]
not sure why setting text files to lf cause issues. especially on non-windows OS.
what build is it breaking?
i can remove the line but i would like just to fully understand why something like that would break anything as it just makes text files (inside cargo-make respository sources) use the linux/unix eol.

**Comment by Future998** [comment]
When building an RPM package, there are a number of checks, including line endings.

**Comment by sagiegurari** [comment]
ok... strange.
feel free to submit a PR for the gitignore changes and I'll push them

**Comment by sagiegurari** [comment]
@Future998 PR merged. closing this issue unless there is something else related needed
