### ISSUE TITLE
Make default "Makefile.toml" more prominent in the README

### ISSUE THREAD

**Issue by jayvdb** [sagiegurari/cargo-make#804]
### Feature Description
Feedback from https://github.com/Electron100/butane/pull/39#issuecomment-1416859975 , it isnt easy to find that "Makefile.toml" will be used as the default, as most of the examples use `--makefile ..` and the first mention of Makefile.toml is buried in the section https://github.com/sagiegurari/cargo-make#tasks-dependencies-and-aliases

### Describe The Solution You'd Like
Mention the default `Makefile.toml` prominently in the usage section.

**Comment by sagiegurari** [comment]
would you like to submit a PR with the doc improvements?

**Comment by jayvdb** [comment]
Sure.

**Comment by sagiegurari** [comment]
so please update the content.md file and run cargo make generate-readme
thanks :)
