### ISSUE TITLE
target/ directories in the repo

### ISSUE THREAD

**Issue by jayvdb** [sagiegurari/cargo-make#805]
Is https://github.com/sagiegurari/cargo-make/tree/master/examples/workspace/target supposed to be in the repo ?

If so, perhaps a short README there to indicate why it is needed.

Also https://github.com/sagiegurari/cargo-make/tree/master/src/lib/test/workspace1/target

**Comment by sagiegurari** [comment]
its inside examples directory. a bunch of them i use for manual tests or include their content in the readme.
not sure we need to write about it in tge readme since its pretty long already and i think its pretty self explanatory. wdyt?

**Comment by jayvdb** [comment]
The `target/` directories are platform specific, so not much use being shared with others.

But if you need them, ok.  I was thinking a new & short README.md in the `target/` directory just to inform that they are needed.

**Comment by sagiegurari** [comment]
sorry, didnt notice you meant the target specifically. lets remove and add to gitignore
