### ISSUE TITLE
same task that is other tasks' dependency is executed multiple times

### ISSUE THREAD

**Issue by hyangfji** [sagiegurari/cargo-make#819]
### Describe The Bug

If a task that is other tasks' dependency is included in the run_task attribute, it is executed multiple times.

### To Reproduce

This is the Makefile:

[tasks.A]
dependencies = ["C", "D"]

[tasks.B]
dependencies = ["C", "D"]

[tasks.C]
script = "echo C"

[tasks.D]
script = "echo D"

[tasks.all]
run_task = { name = ["A", "B", "C", "D"], parallel = true }

Then run "makers --makefile Makefile all."

### Error Stack

```console
[cargo-make] INFO - makers 0.36.6
[cargo-make] INFO - Build File: Makefile
[cargo-make] INFO - Task: all
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: C
[cargo-make] INFO - Running Task: C
[cargo-make] INFO - Running Task: C
[cargo-make] INFO - Running Task: D
C
[cargo-make] INFO - Running Task: D
C
[cargo-make] INFO - Running Task: D
C
D
D
D
[cargo-make] INFO - Build Done in 0.47 seconds.
```

**Comment by sagiegurari** [comment]
i think the docs don't mention it that well i guess, but run_task starts a new sub flow and therefore is not limited on what dependencies were already invoked.
thats one of the differences between invoking tasks via dependencies and via run_task

**Comment by sagiegurari** [comment]
@hyangfji I've updated the docs to explain it
