### ISSUE TITLE
[documentation] watch attribute documentation

### ISSUE THREAD

**Issue by saona-raimundo** [sagiegurari/cargo-make#824]
### Feature Description

`cargo-make` can trigger a task by watching changes in files.
This is currently documented in 
https://sagiegurari.github.io/cargo-make/#usage-watch

There is a simple option `watch = true` that runs the task every time a file changes in the project.
Fine-tuning of the watched files is briefly explained there. 
The exact current documentation is as follows.
```
You can also fine tune the watch setup (which is based on cargo-watch) by providing an object to the watch attribute as follows:
[tasks.watch-args-example]
command = "echo"
args = [ "Triggered by watch" ]
watch = { postpone = true, no_git_ignore = true, ignore_pattern = "examples/files/*", watch = ["./docs/"] }
```

I could not find more documentation on the arguments or roles to configure the watching.  

### Describe The Solution You'd Like

Some documentation on what attributes can be passed to `watch` and their role.

### Comments

Happy to help if you tell me where to look in the code :)

**Comment by sagiegurari** [comment]
its defined in these docs:
https://sagiegurari.github.io/cargo-make/api/cli/types/struct.WatchOptions.html

if you want to improve the readme, feel free to submit a PR (but update the content.md as readme is generated). thanks :)
