### ISSUE TITLE
Print task names by default

### ISSUE THREAD

**Issue by Marcono1234** [sagiegurari/cargo-make#835]
### Feature Description
When running `cargo make` the task names should be printed to the console. Task names might make it easier to identify a task in the console output than having to check the command it performs.

### Describe The Solution You'd Like
Actually this is already implemented but https://github.com/sagiegurari/cargo-make/commit/0840229a016ebcd7c7018cedd7f29e5ebd2ae8e1 changed it so that the task name is not printed by default. Personally I don't completely understand the rationale for this because printing the task name does not feel very noisy to me (though I only have declared a few tasks).

While this can be changed by setting `reduce_output = false` in the `[config]` section, that config option sounds quite generic and might affect more than just printing the task name.

**Comment by sagiegurari** [comment]
you found the code, but i guess didn't see the complaints :)
i got a lot of those about cargo-make printing out too much and being too verbose.
i too, prefer to see the task names that are executed/skipped but most do not so had this config created for manual execution (for CI i'm more noisy as people don't trigger that in terminal).
i'm not sure what i can do in this issue more than just explain the past. wdyt?

**Comment by Marcono1234** [comment]
> i'm not sure what i can do in this issue more than just explain the past. wdyt?

Not sure, for #630 and #780 it looks like other output from cargo-make, or output from the commands executed was too verbose.
In #194 the user indeed might have complained about the `Running Task: ...` output, but they did not explicitly mention the `Running Task: ...` messages, so maybe your changes back then of reducing other output already sufficed. Additionally maybe the user was not aware of the default tasks which are being run?

For my use case I simply have set `skip_core_tasks = true` for now; maybe in the future I will appreciate these default tasks, but currently they made my setup (in my opinion) too complex because I have to (1) understand where all the cargo-make default tasks are defined, (2) understand what they do, (3) understand how to adjust them for my use case, (4) account for any changes to the default tasks in the future. So for simplicity I just disabled them and defined all tasks explicitly.

I still think the `Running Task: ...` output is not very verbose, especially considering that it makes it easier to identify the task. But if you want we can also wait for the opinion of other users, or you can of course also close this issue if you don't want to change the current behavior.

**Comment by sagiegurari** [comment]
so maybe a question, why not use the config option? you already setup a config section.
i am interested to understand why its not a good solution and how to improve it

**Comment by sagiegurari** [comment]
im closing this one for now, but feel free to reopen if you think there is something more concrete we can do
