### ISSUE TITLE
Tasks that inherit IO for pseudo-terminal support in tests

### ISSUE THREAD

**Issue by tmpfs** [sagiegurari/cargo-make#842]
### Feature Description

Is it possible to add a flag that would inherit `stdin`, `stdout` and `stderr` from the parent process so that we can start pseudo-terminals when running tests?

I am using `rexpect` to test a command line tool and also using `cargo-make` to run all my integration tests.

When I run the CLI integration tests directly (`cargo test`) they work as expected however when I run via `cargo make` they hang forever which I assume is because tasks are spawned processes that use pipes for the IO of the child process.

### Describe The Solution You'd Like

Add an `io = inherit` (or similar) option to tasks/scripts that would allow the child process to use pseudo-terminals.

I looked in the docs and couldn't see anything about this so apologies if this already exists!

Thanks 🙏

**Comment by sagiegurari** [comment]
there are few issues in this area and few ah hoc solutions implemented.
suggest you take a look at 
https://github.com/sagiegurari/cargo-make/blob/master/src/lib/command.rs
and maybe file a PR to configure this new behavior.
wdyt?

**Comment by tmpfs** [comment]
Looks like modifying some of those functions to also support the `capture_output` flag would be pretty straightforward. I guess the challenge will be threading through the configuration from https://github.com/sagiegurari/cargo-make/blob/master/src/lib/types.rs#L1054 into the calls to run the command or do you think that would be straightforward to?

**Comment by tmpfs** [comment]
Apologies @sagiegurari this was a bug my end with incorrect handling of environment variables included from a parent Makefile used for code coverage - my bad!
