### ISSUE TITLE
Allow to completely silence logs, configure from [config]

### ISSUE THREAD

**Issue by yoav-lavi** [sagiegurari/cargo-make#846]
### Feature Description

At the moment `--quiet` or `--loglevel=error` will still output log lines if an error is encountered.
If you're working on a CLI (or just don't want logs) and are using cargo-make to automate various tasks you may want to get "passthrough" output without any cargo-make specific logs

### Describe The Solution You'd Like

A `--silent` (for example) flag that silences all output other than script / binary STDOUT / STDERR
(would also be useful to be able to configure this in the script `[config]` section)

Thanks for your consideration!

**Comment by yoav-lavi** [comment]
> as for config section, its too late. cargo-make will spit out log output before even reading the makefile.toml, for example if it fails to find the makefile.toml it will say so and exit.

Are there default logs before that point that aren't errors? 
It might make sense to make it suppress any log that isn't one of those errors, the goal being that everyone gets the same experience in a team rather than each person needing to define it for themselves.

The solution makes sense, I hope I'll be able to PR it sometime soon but can't make any promises, will update.

Thanks!

**Comment by yoav-lavi** [comment]
I've also noticed that `--quiet` can swallow STDOUT from scripts, e.g.

```toml
[tasks.prettier]
description = "Runs Prettier and writes the results"
script = '''
npx prettier --write .
'''
```

with 

```sh
cargo make --quiet prettier
```

Will produce no output from Prettier itself on errors

**Comment by sagiegurari** [comment]
@yoav-lavi a new --slient flag (or --loglevel off) has been added to dev branch 0.36.8
feel free to try it out.
i've not added (and not planning to) add logger setup to the toml file config section

**Comment by sagiegurari** [comment]
@yoav-lavi  this is now officially released

**Comment by yoav-lavi** [comment]
Thank you @sagiegurari! will check it out and reply back here if there's any suggestions.
