### ISSUE TITLE
`--list` flag

### ISSUE THREAD

**Issue by yoav-lavi** [sagiegurari/cargo-make#848]
### Feature Description

Add a `--list` flag to list the available tasks with their description (this would act like `--list-all-steps` but only show proper tasks rather than things like `init` and `end` and would be more discoverable / intuitive (IMO) than using `--list-all-steps` for this purpose)

Note: this could possibly filter by platform / condition (or just show unavailable tasks as grey / crossed out)

e.g.

```
cargo make --list
```

```
Tasks
----------
clippy             Runs Clippy
clippy-nightly     Runs Clippy on the nightly toolchain
test               Runs cargo-nextest
```

**Comment by sagiegurari** [comment]
I didn't fully understand the difference between the current cli capability apart of not showing init/end tasks and few others that can be hidden if they are private

**Comment by yoav-lavi** [comment]
Although I see `--list-all-steps` does filter out `private=true` tasks so the difference isn't huge

**Comment by sagiegurari** [comment]
@yoav-lavi going back to this issue, so you want list-steps to show steps that will be executed  if you run task X for example? isn't that '--print-steps '?
i'm trying to understand what is really missing and i'm just not sure

**Comment by sagiegurari** [comment]
@yoav-lavi i've added a new flag (--hide-uninteresting) for both list cli commands so hooks (pre-/post-/init/end/empty) are excluded from the output.
I hope this would resolve your issue.
you can try it out in the dev branch 0.36.8

**Comment by sagiegurari** [comment]
@yoav-lavi  this is now officially released. if you feel something more should be added here, please open a new issue and lets talk about the gap

**Comment by sagiegurari** [comment]
you can set that alias in your bashrc :)

**Comment by yoav-lavi** [comment]
Sure, I meant as a builtin alias, I'll be doing so regardless :)
