### ISSUE TITLE
merge together alias tasks in `--list-all-steps`

### ISSUE THREAD

**Issue by xxchan** [sagiegurari/cargo-make#862]
### Describe The Solution You'd Like

Change
```
Misc
----------
l - Description
logs - Description
```
To
```
Misc
----------
logs - Description [aliases: l]
```

Would that be better? 

### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
cool idea. would you like to PR that?
i think all code should go into:
https://github.com/sagiegurari/cargo-make/blob/master/src/lib/cli_commands/list_steps.rs

**Comment by xxchan** [comment]
> would you like to PR that?

Yes I can do it.

**Comment by sagiegurari** [comment]
released new cargo-make version. thanks for the PR.
