### ISSUE TITLE
ENV_VAR=${ENV_VAR} get the unexpexted value if "ENV_VAR" is unset

### ISSUE THREAD

**Issue by Dirreke** [sagiegurari/cargo-make#864]
when I set ENV_VAR="${ENV_VAR};path1" in tasks, ("ENV_VAR" is unset before), I get `ENV_VAR=${ENV_VAR};path1` but not `;path1`.

is it designed as this?

**Comment by sagiegurari** [comment]
what are you trying to actually do?

**Comment by Dirreke** [comment]
I have a series of unit tasks. And I will combine some of them in different order to form new tasks. Before every unit tasks start, I want to add a path to ENV_VAR to record them to finish the follow-up tasks.

like this
```
[tasks.task1]
env = { ENV_VAR = "${ENV_VAR};path1}
command = "cmd1"


[tasks.task2]
env = { ENV_VAR = "${ENV_VAR};path2}
command = "cmd2"

[tasks.task3]
command = "cmd3"
args = ["@@split(ENV_VAR)"]

[tasks.task-main]
run_task = { name = [
    "task1",
    "task2",
    "task3"
]}
```

**Comment by sagiegurari** [comment]
ok, so at the moment, it do not remove the var requested if not found so i don't mess up scripts and such that might be triggered. but you can play around that in 2 ways

1. make sure its defined, and define it as empty is not already defined.
ENV_VAR = { value = "", condition = { env_not_set = ["ENV_VAR"] } }

2. use duckscript where you can basically do anything you want:
https://github.com/sagiegurari/cargo-make#env-setup-scripts

i would prefer not to change existing behavior as it will be a backward break.

**Comment by Dirreke** [comment]
Thanks so much!

**Comment by sagiegurari** [comment]
released new cargo-make version. feel free to reopen for any issue
