### ISSUE TITLE
Add `cargo make init` to create minial Makefile.toml

### ISSUE THREAD

**Issue by ethever** [sagiegurari/cargo-make#870]
### Feature Description
Add `cargo make init` to create minial Makefile.toml

### Describe The Solution You'd Like
Add `cargo make init` to create minial Makefile.toml

### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
the default makefile is embedded. you can start without any makefile. so what would you like to see there?

**Comment by sagiegurari** [comment]
all these exist without any makefile, out of the box:

https://github.com/sagiegurari/cargo-make/blob/master/docs/cargo_make_task_list.md

**Comment by ethever** [comment]
> so what would you like to see there?

I want to fully custom my task flow for my project, when i create a `Makefile.toml` in the `root path` of my project:
``` bash
(base) root@DESKTOP-D2P8H7D:~/projects/books_ic_monorepo# ls -lah Makefile.toml 
-rw-r--r-- 1 root root 197 Jun 11 23:00 Makefile.toml
```
with the content: 

``` bash 

(base) root@DESKTOP-D2P8H7D:~/projects/books_ic_monorepo# cat Makefile.toml 
[tasks.gendid]
command = "cargo"
args = ["test", "-p", "books_ic", "--target", "x86_64-unknown-linux-musl"]

[tasks.test]
command = "cargo"
``` 
then i ran `cargo make --makefile ./Makefile.toml gendid`:
``` bash
(base) root@DESKTOP-D2P8H7D:~/projects/books_ic_monorepo# cargo make --makefile ./Makefile.toml gendid
[cargo-make] INFO - cargo make 0.36.10
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Build File: ./Makefile.toml
[cargo-make] INFO - Task: gendid
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: workspace
/root/projects/books_ic_monorepo
[cargo-make][1] INFO - Calling cargo metadata to extract project info
[cargo-make][1] INFO - Cargo metadata done
[cargo-make][1] INFO - Project: books_ic
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: gendid
[cargo-make][1] INFO - Profile: development
[cargo-make][1] ERROR - Task gendid not found
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 5 - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```
I am new to `cargo make`, and i am learning hard on the docs. i want to know where the point i missed.

**Comment by ethever** [comment]
> all these exist without any makefile, out of the box:

With `cargo make init` subcommand to generate the minial `Makefile.toml` probably make the `out of the box` task more customizable while still keeps `out of box` i think.

**Comment by sagiegurari** [comment]
they are customizable. i think we should discuss it after you go over the docs about how to extend makefiles and tasks.

**Comment by ethever** [comment]
I figured it out. Great project, awesome!
