### ISSUE TITLE
[feature request] print all environment variables set by cargo-make

### ISSUE THREAD

**Issue by xxchan** [sagiegurari/cargo-make#889]
### Feature Description

(Not urgent, just a good-to-have idea)

I'd like to have that for debugging. Format would be like below, but only for the envvars set by cargo-make.
```rust
println!("env vars:")?;
for (key, value) in env::vars() {
    println!("{}={}", key, value)?;
}
```
Benefits:
- a summary of all env vars in one place.
- can be copied directly to scripts.

`--verbose` have some outputs though. 
```
[cargo-make] VERBOSE - Setting Env: BUILD_MODE_DIR Value: debug
```

Besides, currently `env` is logged in `--verbose`, but not `env_files` and `env_scripts`.

### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
@xxchan sorry for really late reply.
1. all env vars are also duckscript vars, so you can always have some script like this:

vars = dump_variables
echo ${vars}

you can add this script as a task like i have my built in print tasks that provide certain runtime info.

2. vars are set in different places, sometimes in scripts. so i'm not sure i can easily add printouts everywhere and have those consistent.

**Comment by sagiegurari** [comment]
closing due to lack of feedback
