### ISSUE TITLE
Would it be possible to have a on failure or a do always clause for clean up related tasks? 

### ISSUE THREAD

**Issue by piperRyan** [sagiegurari/cargo-make#89]
In my particular use case I have a series of system tests that I would like to automate with cargo make. In essence the logic is bring docker services up then run a battery of tests with cargo then shut down the containers. However, when a test fails or something returns an error status the containers won't get shut down as part of the script.  I can write this in bash, but it would nice if I could centralize my project flow process to just one tool.

**Comment by sagiegurari** [comment]
that's a pretty good idea :+1:

**Comment by sagiegurari** [comment]
Initial development was pushed. I guess if build will work, you can test it.
After I finish some other issues, I'll officially release it.

**Comment by sagiegurari** [comment]
0.10.8 was just published.
You can checkout the [docs](https://github.com/sagiegurari/cargo-make#usage-catching-errors)
If you could please verify it is working good for you and I'll close this issue afterwards.

**Comment by piperRyan** [comment]
Yup, this is working good for me. :+1:

**Comment by sagiegurari** [comment]
thanks for confirming
