### ISSUE TITLE
ansi_term dependency is not maintained

### ISSUE THREAD

**Issue by wmmc88** [sagiegurari/cargo-make#913]
### Feature Description
This crate depends on `ansi_term` which is unmaintained according to [this security advisory](https://rustsec.org/advisories/RUSTSEC-2021-0139). The following warning shows up when running `cargo audit`:

```
 ❯ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 555 security advisories (from C:\Users\melvinwang\.cargo\advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (194 crate dependencies)
Crate:     ansi_term
Version:   0.12.1
Warning:   unmaintained
Title:     ansi_term is Unmaintained
Date:      2021-08-18
ID:        RUSTSEC-2021-0139
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0139
Dependency tree:
ansi_term 0.12.1
└── cargo-make 0.36.12
```

### Describe The Solution You'd Like
It seems like many other crates in the rust community have moved on to use [`nu-ansi-term`](https://github.com/nushell/nu-ansi-term), which is a fork of the original dependency. At a glance, it looks like it might be a drop-in replacement.

**Comment by sagiegurari** [comment]
@wmmc88 thanks for reporting. I'll probably do the same switch

**Comment by sagiegurari** [comment]
@wmmc88 this is now released
