### ISSUE TITLE
Sub-command docs improvement

### ISSUE THREAD

**Issue by janosimas** [sagiegurari/cargo-make#923]
### Feature Description
The current example for sub-commands using `extend` has some limitations, including the ability to list the allowed commands in the sub-command.

### Describe The Solution You'd Like
Use an external file for a sub command.

### Code Sample

```rust
[tasks.foo]
args = ["--makefile", "${FOO_CONFIG_DIR}/Makefile.foo.toml", "${@}"]
category = "Subcommands"
command = "makers"
description = "Foo subcommands"
```

Some benefits of this approach:
-  allows to use the usual options for `cargo-make` like `--list-all-steps` to get the sub-command specific commands
- commands don't require a specif prefix
- allows `[config]` options per sub-command

A limitation of this approach is the lack of auto-complete. I didn't investigate this yet.

**Comment by sagiegurari** [comment]
is this basically a documention question?
since both current example and yours are supported, right?

**Comment by janosimas** [comment]
This is a suggestion to improve the documentation.
I think the current example is not the best method considering it limits some of the options that `cargo-make` provides.

**Comment by sagiegurari** [comment]
@janosimas sorry for late reply. 
if you want to PR an additional sub command solution alternative, i'm for it.
lets push for both so users can pick and also understand how cargo-make works.
wdyt?
