### ISSUE TITLE
Allow `script_runner` for `load_script`

### ISSUE THREAD

**Issue by wmmc88** [sagiegurari/cargo-make#926]
### Feature Description
I would like to be able to specify the script runner for load scripts. One possible use case of this is setting the script runner to pwsh to get access to things like `invoke-restmethod` or `invoke-webrequest` to download other cargomake files to extend

**Comment by sagiegurari** [comment]
@wmmc88 sorry for really late reply.
did you look at shebang support?
https://github.com/sagiegurari/cargo-make#usage-task-command-script-task-exampleshebang

**Comment by wmmc88** [comment]
Since I'm om windows and cmd is the default script runner for loadscripts, shebang are not supported

**Comment by sagiegurari** [comment]
if you put the duckscript shebang it will work and not even trigger cmd.

i wonder if powershell will fail only a line that starts with # (no idea, haven't really used ps)

**Comment by sagiegurari** [comment]
@wmmc88 powershell does support # as comment char.
so you could use the shebang support (its not native support, its built in cargo-make).
see
https://github.com/sagiegurari/cargo-make#shebang-support

**Comment by sagiegurari** [comment]
@wmmc88 did it resolve your issue?
you can use duckscript to do many operations not natively available in window cmd.
i'm not 100% sure of the use case, so would like some feedback.

**Comment by wmmc88** [comment]
> @wmmc88 powershell does support # as comment char. so you could use the shebang support (its not native support, its built in cargo-make). see https://github.com/sagiegurari/cargo-make#shebang-support

How would i go about doing this? `#!@powershell` and `#!@pwsh` do not work.

I also dont think duckscript does not support what I want to do. I need access to something like powershell's `Invoke-RestMethod` in order to pull down a private cargo-make file via github rest requests to extend

**Comment by sagiegurari** [comment]
duckscript has a http get command built in. worth checking.

**Comment by sagiegurari** [comment]
https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__net__HttpClient

**Comment by sagiegurari** [comment]
@wmmc88 did the duckscript http api resolve your issue?

**Comment by sagiegurari** [comment]
@wmmc88 also i still think the shebang line would enable you to trigger powershell directly.
can you try something like this:

```toml
[config]
load_script = """
#!powershell
echo hello
"""
```

It should cause cargo-make to trigger: "powershell ./scriptfile_with_your_content.sh"

**Comment by wmmc88** [comment]
> @wmmc88 did the duckscript http api resolve your issue?

I ended up just invoking pwsh.exe with my inline script from the `load_script`: https://github.com/microsoft/Windows-rust-driver-samples/blob/ee293426e8cd2ac68d56d564e43e3b9117443b72/Makefile.toml#L8C9-L8C9

Definitely not ideal, but it was enough to unblock me. I will look into switching to the duckscript api if i get some free cycles in the future.

> @wmmc88 also i still think the shebang line would enable you to trigger powershell directly. can you try something like this:
> 
> ```toml
> [config]
> load_script = """
> #!powershell
> echo hello
> """
> ```
> 
> It should cause cargo-make to trigger: "powershell ./scriptfile_with_your_content.sh"

Ah! from the docs, i thought i needed to have an additional `@`, so i was wondering why `#!@powershell` and `#!pwsh` didn't work. However, it still doesnt work since it tries to execute the script in a temporary `.sh` file and powershell accepts only files with `.ps1` extension:

`Makefile.toml`
```
[config]
load_script = """
#!pwsh
Write-Output "HELLO!"
"""
```

Output
```
cargo make
[cargo-make] INFO - cargo make 0.37.0
[cargo-make] INFO - Execute Command: "pwsh" "C:\\Users\\MELVIN~1\\AppData\\Local\\Temp\\fsio\\fsio_C65I0u55lw.sh"
Processing -File 'C:\Users\MELVIN~1\AppData\Local\Temp\fsio\fsio_C65I0u55lw.sh' failed because the file does not have a '.ps1' extension. Specify a valid PowerShell script file name, and then try again.
```

**Comment by sagiegurari** [comment]
@wmmc88 can you try same setup with the dev branch 0.37.2 which contains some default extension setup for the runner?
this means it will setup ps1 for your powershell invocation.
if it is ok, i'll release it

**Comment by wmmc88** [comment]
> @wmmc88 can you try same setup with the dev branch 0.37.2 which contains some default extension setup for the runner? this means it will setup ps1 for your powershell invocation. if it is ok, i'll release it

I tested it and verified that the fix works. Thanks @sagiegurari !

**Comment by sagiegurari** [comment]
@wmmc88 this is now officially released. thanks for validating it.
