### ISSUE TITLE
Cannot generate coverage report for workspace

### ISSUE THREAD

**Issue by quake** [sagiegurari/cargo-make#97]
#### Problem Description
This is my workspace structure:
```
member_a
  | src
    lib.rs
  Cargo.toml
member_b
  | src
    lib.rs
  Cargo.toml
src
  lib.src
  Cargo.toml
  Makefile.toml
```
Add env to Makefile.toml
```
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
CARGO_MAKE_TEST_COVERAGE_BINARY_FILTER = "${CARGO_MAKE_CRATE_FS_NAME}-[a-z0-9]*$"
```

No coverage report generated after running cargo-make in workspace root folder:
```
cargo make --no-workspace workspace-ci-flow
```

It is suspected that `CARGO_MAKE_CRATE_FS_NAME` is using root crate name instead of member crate name, could you help to check?

**Comment by sagiegurari** [comment]
I don't think the env value gets messed up.
do you have some sample repo for me to clone and check?

**Comment by quake** [comment]
I created a sample repo here:
https://github.com/quake/cargo-make-foo

**Comment by sagiegurari** [comment]
Thanks, in your example CARGO_MAKE_CRATE_FS_NAME is ok, but CARGO_MAKE_TEST_COVERAGE_BINARY_FILTER is not for some reason.
I will investigate it.

**Comment by sagiegurari** [comment]
think I found the issue, i'm testing now and will release a new version soon.

**Comment by sagiegurari** [comment]
version 0.11.3 published, took me a while to understand the regression bug there.
please try it out and tell me if its working well or needs more work.

**Comment by quake** [comment]
It works, thank you very much!
