### ISSUE TITLE
`CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY` is empty when no `build.target`

### ISSUE THREAD

**Issue by wmmc88** [sagiegurari/cargo-make#972]
### Describe The Bug

`CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY ` is described in the [readme](https://github.com/sagiegurari/cargo-make/blob/ad486eb35f480927fb06b9f216ef8f3ce1873a8f/README.md?plain=1#L1738) as:
> Like `CARGO_MAKE_CRATE_TARGET_DIRECTORY` but respects `build.target` in `.cargo/config.toml`.

The actual behaviour if `build.target` is not specified in a `.cargo/config.toml` is that `CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY` evaluates to nothing. Based off the above documentation, I would expect the behaviour to be that it falls back to `CARGO_MAKE_CRATE_TARGET_DIRECTORY` when `build.target` is not specified

**Comment by sagiegurari** [comment]
fair point. will fix that.

**Comment by sagiegurari** [comment]
@wmmc88 can you verify this works well for you in the dev branch 0.37.3?

**Comment by wmmc88** [comment]
I verified this worked. Thanks @sagiegurari

**Comment by wmmc88** [comment]
In my testing, i found that having an array in `build.target` fails, but it seems that this was already the existing behaviour. Is this knowingly not supported by `cargo-make`?

**Comment by sagiegurari** [comment]
can't remember. I think this was developed by others

**Comment by sagiegurari** [comment]
this is now released
