### ISSUE TITLE
A separate platform type for BSD

### ISSUE THREAD

**Issue by filips123** [sagiegurari/cargo-make#989]
### Feature Description

Currently, [conditions treat](https://github.com/sagiegurari/cargo-make/blob/master/src/lib/types.rs#L20-L28) all non-Windows, non-macOS OSes as Linux, which includes BSD. Although BSD is pretty similar to Linux in most normal cases, there are still some differences that might require special handling for Linux and macOS. For example, the software is commonly installed to `/usr/local/` on BSD, while on Linux it's commonly just `/usr/`. Additionally, some commands work differently on BSD than on Linux. Because of this, it should be possible to differentiate between them and specify a separate task for each of them.

### Describe The Solution You'd Like

One solution would be to add `bsd` to a list of platforms, probably with a cfg like this (to match most common BSD versions), and update the platform handling everywhere it's needed:

```
any(target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd")
```

However, this is likely a breaking change that will break all scripts/tasks that only target Linux and are expected to also work on BSD. A better solution could be to check if both Linux and BSD are separately specified for the task and only differentiate between them in that case, but still treat Linux as BSD if only Linux (and other OSes) is specified as a task platform. However, this is probably harder and I'm not sure how feasible it is.

Alternatively, is there a way to manually specify `cfg` attributes for a task? For example, like it's possible for Cargo dependencies:

```toml
[target.'cfg(any(target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
```

**Comment by sagiegurari** [comment]
I also hate the limitation i did at the very begining of this project (and few other mistakes....), and as you said, adding another platform value would be a big backward break.

i wonder if we can do something else like platform but call it 'os' and put the exact value we get from rust target_os there and than allow condition on OS value.
anyone using the platform condition would not be impacted and anyone using OS platform would be in sync with what rust can provide during installation+compilation time of cargo-make in the local machine.

wdyt?

**Comment by filips123** [comment]
That could probably work. However, it should also allow some mechanism like `any`, `all` and `not` for conditional compilation, so you can target multiple OSes with one task.

**Comment by sagiegurari** [comment]
ya got similar capability for other conditions. its doable.

**Comment by sagiegurari** [comment]
@filips123 this is now available as condition 'os' and works like 'platforms' but you need to put the cfg(target_os) value there. this way it supports everything that rust supports directly.

**Comment by filips123** [comment]
Thank you!
